### ISSUE TITLE
Move Blockstore client API write-up to wiki

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#100]
Here's my super-alpha take on the blockstore API.  Please note that this is the **client-side, front-end API**--it needs the user's private key, or (down the road) a delegated key.

**Terminology**
- **immutable data**:  This is content-addressed data whose hashes are written to the underlying blockchain in an OP_RETURN transaction, signed off by the writer's private key.  The rationale behind providing "immutable" data is to provide a way of a writer to upload data that will not change, but whose integrity and owner can be confirmed by the blockchain.  Immutable data can be hosted anywhere by anyone; a reader can verify that a given piece of data is authentic and owned by someone (given that someone's public key) by checking for its hash and signature in the OP_RETURN.  The reader does not have to trust the source of the data; only the blockchain.
- **mutable data**:  This is named data whose existence, ownership, and location are written to the underlying blockchain in an OP_RETURN transaction, signed off by the writer's public key.  The rationale behind providing "mutable" data is to provide a way for a writer to upload data that will change frequently, but still guarantee to the reader that the data the reader gets is authentic and fresh.  Mutable data must be hosted on one of a pre-defined set of servers, but the data's ownership, location, and any extra unchanging metadata are confirmed by the blockchain.  The API for mutable data envelopes a read and write protocol that additionally ensures that readers will only receive authentic data, and that readers cannot be fed old versions of data once they have been seen for the first time.
- **ancillary storage**:  General-purpose services like our DHT, or like IPFS, Syndicate, Tahoe-LAFS, Amazon S3, or even a humble FTP server.  They merely hold copies of the data we send them; we construct the data such that they cannot serve data that a writer did not produce, and cannot serve an older version of data to a reader once the reader has seen a newer version.
- **default ancillary storage provider**:  The blockstore API library can be configured to contact a default storage provider, specific to the application.  Each method lets the caller choose how to contact ancillary storage of its choice, but in the context of a single application that hosts replicas of user data, this is redundant (hence the need to add a notion of a default provider).
- **route**:  A JSON document encoding, among other things, the name and locations of mutable data (see below).

**Route schema**

```
{
   "id": string,
   "urls": [string],
   "pubkey": string
}
```
- `id` is an unchanging, unique identifier for the data.
- `url` is an array of strings that determine the location(s) of the current copies of the data.  The data returned by `url` must encode enough information to construct a mutable data schema JSON document (see below).  The easiest way is to simply send the JSON itself, but it's permitted to send something that the client can decode into one as well.
- `pubkey` is the _optional_ public key of the writer, to be used in place of the public key in the blockchain.

**Mutable data schema**

```
{
   "id": string
   "data": string
   "nonce": int
   "sig": string
}
```
- `id` is an unchanging identifier for this data.
- `data` is the string of data to fetch (base64-encoded).
- `nonce` is an integer that represents the instance of the data (i.e. to help the reader discover stale data).  It does **not** need to be monotonically-increasing (but the implementation may do so as an optimization), but it must be unique to the `put_mutable` call that generated it.
- `sig` is the writer's signature over both `data` and `nonce`.

**API**
- `default_get_handlers( immutable_callbacks=None, route_callbacks=None, mutable_callbacks=None )`:  Set the default data-downloading methods for getting immutable and mutable data.
  - A callback in immutable_callbacks has the signature `get_immutable_handler( key ) -> data`, where `key` is the hash of the data.
  - A callback in route_callbacks has the signature `get_route_handler( id ) --> JSON`, where `id` is the mutable data's unchanging ID, and `JSON` is a route document. 
  - A callback in mutable_callbacks has the signature `get_mutable_handler( url ) --> JSON`, where `url` is a URL to the data, and `JSON` is a mutable storage document.
- `default_put_handlers( immutable_callbacks=None, mutable_callbacks=None )`:  Set the default data-uploading methods for writing immutable and mutable data.
  - A callback in immutable_callbacks has the signature `put_immutable_handler( name, key, data, signature ) --> True|False`, where `name` is the name of the writer, `key` is the hash of the data, `data` is the data itself, and `signature` is the writer's private key signature over the data.
  - A callback in mutable_callbacks has the signature `put_mutable_handler( name, id, data, nonce, signature ) --> True|False`, where `name` is the name of the writer, `id` is the unchanging ID of the data, `data` is the data itself, and `signature is the writer's private key signature over the id, data **and** the nonce (all concatenated in that order).
- `default_delete_handlers( immutable_callbacks=None, mutable_callbacks=None )`:  Set the default data-deleting methods for removing immutable and mutable data.
  - A callback in immutable_callbacks has the signature `delete_immutable_handler( name, key, signature ) --> True|False`, where `name` is the name of the writer, `key` is the hash of the data, and `signature` is the signature over the **hash** of the data, not the data itself (i.e. to prove the request's authenticity).
  - A callback in mutable_callbacks has the signature `delete_mutable_handler( name, id, signature ) --> True|False`, where `name` is the name of the writer, `id` is the unchanging ID of the data, and `signature` is the writer's signature over the **id** of the data (i.e. to prove the request's authenticity).
- `get_immutable( key, name=None, publickey=None, get_immutable_handlers=None )`:  Takes the hash of the data (key), and optionally either a username or a WIF-encoded public key, and returns the data.  If name or publickey is given, the method checks the blockchain to see that the data's hash (key) was signed by the writer's public key--either the publickey given, or the public key of the user that owns the name.  This method fetches the data from the ancillary storage system(s), using the default ancillary storage system, or using one of an optional list of callbacks given in get_immutable_handlers.  Each callback takes the key as an argument, and returns the data.
- `get_mutable( id, name=None, publickey=None, get_route_handlers=None, get_mutable_handlers=None )`:  Takes the unchanging id of the data, and either a username or a WIF-encoded public key (exactly one must be given), and returns the data.  If name or publickey is given, the method checks to see that the data was signed by the given publickey, the public key of the user that owns the name, or the `pubkey` in the route (if given).  This method fetches the data from the ancillary storage system(s) by first fetching the route JSON record described above (using callbacks in get_route_handlers if given), and then fetching the data from the URLs given in the route JSON (using callbacks in get_mutable_handlers, if given).  It verifies the signature over the nonce and data, confirms that this nonce has not been seen before, and caches the nonce number locally.  The caller only gets data back if (1) the signature matches, and (2) the data is not stale.
- `link_immutable( name, key, privatekey )`:  Takes the name of the user and the hash of the data (key), and uses privatekey to write the key to the blockchain.  This method does not store data anywhere; it is meant for users who handle data storage separately, and only want the blockchain to attest to the data's ownership and integrity.
- `put_immutable( name, data, privatekey, put_immutable_handlers=None )`:  Takes the name of the user and the data, generates the key, runs `link_immutable` with the name, key, and private key, and replicates the data to ancillary storage.  It sends it off to the default ones by default (e.g. the DHT), but optionally takes a list of callbacks (put_immutable_handlers) to replicate the data to the caller's choice of ancillary storage.  Each callback will take the user name, the data, and signature over the data's hash (i.e .the same signature put into the blockchain) as arguments, and return True or False to indicate whether or not the data was successfully replicated (signature: `put_immutable_handler( name, data, signature ) -> True|False`).  Note that immutable data is content-addressed--there is no notion of write-conflicts.
- `put_mutable( name, id, data, privatekey, put_mutable_handlers=None )`:  Takes the name of the user, the unchanging id for the data, the data itself, generates a mutable data JSON document (see above), and replicates the JSON document to ancillary storage.  The default implementation generates a random nonce for the mutable data.  The method sends the JSON off to the default ancillary storage, or optionally takes a list of callbacks (put_mutable_handlers) to replicate the data to the caller's choice of ancillary storage.  Because mutable data is addressed by an unchanging ID (since the hash keeps changing), the default policy for handling multiple writes is to (1) accept only writes from the data's author (i.e. writes can only come from the user that created it, as identified by the writer's signature), and (2) use a last-write-wins conflict-resolution policy.
- `delete_immutable( name, key, privatekey, delete_immutable_handlers=None )`:  Takes the name of the user and the data's hash (key), and removes it from the user's profile and marks it as deleted in the blockchain.  Also, this method removes the data from ancillary storage.  The caller can supply a list of callbacks (delete_immutable_handlers) to be called to remove data from the caller's ancillary storage providers of choice; if not, the defaults will be used.
- `delete_mutable( name, id, privatekey, delete_mutable_handlers=None )`:  Takes the name of the user, the unchanging id for the data, and the private key, and an optional list of callbacks to contact ancillary storage.  The method will remove the mutable data and the mutable data JSON from default ancillary storage, or pass the request on to the optional list of deletion handlers (delete_mutable_handlers).

**Comment by larrysalibra** [comment]
https://forum.blockstack.org/t/blockstore-client-api-write-up/118/2?u=larry

**Comment by jcnelson** [comment]
We're going to overhaul this with the datastores API.
