### ISSUE TITLE
Add native STX token transfer function

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#1002]

**Comment by lgalabru** [comment]
Is this requirement handled by https://github.com/blockstack/blockstack-core/pull/1074, or do we want / need a native function?

**Comment by jcnelson** [comment]
I don't think it is.  cc @kantai

**Comment by kantai** [comment]
The transfer function itself might be -- `stacks` being a reserved name is really all that is necessary (language-wise) on top of #1074
