### ISSUE TITLE
Add `(some ...)` and `(none)` functions

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#1028]
This will allow users to construct their own Optional types -- this will be most directly useful for persisted variables.

We'll have to expand the type intersection function used in `most_admissable(A, B)`

**Comment by zone117x** [comment]
Should we allow these and `(ok ...)` to the allowed function arg types, so user-defined functions can take `response` and `optional` types?

**Comment by kantai** [comment]
Yeah -- I think for this to be useful we need to add type defintions for `optional` types at least. If we want response types to be supported as arguments as well, we'll need to add that too.

**Comment by kantai** [comment]
Resolved in #1033
