### ISSUE TITLE
how install API node?

### ISSUE THREAD

**Issue by yunsite** [blockstack/blockstack-core#1040]
it's not work:
https://github.com/blockstack/blockstack-core/blob/api/docs/install-api.md

$ blockstack setup_wallet
bash: blockstack: command not found

**Comment by jcnelson** [comment]
Those instructions are deprecated and are no longer necessary.  All you need to do is start up `blockstack-core`, and you can contact the API endpoints on port 6270 (e.g. `curl http://localhost:6270/v1/info` will work).
