### ISSUE TITLE
Ability to admit partial tuples on set-entry!

### ISSUE THREAD

**Issue by lgalabru** [blockstack/blockstack-core#1045]
`set-entry!` expects a value that matches the map's type.
It's perfectly fine when the value is a "simple" type, but when it's a tuple, it makes the operation a bit cumbersome and add some inefficiency: it forces the developer to fetch the current value (unnecessary IO), manually build a tuple value (inconvenient), and ~~update some values that haven't changed (unnecessary IO).~~

That being said, there's an issue with this proposal. 

> This function performs a _blind_ update; whether or not a value is already associated
with the key, the function overwrites that existing association.

We would need to be more strict on that end, and reject `set-entry!` operations that are trying to insert new entries, otherwise we would end-up with partial values being inserted in the DB.

**Comment by lgalabru** [comment]
Adding a short sample pseudo-code for illustrating this issue:

```
(define-map rocket
  ((token-id int))
  ((owner principal) (name buffer) (size int)))

;; Internal - Register token
(define (transfer-rocket (new-owner principal) (token-id int))
  (let ((rocket-to-transfer (fetch-entry rocket (token-id token-id))))
     (set-entry! rocket
       ((token-id token-id))
       ((owner new-owner)
        (name (get name rocket-to-transfer))
        (size (get size rocket-to-transfer))))))
```

vs 

```
(define-map rocket
  ((token-id int))
  ((owner principal) (name buffer) (size int)))

;; Internal - Register token
(define (transfer-rocket (new-owner principal) (token-id int))
   (set-entry! rocket
      ((token-id token-id))
      ((owner new-owner))))
```

**Comment by jcnelson** [comment]
The `value` of a map is atomic, regardless of the type of `value` -- it is not broken into columns.  As such, there is no notion of a "partial update" -- maps are key/value stores through-and-through.  If you find yourself doing excessive I/O to update a map whose values are composed of multiple values that must be read, the solution should be to normalize your data better.

**Comment by lgalabru** [comment]
> it is not broken into columns

Oh right, I missed this detail.
