### ISSUE TITLE
Improved Transaction Sender Verification and First Class Assets

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#1051]
In order to address verification of ownership via transaction sender or origin, we want to provide the following.

1. First class support for Asset types, which will sidestep the problem of permissions by requiring a "maximum spend of any asset" be included in the wire format for a transaction.

2. Allow general purpose ownership checks to express a similar range of checks as other smart contracting languages (in EVM, this distinction is made via `msg.sender` and `tx.origin`).

### 1. First Class Assets

Provide two new “define” primitives:

```scheme
    ;; fungible assets (tokens) do not require a key type -- they are just maps
    ;;   of accounts to balances
    (define-token foo-tokens)
    ;; defining non-fungible assets requires providing a "key type" which will be used to
    ;;   uniquely identify the asset
    (define-asset bar-nfts int)
```

Then, we have some getters/setters:

```scheme
    (transfer-token! token-name      amount from to)
    (transfer-asset! asset-name     identifier from to)
    ;; returns balance of fungible tokens or the count of non-fungible assets
    (get-balance asset-name owner)
    ;; returns owner of non-fungible asset, type check error if applied to fungible tokens
    (get-owner asset-name identifier) 
```

Then, we include in the wire format a set of allowed spends in the transaction. This makes it so that the limit is set outside of the context of the contract execution, and also forces wallet clients to participate in the security measure. The transaction aborts if the allowed spends are exceeded (though, it should be noted, transaction fees would be deducted).

### 2. Expressing general ownership verification

For general purpose ownership checks, we'll give contracts access to two variables:

1. `tx-sender` -- this is the "sender of the transaction", that is the original principal that signed and broadcasted the transaction, _unless_ `as-contract` has been called, in which case the context switches to simulate the current contract principal signing and broadcasting a transaction (i.e., `tx-sender` and `contract-caller` immediately change to the current contract principal).
2. `contract-caller` -- this is the most recent caller of the contract. In the first contract called by a transaction, `(eq? contract-caller tx-sender)` will be true.

**Comment by kantai** [comment]
PR #1046 implements the semantics of Part 2 above -- however, the naming is incorrect.

**Comment by lgalabru** [comment]
will `token` and  `asset` be implemented in rust or clarity?

**Comment by kantai** [comment]
> will token and asset be implemented in rust or clarity?

I think it has to be in rust -- we'll need interpreter level support in order to perform the whitelisting check.
