### ISSUE TITLE
Proposal: contract pays for RPC-like transactions

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#1075]
Hey everyone, I wanted to run this by you all before making it part of the official design in SIP 005.  Let me know what you all think? @kantai @lgalabru @zone117x @yknl 

## Introduction

While drafting SIP 005, it occurred to me that there's a special case where a contract's account could pay the transaction fee instead of the transaction's originating account.  The upside of such a feature would be that **users wouldn't need to own any on-chain assets to send (simple) transactions to a particular contract**.  Instead, the contract's administrators (or user community) would periodically fund the contract's account, so the contract's account would act as a "fee faucet" for transactions that interact with it.  This would be useful for on-boarding new users who don't yet understand or own on-chain assets, and for helping infrequent or anonymous users leverage smart contracts without requiring them to first go out and buy assets.

However, such a feature would have three limitations:

* The transaction's Clarity code body _must_ consist of a single `contract-call!` statement whose arguments are immediate values, and nothing else.  No persistent variable reads or data map reads would be permitted, nor would any other calls to native functions be permitted (i.e. no `get-block-info`, no `get-balance`, etc.).  Moreover, the transaction code body would be capped in length -- i.e. 256 characters or the like.  This is all to ensure that:

   * It will be unambiguous as to which account to bill for the transaction fee (i.e. the contract's account).
   * Malicious users won't be able to get the Clarity VM to work "for free" by passing in complex arguments that need to be evaluated before the contract account can be billed.
   * Validating an eligible transaction will be able to be done using code paths that are "free" to use anyway -- i.e. by invoking only code paths that would be provided via the node's public RPC interface in the first place.

* The smart contract must explicitly signal to the Clarity VM that it will pay for such fees, as well as how much it is willing to pay per transaction.  This will require a new native function in Clarity.

* This feature can only work with whitelisted addresses.  That is, the contract administrator must _explicitly_ state which account addresses can use this contract's funds to pay their transaction fees.  The reason for this is because if there were _not_ a whitelist, then miners could simply steal the funds in the contract account by filling their block with spam transactions that call into the contract for the sole purpose of receiving the contained fees (at the expense of the target users).

## New Native Functions

In order to allow a contract to pay for such transactions' fees, we would need the following new native functions:

```
(define-fees FUNCTION_NAME VARNAME_MAX_FEE)
(fee-add-whitelist! PRINCIPAL)
(fee-rm-whitelist! PRINCIPAL)
```

The `define-fees` function sets the fee rate for calling a particular public function (named by `FUNCTION_NAME`), and is used in conjunction with the name of a data variable that stores the maximum fee rate (an integer).  The it takes the name of a data variable as opposed to a literal is to allow the contract administrator to later update the fee rate, i.e. in response to changing STX values or fee market fluctuations.  The smart contract would define a public function that would allow one or more principals to change the fee rate by way of a transaction.

The `fee-add-whitelist!` function authorizes a principal to spend this contract's funds for its transaction fees, and the `fee-rm-whitelist!` function deauthorizes a principal.  These functions would usually be wrapped in public contract functions for administrating the contract (see the example below).

## How a Contract Pays a Transaction Fee

In order to bill the contract for the transaction, the Clarity VM would do the following:

1. Identify the transaction as eligible to have its fee paid by the contract's account.
   a. First, make sure the transaction code body is short enough to be inspected.
   b. Next, inspect the transaction bytes to see that it has the right version number, and extract the proposed transaction fee amount, and inspect the code body.  While inspecting the code body, do the following two things: 
      1. Determine that the body is composed of only a `contract-call!` with immediate values.
      2. Extract the contract name and public function.

   Note that (i) and (ii) can be done with a single simple regex -- there's no need to use the Clarity VM parser.  Also, note that all of these steps are performed on the "transaction validation" code path -- they're not billable operations, since we haven't yet invoked the Clarity VM.

2. Look up the contract's analysis data to determine if it has specified `define-fees` for the public function in question.  If not, reject.  Note that these operations would already be provided "for free" via the RPC interface, since we want wallets to be able to determine _a priori_ whether or not they can send such a transaction.

3.  Determine whether or not the transaction's signer corresponds to a whitelisted account by querying the contract's fee-spending whitelist.  If not, reject.  Note that this operation would already be provided "for free" via the RPC interface, since we want wallets to determine _a priori_ whether or not they can send such a transaction.

4.  Now we know what account to bill.  Look up the contract's account to see if it can afford to pay the requisite fee to load the `VARNAME_MAX_FEE` variable.  If not, reject.  Note that this is also a "free" operation that we'd be doing on the RPC interface as well -- it's just querying the account balance for an asset, and comparing it to a well-known constant (i.e. the cost of loading a persistent variable).

5.  Bill the contract account for the fee required to just load the `VARNAME_MAX_FEE` variable.  After this, proceed to evaluate the transaction as normal -- calculate the transaction fee from the analysis data on the contract's public function, and if it is sufficient, run the transaction and bill the contract account the fee.  If the fee is insufficient -- either the contract doesn't have enough balance to process the transaction, or the transaction fee would exceed the `VARNAME_MAX_FEE` value -- then reject, and bill the contract account for the fee given by the transaction, or `VARNAME_MAX_FEE` (whichever is lower).

## Examples

Here's an example contract that pays the transaction fee for any transaction that calculates a Pythagorean triple.  Suppose this contract's name is `pythag`.

```
(define-map pythags ((a int) (b int) (c int)) ((result bool)))

(define-public (test-pythag-triple (a int) (b int) (c int))
   (let ((a2 (* a a))
          (b2 (* b b))
          (c2 (* c c)))
     (begin
       (if (eq? (+ a2 b2) c2)
           (begin
              (set-entry! pythags (tuple (a a) (b b) (c c)) (tuple (result 'true)))
              (ok 'true))
           (begin
              (set-entry! pythags (tuple (a a) (b b) (c c)) (tuple (result 'false)))
              (ok 'false))
       )
     )
   )
)

;; Let the contract admin update the max fee
(define-public (update_max_fee (new_max_fee int))
  (let ((contract-admin 'SP2FCC7HBZEB80Q9R9E9N6M91C5XGAB5QQDQ9E1JP))
  (if (eq? (tx-sender) contract-admin)
     (if (> new_max_fee 0)
        (begin (
           (set-var! max_fee new_max_fee)
           (ok 'true)))
        (err "invalid new_max_fee"))
     (err "bad tx-sender -- not the contract admin")))
)

;; Let the contract admin authorize someone to use this contract's STX to pay their fees
(define-public (add_spender (spender principal))
  (let ((contract-admin 'SP2FCC7HBZEB80Q9R9E9N6M91C5XGAB5QQDQ9E1JP))
  (if (eq? (tx-sender) contract-admin)
     (fee-add-whitelist! spender)
     (err "bad tx-sender -- not the contract admin")))
)

;; Let the contract admin deauthorize someone from spending this contract's STX to pay their fees
(define-public (rm_spender (spender principal))
  (let ((contract-admin 'SP2FCC7HBZEB80Q9R9E9N6M91C5XGAB5QQDQ9E1JP))
  (if (eq? (tx-sender) contract-admin)
     (fee-rm-whitelist! spender)
     (err "bad tx-sender -- not the contract admin")))
)

;; Pay at most 0.1 STX for anyone who calls test-pythag-triple
(define-data-var max_fee int 10000)
(define-fees test-pythag-triple max_fee)

;; Set up initial whitelisted addresses
(begin
  (fee-add-whitelist! 'SP2FCC7HBZEB80Q9R9E9N6M91C5XGAB5QQDQ9E1JP)
  (fee-add-whitelist! 'SP1WY3VTA7A38R3E2AHK20X8N6XBVN0YCN54FKVTD))
```

In this example, the smart contract's account can pay up to 0.1 STX for any transaction that calls `test-pythag-triple`.  If this is sufficient, then it would be possible for anyone to send transactions with code such as the following examples, assuming that `tx-sender` was either `'SP2FCC7HBZEB80Q9R9E9N6M91C5XGAB5QQDQ9E1JP` or `'SP1WY3VTA7A38R3E2AHK20X8N6XBVN0YCN54FKVTD`:

* `(contract-call! pythag test-pythag-triple 3 4 5)`
* `(contract-call! pythag test-pythag-triple 9 11 13)`

However, the following would be _invalid_ and would _not_ be accepted:

* `(contract-call! pythag test-pythag-triple (+ 1 2) 4 5)`
   * Rejected because an argument is not a literal value.
* `(contract-call! pythag test-pythag-triple 3 4 5) ;; this is a comment`
   * Rejected because the transaction body contains a comment.
* `(let ((a 3) (b 4) (c 5)) (contract-call! pythag test-pythag-triple a b c))`
   * Rejected because the transaction body is not a `contract-call!`.
* `(contract-call! update_max_fee 123456)`
   * Rejected because this contract does not pay fees for `update_max_fee`.

In addition, the following code examples would _fail type-check_ because they don't use `define-fees` correctly:

* `(define-data-var fee_rate buf "hello") (define-fees test-pythag-triple fee_rate)`
   * Fails because `fee_rate` is not an integer.
* `(define-fees test-pythag-triple nonexistant_var)`
   * Fails because `nonexistant_var` is not a data variable in this contract.
* `(define-data-var fee_rate int 10000) (define-fees nonexistant_function fee_rate)`
   * Fails because `nonexistant_function` is not a public function in this contract.

## Contract Administration

The example above adds three administrative functions -- `update_max_fee`, `add_spender`, and `rm_spender`.  In all cases, these functions only succeed if called by a particular address.  

The thinking here is that a contract that pays for transactions that call some of its functions should remain under the control of one or more principals entrusted with deciding who spends these funds.  The reason is that we want to make sure that miners can't simply steal a contract's funds -- if the miner managers to get its address whitelisted, then it can later be un-whitelisted.

This is nevertheless a "decentralized" design, for two reasons.  First, the administrative code that adds or removes spenders doesn't need to be limited to a single principal like in this example -- it can be invoked by a set of principals, it can be invoked by an oracle, it can be invoked by another smart contract, and so on.  Second, if a group of users don't like the way a contract's fees are managed, they can create their own "proxy contract" that defines its own max-fee and spender whitelist, and simply contains wrappers around the original contract's public functions.  By allowing this, I would expect that any sort of community conflict involving who gets to spend the transaction fees would be easy to mitigate in the contract's original design, and imminently solvable should the original design prove insufficient.

**Comment by lgalabru** [comment]
This feature would be pretty huge, I need to process it.
I have at least one clear concern at this point.

> This would be useful for on-boarding new users who don't yet understand or own on-chain assets, and for helping infrequent or anonymous users leverage smart contracts without requiring them to first go out and buy assets

👍

> This feature can only work with whitelisted addresses. That is, the contract administrator must explicitly state which account addresses can use this contract's funds to pay their transaction fees.

This might be conflicting with the 1st statement. How does that work in real life?
As a new user, I would have to, somehow, signal to an administrator that I need to be whitelisted so that I can transact, and I need to, somehow, get a green light when this whitelisting step has been performed. 
1) Where is the signaling happening? On chain? Off chain?
2) How can I prove that I'm not a minor, or an account working for a minor?

**Comment by kantai** [comment]
First:

```
...
The transaction's Clarity code body must consist of a single contract-call! statement whose arguments are immediate values, and nothing else. No persistent variable reads or data map reads would be permitted, nor would any other calls to native functions be permitted (i.e. no get-block-info, no get-balance, etc.). Moreover, the transaction code body would be capped in length -- i.e. 256 characters or the like.
....
```

This is already the planned design of _all_ transactions -- the only time actual code is submitted in a blockchain transaction is during contract publishing. Other kinds of execution are only allowed via direct invocation of a public contract function. This ensures that static analysis only ever needs to be invoked on contract publish, because static analysis of contract functions will be cached.

Second:

What are the advantages of this over, say, something like SIGHASH_ANYONE_CAN_PAY in Bitcoin (and including some similar functionality to our wire format)? It seems like the chief advantage is that this can be processed/charged automatically versus requiring an active signer in a SIGHASH_ANYONE_CAN_PAY (though the requirement of a whitelist undermines that somewhat). Otherwise, using SIGHASH_ANYONE_CAN_PAY for this is (1) more general, since any function at any time may be funded that way and (2) more secure, since the signer is deciding in real time when to subsidize.

**Comment by jcnelson** [comment]
> This is already the planned design of all transactions -- the only time actual code is submitted in a blockchain transaction is during contract publishing. Other kinds of execution are only allowed via direct invocation of a public contract function. This ensures that static analysis only ever needs to be invoked on contract publish, because static analysis of contract functions will be cached.

I did not know this.  However, is it a good idea to always be this strict?  This restriction means doing anything atomically (e.g. calling two contract functions in the same transaction) necessarily requires deploying a bespoke contract with a public function that does your atomic operation, _and then_ sending a transaction that calls that bespoke contract's public function.  This would make atomic swaps more complicated and more expensive, for example.

> What are the advantages of this over, say, something like SIGHASH_ANYONE_CAN_PAY in Bitcoin (and including some similar functionality to our wire format)? It seems like the chief advantage is that this can be processed/charged automatically versus requiring an active signer in a SIGHASH_ANYONE_CAN_PAY (though the requirement of a whitelist undermines that somewhat). Otherwise, using SIGHASH_ANYONE_CAN_PAY for this is (1) more general, since any function at any time may be funded that way and (2) more secure, since the signer is deciding in real time when to subsidize.

There's also a time/space trade-off here.  The `SIGHASH_ANYONECANPAY` approach trades space for time -- each such transaction would need a signature from both the originating account and from the paying account, causing the space required to implement someone-else-pays-for-my-transaction to grow with the number of such transactions.  The approach in this proposal trades time for space -- each transaction only needs one signature from the originating account regardless of who's paying, causing the space required to implement someone-else-pays-for-my-transaction to grow with the number of changes to the whitelist.  If I had to make a choice, I'd trade time for space in general.

Another advantage of this approach over `SIGHASH_ANYONECANPAY` is that it requires little/no coordination between the payer and the recipient.  Implementing a scheme whereby a developer or user community can pay for other users' transactions using `SIGHASH_ANYONECANPAY` requires:

* Setting up a server for validating transactions, paying for them, and broadcasting them.
* Keeping this server online and defending it from attackers who would steal the private keys (and funds)
* Making the server discoverable to the target users
* Having a "degradation plan" if the server operator decides to shut it down for some reason (i.e. the sponsor is out of funds, the sponsor gets bored, etc.).

None of these problems arise in this proposal.  Anyone can put up the funds to pay for other peoples' transactions by sending them to the contract's account, and the sponsor contracts are all enumerable and discoverable by querying a Stacks blockchain node.

**Comment by jcnelson** [comment]
To be clear, I'm not opposed to `SIGHASH_ANYONECANPAY`.  In fact, the more I think about it, the more firmly I believe that if we do want to have an off-chain mechanism that gives one user the ability to pay for another user's transaction, then that mechanism needs _first-class support_ in the transaction wire format.

The strawman alternative to avoid implementing native `SIGHASH_ANYONECANPAY` functionality would be to instead implement a handful of EC cryptographic operations in Clarity to allow a smart contract to validate a signature from another user, thereby giving _contracts_ the ability to emulate `SIGHASH_ANYONECANPAY` (or more generally, a way for a contract to validate a request from a principal besides `tx-sender` or `tx-origin`).  While I'm not opposed to adding EC cryptographic operations to clarity, I _am_ opposed to emulating `SIGHASH_ANYONECANPAY` in Clarity.  I believe that any payment scheme for spending someone's money on transaction fees _must_ be implemented with first-class transaction authentication scheme, since (1) it will force a "standard" way of doing it which all wallets can support, and (2) it shields users from bugs from N different Clarity implementations.

**Comment by jcnelson** [comment]
After other discussions, we came to the conclusion that this is not necessary.  The the contract-pays-fee paradigm can be implemented with existing Clarity primitives along with a `SIGHASH_ANYONECANPAY` transaction signing mode.

To do so, the developer (or community) runs a transaction-sponsoring server that will pay for a chosen set of transactions relayed to it.  The server is paired with an on-chain smart contract that lets anyone donate STX to it to pay fees, but such that the server can only receive STX for fees at a fixed rate.  Moreover, the contract would be written so anyone could later withdraw their donation of the sponsor server operator is found to be absconding with the funds.
