### ISSUE TITLE
OptionalType check

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-core#1081]
Currently, I need to explicitly convert an optional type to its original type even though the variable can’t be optional in that branch.

```
(if (not (is-none? price))
      (contract-call! token transfer receiver (expects! price invalid-price-err))
      invalid-price-err
)
```

Is it possible to deduce that in this case price is a real type, not an optional one? So that I can remove the `expects!` method.

**Comment by kantai** [comment]
This kind of analysis would be possible, but would lead to strange typing within the program structure -- namely, the value of "price" would have to silently unwrap to the value of the option. Languages with option/result types typically wouldn't do this for that reason.

A better set of native functions for interacting with optionals and results might be helpful, for example, something like a `match` statement from ML-like languages or Rust, but specific to options/results, e.g.:

```
(match-or-else price unwrapped-price
   (contract-call! token transfer receiver unwrapped-price)
   invalid-price-err)
```

**Comment by kantai** [comment]
Automatic destructuring is something we may explore later on, but for now, we're going to focus on getting the right set of interfaces in place for manual destructures via #1138. Closing this for now, but we can revisit this down the road.
