### ISSUE TITLE
Clarity List Types High-Dimension Behavior

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#1101]
Currently, Clarity list types have the following constraints:

1. A list's type conveys the maximum length of the list. This is based on:
    * The actual length in the case of lists constructed in place using `(list ...)`
    * The declared max length in the case of database results or function arguments
2. Every entry in the list must be of the same type
3. High-dimension lists are "square" in that the max length of the top-level list is also the max-length for any child lists.

The third constraint is unnecessary -- it was originally put in place to prevent type signatures from being recursive. This isn't really too much of a concern (and tuples are recursive in any case).

Removing that constraint would make the list type a little less surprising, and so I'm inclined to think that we should do that, unless anyone has any objections.

**Comment by jcnelson** [comment]
I'm inclined to agree that addressing point (3) will be useful and would remove surprise.  Do you foresee any other complications with making list types recursive -- in particular, related to assessing the transaction fee cost?

**Comment by jcnelson** [comment]
> Variably sized type signatures do affect the cost of analyzing a contract, however, since they make the type enforcement checks more expensive. In general, the cost of contract analysis is something like O((contract-length)^2) for reasons like this (that is, operations can get linearly more expensive to check as the contract grows in length).

Is the cost of type-checking a `contract-call!`-type transaction affected by this?  Or would this only affect the cost of publishing a smart contract?  Also, how "fast" can an attacker make the analysis cost grow?  Can we impose a maximum analysis budget?
