### ISSUE TITLE
Clarity: Implement time-shift evaluation (at-block)

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#1104]
Based on a @lgalabru suggestion, we should add support for historical evaluation in Clarity. This enables, among other items, easier implementation of contract forks, voting and staking protocols, which require that votes have been acquired or placed prior to specific blocks.

This syntax would look like:

```scheme
(at-block (block-height int) expr)
```

```scheme
(at-block 170
    (ft-get-balance votes tx-sender))
```

Where `expr` is:

* Checked by the analysis passes to be read-only
* Enforced during VM execution to be read-only
* Code in the `expr` block evaluates with the MARF at the given block-height (that is, the block at height block-height in the currently evaluating fork).

**Comment by lgalabru** [comment]
@kantai I really love the term `time-shift` that you coined. 
It really looks like a cool and unique feature, what's our take on renaming `(block-at ...)` to `(time-shift ...)`?
