### ISSUE TITLE
Clarity: Implement an intrinsic to directly query the MARF

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#1106]
I predict that any _in situ_ upgrades (i.e. "soft forks") to the blockchain network will be achieved in part by requiring miners to commit to new state in each block's MARF.  For example:

* A soft fork that requires miners to commit to the quantity of transactions that have hit each public function since the beginning of time (something that we do not currently do) would be achieved in part by having miners track this information, commit to this information in each block they mine, and only mine on top of blocks that have also done so.

* A soft fork that requires miners to list the set of IP addresses for their high-uptime peers would be implemented in part by having each miner commit to their set via their blocks' MARFs.

This information is potentially valuable to smart contracts, but we currently don't offer a way to directly query state out of the MARF.  I would recommend that we add an intrinsic to do so, so that we can expose new information to Clarity contracts going forward.

**Comment by diwakergupta** [comment]
No concrete use-case yet, and might raise potential issues w.r.t typing. Closing for now.
