### ISSUE TITLE
Clarity: add buffer operations

### ISSUE THREAD

**Issue by lgalabru** [blockstack/blockstack-core#1116]
In order to implement BNS, we need to be able to iterate over a string/buffer (bounded, but size unknown) and test each character so that we can compute a price for a given name / namespace. 
To achieve that, we need to augment clarity's feature set.
With the wrong design, this new capability could be leveraged for introducing a dynamic loop.
How are we approaching this?

**Comment by kantai** [comment]
I think the first step is to allow buffers to be inputs to the high-order list functions --

* map
* filter
* fold

That gives you the ability to loop over buffers.

Second, we can have `concat` and `append` functions:

* `concat` - takes two lists or two buffers, outputs a list or buffer of the same type, with max_len = max_len_a + max_len_b
* `append` - takes a list or buffer and a matching item or max-len 1 buffer and outputs a list or buffer of the same type with max_len += 1.

I think a final useful function would be to provide an error'ing list/buffer cast function --

`(assert-max-length number-literal buffer-or-list-value)`

This function takes a buffer or list argument, which must be typed as a list or buffer of length N and outputs that same list or buffer, but typed with max length `number-literal`. At runtime, a check is performed, which if it fails, causes a runtime error.

**Comment by lgalabru** [comment]
Handled with #1139
