### ISSUE TITLE
Ability to slice buffers / lists

### ISSUE THREAD

**Issue by lgalabru** [blockstack/blockstack-core#1123]
Feature request extracted from https://github.com/blockstack/blockstack-core/pull/1117

https://github.com/blockstack/blockstack-core/blob/d674066f395c99faaaa6b0b8bfc6abcc32b75f05/core-contracts/contracts/bns.clar#L304-L309

Context: In the current draft, when dealing with a `name`, we are passing the name and namespace separately, instead of passing a fully qualified name.
Instead, we want to pass the FQN, locate the `.` and `split` the name and namespace on chain. 
To achieve that the current direction would be implementing the ability to slice a buffer.

**Comment by lgalabru** [comment]
See https://github.com/blockstack/blockstack-core/issues/1116#issuecomment-533150463

**Comment by lgalabru** [comment]
Now that `concat` and `asserts-max-len` are natively supported, this feature is implementable in Clarity, and actually implemented in a test:
https://github.com/blockstack/blockstack-core/blob/dcda531bc75dd4bfadf4ebea9d4eeef6dac1b5f8/src/vm/analysis/type_checker/tests/mod.rs#L333-L338
As discussed with Aaron, this will be part of a stdlib.

**Comment by njordhov** [comment]
Formatted for future reference:
```clojure
(define-private (slice (x (buff 1)) 
                       (acc (tuple (limit uint) 
                                   (cursor uint) 
                                   (data (buff 10))))) 
  (if (< (get cursor acc) (get limit acc)) 
    (let ((data (default-to (get data acc) 
      			    (asserts-max-len (concat (get data acc) x) u10)))) 
      (tuple (limit (get limit acc)) 
             (cursor (+ u1 (get cursor acc))) 
             (data data)))  
     acc))
         
(fold slice "0123456789" (tuple (limit u5) (cursor u0) (data "")))
```
