### ISSUE TITLE
Ability to get the size of a buffer / list

### ISSUE THREAD

**Issue by lgalabru** [blockstack/blockstack-core#1125]
Feature request extracted from https://github.com/blockstack/blockstack-core/pull/1117

```
(define-private (increment-len (byte (buff 1)) 
                               (acc uint))
  (if (not (is-none? byte))
    (+ acc 1)
    (acc)))


(define-private (compute-namespace-price (namespace (buff 20)))
  (let ((namespace-len (fold increment-len namespace 0)))
```

In BNS, we are dealing with bounded buffers / lists.
Do we want to have the a native function for getting the "used" length? 

Related: should we modify the function signature passed to the `map`/`reduce` functions, and move from:
`Function(A, B) -> B, (list A)`
To:
`Function((optional A), B) -> B, (list A)`
?

**Comment by kantai** [comment]
> In BNS, we are dealing with bounded buffers / lists.
> Do we want to have the a native function for getting the "used" length?

Sure, we should add a length function.

> Related: should we modify the function signature passed to the map/reduce functions, and move from:
Function(A, B) -> B, (list A)
To:
Function((optional A), B) -> B, (list A)
?

I'm not sure I understand this. The reduce function's signature currently is something like:

```
Function(A, B) -> B
```

where `B` is the output type of the reduce/fold, and `A` is the list element type.

Do you mean changing that to:

```
Function(A, (optional B)) -> B
```

and change the initial value to always be `none` ?

**Comment by lgalabru** [comment]
> Related: should we modify the function signature ...

Apologies @kantai. That was just me ignoring & guessing how the buffers were implemented.

**Comment by lgalabru** [comment]
Handled with https://github.com/blockstack/blockstack-core/pull/1139
