### ISSUE TITLE
Proposal: improve consistency with usage of ! and ?

### ISSUE THREAD

**Issue by lgalabru** [blockstack/blockstack-core#1126]
Feature request extracted from https://github.com/blockstack/blockstack-core/pull/1117
To be debated - challenged.

At this point, operations suffixed with `!` are falling under 3 different buckets:
- signals writing: `map-insert!`, `var-set!`, `ft-mint!`, `ft-transfer!`, etc.
- signals throwing: `expects!`, `expects-err!`
- not sure: `contract-call!`

We are consistent with our usage of `?`:
- returns a boolean: `is-none?`, `eq?`, `is-ok?`
That being said, there's some redundancy with the prefix `is-` and the suffix `?`.

On the other hand, when writing code, it's pretty hard to "guess" if results from functions should be unwrapped / checked.
I'd like to get your take on the following conventions:
- `!` signals a throwing function, short-circuiting the execution.
- `?` signals a function returning a `result` or an `optional`, and signal / remind that the result should be unwrap - imagine a `ft-transfer?` operation not being checked.
- `is-` signals a function returning a boolean.

**Comment by moxiegirl** [comment]
@lgalabru are you proposing `is-` functions could simply have not punctuation --- consistently -- is some punctuation required on every function?

**Comment by lgalabru** [comment]
@moxiegirl in this suggestion, a function returning a boolean is simply prefixed with `is-`, and we stop using the `?` symbol (used instead for signaling that a function is returning an optional or a response, that should be unwrapped / checked).

**Comment by moxiegirl** [comment]
@lgalabru great!
