### ISSUE TITLE
Fill in miner-address block-info stub

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#1131]
Update `get-block-info` so it can return the miner address.  Useful for paying fees and rewards to miners.

**Comment by kantai** [comment]
Taking this issue on, since it's going to be pretty easy to implement alongside #1207.

**Comment by kantai** [comment]
Taking this issue on, since it's going to be pretty easy to implement alongside #1207.

**Comment by kantai** [comment]
#1233 added a panicking stub for getting this information out of the block header db -- @jcnelson, do you want to take over this issue for filling in that stub?

**Comment by jcnelson** [comment]
Yes, I can take this.
