### ISSUE TITLE
Destructuring Optionals/Results in Clarity

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#1138]
Currently, we have a couple functions for destructuring optionals and results:

```
default-to
expects!
expects-err!
is-ok?
is-none?
```

While these provide the ability for a variety of handling behaviors, they don't make things easy, and languages with strongly typed options and results generally have support for at least three diffferent kinds of destructuring:

1. Runtime error destructures (i.e., `unwrap()` or `expect()` in Rust)
2. Short-return destructures (i.e., `?` in Rust)
3. Matching destructure

I'd propose we implement the above with the following functions:

### Runtime error destructures:
```
(unwrap (optional A)) -> A ;; throw runtime error if none
(unwrap (response A B)) -> A ;; throw runtime error if supplied err
(unwrap-err (response A B)) -> B ;; throw runtime error if supplied ok
```

### Short-return destructures:
```
(unwrap-or-ret (optional A) C) -> A ;; return C if supplied none
(unwrap-or-ret (response A B) C) -> A ;; return C if supplied err
(unwrap-err-or-ret (response A B) C) -> B ;; return C if supplied ok
```

### Matching destructures:
```
(match-opt (optional A) bind-name expr0 expr1)
(match-resp (resp A B) bind-name expr0 bind-name-1 expr1)
```

These behave like if/lets:

```
(match-opt val foo (+ foo 1) 0)
```

is equivalent to:

```
(if (is-none? val)
    (let ((foo (unwrap val)))
          (+ foo 1))
    0)
```

**Comment by kantai** [comment]
Related issue #1080

**Comment by lgalabru** [comment]
Can we keep `is-none`, `is-ok` and add `is-err` and `is-some`?
Ending up with double negations `(not (is-none ...))` is not super compliant in terms of clarity :)
