### ISSUE TITLE
Block mining simulation should be integrated into MARF

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#1147]
The current way that we simulate block mining in Clarity is that we store some simulated information in the ClarityDatabase, using it to respond to `block-info` calls. However, that's not a very good simulation, since it _does not_ integrate with the MARF itself -- things like time-shifted evaluation won't work with that information. Rather, simulated block mining should create a new MARF block with the relevant simulated information.

**Comment by moxiegirl** [comment]
Do we want to explain the simulation block info a bit more? I am assuming we need like a block information explainer. What do you think?

**Comment by kantai** [comment]
> Do we want to explain the simulation block info a bit more? I am assuming we need like a block information explainer. What do you think?

Yeah -- I think that's a good idea -- we can add it to the Clarity function, variable, specification JSON output.

**Comment by kantai** [comment]
Closing in favor of #1207
