### ISSUE TITLE
Articulate exactly what the "initial testnet" constitutes

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/blockstack-core#1177]
We need to align on what the deliverable for SP2 is, what a testnet constitutes initially and perhaps eventually.

**Comment by jcnelson** [comment]
I talked it over with @kantai and @lgalabru, and the general consensus is that an "initial testnet" is a Blockstack Core node that can boot up a minimal JSON-RPC server that will allow users to submit signed transactions for mining into a block, and for querying the chain tip state.  The server will periodically package any pending transactions into block.  In addition, the "initial testnet" will include a minimal CLI for generating, signing, and sending transactions to the server.
