### ISSUE TITLE
JSON in consensus-critical databases?

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#1208]
Most implementations of `ClaritySerializable` and `ClarityDeserializable` convert their structs into JSON and back.  This includes the various `Metadata` classes for contracts, tokens, data variables, data maps, etc., whose state is committed to by the state root MARF.  Given that JSON does not have a stable serialization, should we switch over to using the code from `ClarityValueSerializable` for all these things?

**Comment by kantai** [comment]
No -- per #1206, none of these items should be committed to in the MARF at all, and therefore their serialization is not consensus-critical.

**Comment by kantai** [comment]
Closed by merging #1214
