### ISSUE TITLE
Asynchrony bug in `net::p2p::poll`

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#1236]
While trying to figure out why the `net::p2p::test::dispatch_requests_relay` test failed intermittently, I discovered an asynchrony issue in `net::p2p`:

[`mio_net::TcpStream::connect`](https://docs.rs/mio/0.7.0-alpha.1/mio/net/struct.TcpStream.html#method.connect), used in `NetworkState::connect`, issues a _non-blocking_ connect. However, subsequent code tries to immediately get data from the socket -- eventually leading to a SocketError at `p2p.rs:613`.

The test went from consistently failing on my local machine to consistently passing when I added a thread::sleep for a half second to the connect function, but that's not a real fix for the issue, but does suggest that the problem is caused by the asynchronous IO.

**Comment by jcnelson** [comment]
Thanks for reporting!  I had noticed this before, but could never reproduce it.  It'll be fixed in my HTTP PR.  I'm just making it so `NetworkState::connect` issues a blocking `connect_timeout` on a `net::TcpStream`, and then feeding that into a `mio::net::TcpStream`.

**Comment by kantai** [comment]
Cool -- I'll apply the same fix to my PR branch for now to get it to build. Feel free to just wipe out any conflicts there on merge.
