### ISSUE TITLE
Non-sensical transaction field combinations?

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#1263]
Do we want to support any of the following?  While doing so is non-sensical, it's not technically forbidden:

* Coinbase transactions with post-conditions
* Coinbase transactions that have a sponsored authorization
* PoisonMicroblock transactions with post-conditions

I'm generally in favor of giving miners a lot of leeway with what they put into their coinbases (since they're used mainly for inter-miner in-band signaling), but I think post-conditions should be forbidden on PoisonMicroblock transactions.

**Comment by diwakergupta** [comment]
No.
No.
No.

Create new issue to add back sponsored transactions for STX transfers.
