### ISSUE TITLE
Bash: clarity: command not found..

### ISSUE THREAD

**Issue by trappierhall** [blockstack/blockstack-core#1273]
Hi,

When I try to install your client SDK for smart contract development I
get the following which looks to me to be as expected , but when I go to
run the command Clarity --help-see far below. I get bash cannot find.
What am I doing wrong? Please help.

1. sudo npm install @blockstack/clarity-cli
(btw- I did try the install -g @blockstack/..... but got all kind of permission error messages)
2. + @blockstack/clarity-cli@0.1.13-alpha.3
added 161 packages from 97 contributors and audited 46143 packages in
10.655s

3. 8 packages are looking for funding
  run `npm fund` for details

4. found 0 vulnerabilities
___________________________________________________________________________________________________

Error message

$ clarity --help
-bash: clarity: command not found

**Comment by jcnelson** [comment]
Hi @trappierhall, I think you might be looking for this repo? https://github.com/blockstack/clarity-js-sdk

To build this package's Clarity tools, you'll need Rust and Cargo.  Please see the README.md for details.

**Comment by trappierhall** [comment]
HI,

Thanks for the assist but I have tried the suggested path in the README file, npm rebuild, ensure rust and cargo are up to date, sudo npm install with -g @blockstack.. or without the -g, and other info sources but to no avail. I still get the Clarity command not found...What am I missing..Please help!!

Trappier:clarity-js-sdk trappierhall_LAO$ ls
CONTRIBUTING.md		lerna.json		packages
LICENSE			node_modules		tools
README.md		package-lock.json	tsconfig.build.json
appveyor.yml		package.json		tsconfig.json
Trappier:clarity-js-sdk trappierhall_LAO$ npm install @blockstack/clarity-cli
npm WARN @blockstack/clarity@0.1.13-alpha.2 requires a peer of @blockstack/clarity-native-bin@^0.1.10-alpha.0 but none is installed. You must install peer dependencies yourself.

+ @blockstack/clarity-cli@0.1.13-alpha.3
updated 1 package and audited 46143 packages in 9.274s
found 0 vulnerabilities

Trappier:clarity-js-sdk trappierhall_LAO$ clarity --help
-bash: clarity: command not found
Trappier:clarity-js-sdk trappierhall_LAO$

**Comment by trappierhall** [comment]
Hi,
Thanks for the assist but I have tried the suggested path in the README file, npm rebuild, ensure rust and cargo are up to date, sudo npm install with -g @blockstack.. or without the -g, and other info sources but to no avail. I still get the Clarity command not found...What am I missing..Please help!!
clarity-js-sdk _LAO$ ls CONTRIBUTING.md lerna.json packages LICENSE node_modules tools README.md package-lock.json tsconfig.build.json appveyor.yml package.json tsconfig.json clarity-js-sdk _LAO$ npm install @blockstack/clarity-cli npm WARN @blockstack/clarity@0.1.13-alpha.2 requires a peer of @blockstack/clarity-native-bin@^0.1.10-alpha.0 but none is installed. You must install peer dependencies yourself.
	•	@blockstack/clarity-cli@0.1.13-alpha.3 updated 1 package and audited 46143 packages in 9.274s found 0 vulnerabilities
clarity-js-sdk _LAO$ clarity --help -bash: clarity: command not found clarity-js-sdk _LAO$

**Comment by jcnelson** [comment]
Closing due to the lack of activity.
