### ISSUE TITLE
Guard large allocation in Value::deserialize, apply recursive limits on types

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#1276]
Malformed byte strings in Clarity deserialization can cause OOM.

**Comment by jcnelson** [comment]
In particular, it would be best if we could somehow bound the amount of RAM used in the act of parsing the thing (i.e. bounding the length of a `vec` of huge values to "only" 1 million can still lead to an OOM).

**Comment by kantai** [comment]
Yep -- so there's one level of OOM issues in deserialization from allocating a vec object -- that is resolved by just placing a size limit on the vec (since the Value objects themselves are size bound).

However, what I think the deserialization function really needs to do is two things:

1. Track a running "size budget" as it deserializes an object, so that any object where the type would fail due to a size limit raises an error before it allocates more than the maximum object size.

2. Apply a limit on recursive calls, and apply a limit on _recursive_ type depths. In rust, this limit is 128, but I think we can reasonably apply a much lower limit, e.g., 32.

Th PR #1277 doesn't address either of the above, it just does a simple check for now, but it also fixes a separate bug. So I think this issue will outlive that PR.

**Comment by kantai** [comment]
An alternative to #1 above, I think, is to bound the number of bytes read in. Recursive calls still must be dealt with, however.
