### ISSUE TITLE
Support Internationalized Domain Names

### ISSUE THREAD

**Issue by john-light** [blockstack/blockstack-core#159]
i.e. https://en.wikipedia.org/wiki/Internationalized_domain_name

**Comment by jcnelson** [comment]
Just to clarify, you mean we should support Unicode characters in names?  If so, I think the best way to go about this is to have our tools decode and print out the name correctly, but allow names to be represented internally as a punycode-encoded ASCII strings (including on the blockchain itself).  This means names with Unicode characters will show up strangely in block explorers and services like coinsecrets, but I think that's acceptable for now.  @shea256 @muneeb-ali

**Comment by larrysalibra** [comment]
Previous thread on this topic: https://github.com/blockstack/blockchain-id/issues/43

**Comment by shea256** [comment]
Yes, just as I said in that thread I would push this off for now, and then when we're ready to add support for it, I would use the same IDNA encoding that ICANN DNS uses.

**Comment by john-light** [comment]
OK, is it alright if I keep the issue open here? It seems to be the more accurate place to keep track of this.

**Comment by jcnelson** [comment]
Closing this as stale.  This issue belongs in blockstack.js or some other tooling library that can automatically translate between puny-encoded names and unicode.
