### ISSUE TITLE
Add the ability to pack a high number of operations into a single transaction

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-core#182]
We've had multiple discussions about how we can extend the virtual chain outside of the underlying blockchain, thus allowing the number of operations to scale super-linearly with the number of transactions.

Currently, each Blockstore transaction has it's operation instructions contained within the `OP_RETURN` field, and the authorization for the operation is derived from the signatures in the transaction.

If instead we separate the operational logic from bitcoin transactions, then pack them in a Merkle tree, and then put the Merkle root in a transaction, we can have a much more scalable system.

Here, each operation would come with it's own operation instructions, as well as specify a set of signatures and the public keys that correspond to them.

This of course would require that Blockstore nodes be able to recognize a Merkle root and know how to get the full tree. There are clear challenges here because Blockstore would need 100% data availability across all Merkle trees it discovers. Otherwise it will not be able to proceed in scanning through the Blockchain.

We've discussed the challenges of being able to reach this high level of data availability, and we haven't yet come up with an answer that satisfies us completely. We've considered various peer-to-peer systems for transferring data. We've also considered a secondary "heavy" blockchain that's only designed for guaranteeing 100% data transfer. We'll have to continue to think about this and figure out a way to ensure 100% data availability before we can proceed with this operation-packing system.

One interesting thing we can do, though, is require that each "operation tree" be specific to a particular namespace, and require that the inclusion of an operation tree specify both a Merkle root and the TLD it corresponds to. In this case, if we are able to somehow achieve eventual 100% data availability, but there are occasional hiccups on certain Merkle trees, Blockstore nodes would be able to proceed and process other namespaces without having to wait on a given unfound tree for another namespace. That is, blocking of operation processing would no longer be on a name universe-wide basis, and instead on a per namespace basis.

**Comment by muneeb-ali** [comment]
Posting comments from @jcnelson 

```regarding the high-s problem you've been encountering, try pulling the latest `bitcoin` package from PyPI.   Version 1.1.39 should work (Blockstore currently pulls in 1.1.36).   We're about to make that the new requirement, since it incorporates the BIP62 fix that forces the canonical S-value in ECDSA signatures (which Blockcypher now expects).```

**Comment by shea256** [comment]
@muneeb-ali did you mean to post this on a different issue?

**Comment by muneeb-ali** [comment]
Yes :-)

**Comment by shea256** [comment]
OK I'll delete our comments here.

**Comment by jcnelson** [comment]
I think the conclusion we got here was that we should just focus on ownership of subdomains as a scaling solution.
