### ISSUE TITLE
Use Smart Signatures as a Programable Authorization Mechanism in Operation Packing

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-core#183]
Smart Signatures, or Smart Public Keys, are essentially an implementation of Bitcoin's "script public key" mechanism, but outside of the blockchain.

One big update to Blockstore on our roadmap is operation packing (see #182).

In such a system, transaction-level signatures would no longer be used as the base authorization mechanism. Instead, the operations packed in the Merkle trees would be provided with their own signatures, and those would be used for authorization.

I suggest that instead of using implicitly-defined authorization rules, we use an explicitly-defined authorization scheme like the one we see in Bitcoin.

See the Smart Signatures paper for more information on how such a system would work outside of Bitcoin: https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust/blob/master/draft-documents/smart-signatures.md.

> In this paper, we describe a cryptographic signature system that can be used to greatly extend the capabilities of traditional ones. Traditional systems are based on strictly-defined authentication and authorization mechanisms that assume a single private key may be used to produce a given signature and that a single public key may be used to verify it.
> 
> Given the evident limitations of this design, we propose an alternative that is more powerful in its capabilities due to the fact that the conditions for verification are explicitly outlined and fully-programmable. This programmable authorization system allows for broad capabilities in specifying the conditions under which a signature or set of signatures can be considered valid.
> 
> Our inspiration for this authorization system is the Bitcoin scripting language, where the authorization to spend funds is explicitly defined within a script, rather than being implicitly defined through the reference to an authorized public key. The largest benefit of explicit specification of authorization conditions is that the system is fully extensible, so new operations can be defined at any time and the only limitation on the authorization system is the set of operations that the authorization interpreters understand.

If we implemented this, we would be able to support multiple-party authorization (like multi-signature transactions in Bitcoin) and be able to satisfy a wide variety of authorization conditions.

**Comment by jackzampolin** [comment]
From what I'm reading here it seems like the system has changed significantly since this discussion. I'm going to close this. Reopen of I'm wrong!
