### ISSUE TITLE
Create documentation for running in test mode

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#193]
Need a simpler explanation plus tutorial for running blockstore on a) bitcoin testnet and b) test blockstore namespace. Here is the  4x4 matrix from @shea256 

> there's a main net and a test net configuration. On both main net and test net, there's a test universe of Blockstore as well, called "test set"
> 
> So you can imagine a 2x2 matrix where the top is main vs test blockchain and the left is main vs test Blockstore universe. Yielding 4 universes in total.

**Comment by shea256** [comment]
We originally set it up with 4 universes but now I'm regretting that decision. Might make sense to simplify things and just have "blockstore on main net" and "blockstore on test net".

**Comment by muneeb-ali** [comment]
+1 on just two test modes. We can hide the other modes and they can be for advanced users.

**Comment by jcnelson** [comment]
Yeah--I think the answer to this is "run it on testnet" or "run it on regtest".  Refer to the bitcoin documentation for details, but just be sure to point blockstack-server towards the right port number.

**Comment by uranther** [comment]
+1

I am working on developing an application to manage digital identity using Blockstack's APIs. I have never connected (or setup?) the Bitcoind test network nor have I used Blockstack in its production mode.

**Comment by jcnelson** [comment]
Added documentation here: https://github.com/blockstack/blockstack-integration-tests/blob/master/README.md.  Please submit all future issues and PRs for test documentation to that repository.  Thanks!
