### ISSUE TITLE
Support Python 3 + Error Messages

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#206]
It might take some work before we can have Python 3 support, but wanted to make a note that we should at least detect during installation that the user has a version of Python not compatible with blockstore yet and give a proper error message.

**Comment by muneeb-ali** [comment]
I updated this issue's description and limited the scope to checking python versions during install / first run and giving the user a meaningful error if the python version is not supported.

**Comment by jcnelson** [comment]
Python 3 probably isn't going to happen for a while.  There's already a bounty open for it, so I'm closing this off.
