### ISSUE TITLE
start restricting the TLDs available to those that don't conflict with pre-existing ICANN TLDs

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-core#209]
Here's a table of all of the existing ICANN TLDs as listed by IANA: https://www.iana.org/domains/root/db

There are 1275 listed here but I saw another list as a text file with about 1500 somewhere but I can't remember where. I'll try to track it down.

The best way to do this is probably to simply snapshot this list and ban all the TLDs on this list. Then, a few years down the road when a bunch more TLDs have been added, we can always propose a fork and extend the list of banned TLDs (and just accept a small list of conflicts and resolve them with labeling exceptions).

Excited about this one because of the interoperability it enables. That is, we'll be able to work with resolvers that support both Blockstack DNS and traditional ICANN DNS :)

**Comment by jcnelson** [comment]
Will be happy to merge.  Just need to get the full list.

**Comment by shea256** [comment]
Actually I think that might be the full list. I can't seem to find the other one :(

**Comment by jcnelson** [comment]
This is present in the `develop` branch.

**Comment by shea256** [comment]
Amazing! I'm so excited!

**Comment by jackzampolin** [comment]
This has been merged! Closing
