### ISSUE TITLE
Fast bootstrapping for server 

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#210]
We now have fast bootstrapping functionality in the server (great work, @jcnelson!) and should probably expose this to the users. I think having a "--fast" flag when starting the server can be one way to do this.

Here are some next steps:
1. Start supporting the "--fast" flag as a command-line option when starting the server. 
2. Setup a default repository from where the server will fetch a copy of untrusted DB (can be the same server as apt-get package repository).
3. Allow the user to change the default untrusted DB location in settings.
4. Ask the user for a trusted consensus hash and run verifydb.

I'm thinking that step (4) above can be optional. As in, if I'm doing an internal deployment and trust the DB that will be downloaded on a new VM then I don't need to run verifydb.

Side note: Ethereum has a somewhat similar ["--fast" option](http://ethereum.stackexchange.com/questions/1984/what-is-the-difference-between-geth-and-geth-fast) as well.

**Comment by jcnelson** [comment]
Can do.  (4) has already been done for a while.  (1) can take a URL as an argument, but fall back to a hard-coded set.

**Comment by jcnelson** [comment]
Implemented :D
