### ISSUE TITLE
typo in 'Usage' wiki page?

### ISSUE THREAD

**Issue by dooglus** [blockstack/blockstack-core#212]
https://github.com/blockstack/blockstack-server/wiki/Usage says once I have preordered a name I complete registration using the `register` command, but that seems to want to re-preorder the name that I already preordered.

Looking at the source it appears that the command I really want is `register_tx`. Is that right?

**Comment by muneeb-ali** [comment]
That documentation is outdated and we're working on updating it! Thanks for starting the issue.

**Comment by shea256** [comment]
Hey @dooglus here's a link to the official documentation on blockstack registrations: https://blockstack.org/docs/basic-usage.

If you use the command line interface, the process of preordering and then registering names is automatically done for you.

Let us know if you need anything else!

@muneeb-ali we should probably take down that wiki page right? Most of the wiki pages here should be removed.

**Comment by dooglus** [comment]
I used the page I linked to, using 'preorder' and 'register_tx' (when 'register' didn't work).

Have I lost my coins?

My preorder txid: afabbfc9532d0eb56a4200d84e4886646e3bbe771d4016ab9b374ba8e1de8b31
My register txid: e10ff8516a165155f7407cc8f41ab0aa361c7b89955c0bc69f9939efb8e0e3f8

I am attempting to register the name doog.id since someone already registered dooglus.id before I heard about your service.

`blockstack lookup doog.id` is telling me `"error": "doog.id is not registered"` so I guess I did it wrong.

It would be useful if you removed the outdated documentation until it is fixed so nobody else loses their coins.

**Comment by muneeb-ali** [comment]
Your bitcoins are not lost yet. You can send a well-formed register transaction within the next 130 or so blocks and use the preorder. However, the process of doing that would require some work. 

Also, please send me your deposit address (you can DM in our Slack channel -- http://chat.blockstack.org) and I can send you some bitcoins so that you can register the name via the CLI.

Completely agree @shea256 and @dooglus that we should remove the outdated documentation. We're doing that now.

**Comment by muneeb-ali** [comment]
Update: looking at what you did. The old documentation might still work. Let's wait for your register tx to go through, but we should remove the old documentation anyway :-)

**Comment by dooglus** [comment]
I used `register_tx` rather than `register`. Other than that I followed the documentation.

**Comment by muneeb-ali** [comment]
@dooglus I'm closing this issue and assuming your transaction went through. Please reopen or post in http://forum.blockstack.com for support. Thanks!
