### ISSUE TITLE
Zonefile replication

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#219]
Offer an API endpoint that will allow clients to replicate their zonefiles via the Blockstack Server they talk to.  The client can talk to many different Blockstack servers to enhance its durability, and can replicate to its own storage providers directly (the latter already happens with regards to the Blockstack DHT).

In addition, make the Blockstack Servers replicate their zonefiles among one another.  This is in addition to replicating them to the DHT and back-end storage providers.

**Comment by jcnelson** [comment]
A bit of background:

**Peer Discovery:** Some blockstack IDs will point to lists of Blockstack servers.  Their zonefile hashes will contain hex-encoded URLs, which refer to signed JSON web tokens.  The JSON web token will contain a list of peers known to the blockstack ID owner, and will be signed with the private key that put the zonefile hash.  In doing so, any Blockstack server can discover, fetch, and verify the authenticity of an initial list of peers if they know one or more of these initial blockstack IDs.  The one I will be using is `blockstackmirrors.id`.  In addition, Blockstack servers will serve their known list of peers and their seed blockstack IDs to other peers on request, so that a new Blockstack server can build up the global set of known peers.

**Zonefile Replication:**  Zonefiles are small, and there aren't too many of them, but we know their hashes in advance.  Therefore, Blockstack servers should seek to achieve 100% zonefile replication.  I'm going with a two-pronged strategy:  (1) Blockstack clients will *eagerly* replicate their zonefile to a subset of known Blockstack servers after their NAME_UPDATE goes through (this set can be arbitrary), and (2) Blockstack servers will asynchronously replicate zonefiles in the background to one another, but will do so synchronously on client request.

In particular, each Blockstack server learns the same set of new zonefile hashes as everyone else at each block, but only some peers will actually have the zonefile (since the client will have replicated it only to them).  Upon discovering a new hash, the Blockstack servers that don't have the matching zonefile will search through their peer listings and iteratively request the missing zonefiles.  They'll do so in weighted random order, and with random initial delays with exponential back-off to avoid thundering herds.

Weighted random order is an optimization, based on the assumption that a peer that often can serve zonefiles is likely to do so in the future (the intuition behind this is that there will probably be a persistent subset of professionally-maintained Blockstack servers within Blockstack-powered applications that are often the first to receive zonefiles for their clients).  By making servers higher hit ratios more likely to be requested, other peers will more quickly find zonefiles by avoiding querying underprovisioned "flaky" peers.

**Zonefile availability and durability:** A Blockstack server will cache its zonefiles locally, and it will replicate them to its operator's back-end storage providers.  In addition, we'll make our set of zonefiles wholly-downloadable so new peers can quickly bootstrap (the bootstrapping peer would of course verify that each zonefile corresponds to a current zonefile hash in a valid name).

**Comment by muneeb-ali** [comment]
I like using the server for zonefile replications. Two benefits:

a) This works well with our general **direction of consolidating** resolver, search, API etc into a single server. You shouldn't think about running a "mirror", you should only think about running a server. A mirror is useless unless it can talk to a server anyway.

b) This gives us a legitimate reason to have a **peer discovery protocol** i.e., you need to know about other blockstack server because you want to sync your zone files in the background. A big benefit of having a discovery protocol is that we can have a much better picture of how many nodes there are, how is the network evolving, how resilient it is to attacks etc. Also, once we have a discovery protocol it'd be easier to compare consensus hashes with your peers as well.

**Comment by jcnelson** [comment]
This has evolved into the Atlas feature, which will be deployed in 0.14 alongside the DHT.

**Comment by jcnelson** [comment]
Merged to master
