### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by wutengcoding** [blockstack/blockstack-core#221]
Hi dear:
when i do the sudo pip install blockstack command, and run the blockstack-server start, but got an error.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualchain-0.0.6-py2.7.egg/virtualchain/lib/indexer.py", line 860, in get_index_range
    current_block = int(bitcoind.getblockcount())
  File "/usr/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 114, in __call__
    response = self._get_response()
  File "/usr/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 140, in _get_response
    parse_float=decimal.Decimal)
  File "/usr/local/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[ERROR] [blockstored:241] (25549) Reconnect to bitcoind
anyone can help me?
it seems that i specify the wrong server? how to specify a right server, does the server means the remote bitcoin miner? 
In addition, if i want to add some functionality in the register and query process, which module should i reference? Thank you very much.:)

**Comment by muneeb-ali** [comment]
Looks like you cannot connect to bitcoind. What pip command did you use to install the server? Depending on the installation command you used the bitcoind settings will be in either ~/.blockstore/blockstore.ini or in the folder ~/.blockstack-server

**Comment by helloooooo** [comment]
yes, the config file is in ~/.blockstore/blockstore.ini.
when i type in "blockstack-server", it means /usr/bin/blockstack link to a python file, i delete this blockstack shell by mistake, and i can't start it any longer, can you tell me which file the start shell link to?
What's more, when i git clone the blockstack-server reposit, and run the test cases like this ./run_tests.sh ./scenarios/ ./output, i get ./scenarios/.name_import_update_transfer_revoke_verify_multi ...  FAILURE
and the log file is TypeError: relative imports require the 'package' argument
thank you very much.

**Comment by jcnelson** [comment]
The second argument (`./scenarios/`) should be just `scenarios`.
