### ISSUE TITLE
Server doesn't set version in config file after update

### ISSUE THREAD

**Issue by doodlemania2** [blockstack/blockstack-core#229]
After updating server, ini file is reported as old.
Delete old file, allow server to generate a new file.
Server generates new file, then returns that ini file is still old.
Cause: version not written to ini file: server_version = <blank>
Should write version to this field.

**Comment by jcnelson** [comment]
Thanks!  Just pushed a fix to the code; it'll find its way into PyPI, APT, and brew in the next minor release.

**Comment by jcnelson** [comment]
Pushed.
