### ISSUE TITLE
Resolver should try all available data locations

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#230]
(This issue should be addressed after the resolver is merged with the server)

The resolver currently gives up after trying the first location listed in the zone_file. 

CLI v0.0.13 however tries all listed locations. The resolver should be updated to follow that process as well.

**Comment by jcnelson** [comment]
Is this fixed?  Are you using `blockstack_client` (the Python package) to do this?

**Comment by jackzampolin** [comment]
From what I'm reading here it seems like the system has changed significantly since this discussion. I'm going to close this. Reopen of I'm wrong!
