### ISSUE TITLE
Add support to core API for all RPC calls

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#239]
Information available via CLI and RPC calls should available through core HTTP API so that other projects don't need to roll their own solutions. (like this https://github.com/blockstack/blockstack-explorer/blob/5030dba2d10256a13f3577bf0b23ceecc46688e4/tools/runserver.py)

**Comment by muneeb-ali** [comment]
This is outdated now with the the [new Blockstack API](https://github.com/blockstack/blockstack-core/issues/279). Closing.
