### ISSUE TITLE
502 bad gateway error

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#241]
@muneeb-ali commented on [Tue Sep 06 2016](https://github.com/blockstack/blockstack-resolver/issues/111)

 https://resolver.onename.com/v2/users/vsund triggers a 502 bad gateway error too

---

@shea256 commented on [Tue Sep 06 2016](https://github.com/blockstack/blockstack-resolver/issues/111#issuecomment-245079286)

Suggestion:

What do you think of adding a 502 global error handler like one of the ones we have to ensure API errors return JSON?

``` python
#502 Error handler
@app.errorhandler(502)
def page_not_found(error):
    response = jsonify({'error': error.to_dict()})
    response.status_code = error.status_code
    return response
```

**Comment by muneeb-ali** [comment]
The resolver interface is deprecated and only the API interface is active. I believe we already have this in place for the API, but I'm leaving this issue open until we confirm that's the case.

**Comment by shea256** [comment]
Yeah, makes sense.

A 502 handler isn't actually in the API repo. And I just realized the 500 handler we have needs to be updated so that it returns JSON.

**Comment by jackzampolin** [comment]
We are deprecating that service. I'm going to go ahead and close this issue.
