### ISSUE TITLE
[Feature request] Reverse lookup

### ISSUE THREAD

**Issue by JustinDrake** [blockstack/blockstack-core#242]
OpenBazaar nodes have GUIDs associated with their BlockchainID. It would be helpful to have a reverse lookup from GUID to BlockchainID. @muneeb-ali suggested this was possible to implement in search.

**Comment by muneeb-ali** [comment]
Thanks for the suggestion. Yeah this can go in search. We basically need a new search index for the GUID (we already create indexes for a bunch of things and this will be 1 additional index).

**Comment by JustinDrake** [comment]
On the OpenBazaar Slack Muneeb said

> I wrote some code to do a reverse lookup

Look forward to having this.

**Comment by muneeb-ali** [comment]
@JustinDrake looks like @Muqeet implemented this. This hasn't been merged to master yet and should be available in v0.14.2 onwards.

**Comment by jackzampolin** [comment]
Looks like this is in master. Closing as implemented.
