### ISSUE TITLE
[Feature request] Filter BlockchainIDs that have an associated OpenBazaar GUID

### ISSUE THREAD

**Issue by JustinDrake** [blockstack/blockstack-core#243]
At the moment there's the full list of (currently 62,550) BlockchainIDs from this URL:

https://resolver.onename.com/v2/namespaces

It would be very helpful to have the same list but filtered for those that have an associated OpenBazaar GUID.

**Comment by muneeb-ali** [comment]
Thanks for the suggestion. Let me think about how to best implement it.

**Comment by jcnelson** [comment]
Do we have this merged now? https://github.com/blockstack/blockstack-core/pull/368

**Comment by jackzampolin** [comment]
This is in master. Closing as implemented.
