### ISSUE TITLE
Core dump when stopping server after bitcoind dies

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#251]
Prereqs: blockstack core is indexing from local bitcoind instance:

1.) Kill bitcoind
2.) run `blockstack-server stop`

output:

```
(venv) larry@blockstack-explorer-1:~$ blockstack-server stop
Failed to connect to bitcoind
Aborted (core dumped)
(venv) larry@blockstack-explorer-1:~$
```

**Comment by jcnelson** [comment]
That's `blockstack-server` calling `os.abort()` when it fails to connect.  Are you actually getting core dump files?  We can change `os.abort()` to `os.kill( os.getpid(), signal.SIGKILL )`.
