### ISSUE TITLE
Detailed installation instructions missing

### ISSUE THREAD

**Issue by meulie** [blockstack/blockstack-core#254]
On https://github.com/blockstack/blockstack-core there's a sentence:

> If you encounter any problems during the pip install, see the [detailed installation instructions](https://blockstack.org/docs/installation).

There's nothing there.

**Comment by elopio** [comment]
Same with "Next, visit the basic usage docs and extended usage docs". It has two dead links.

**Comment by shea256** [comment]
Oh sorry, here's the new link: https://blockstack.org/docs

We'll fix this shortly.

**Comment by jackzampolin** [comment]
The README has changed significantly. This is no longer an issue. Closing.
