### ISSUE TITLE
Where are the RPC and RESTful interfaces documented?

### ISSUE THREAD

**Issue by JustinDrake** [blockstack/blockstack-core#260]
The `README.md` states

> Blockstack Core provides RPC and RESTful interfaces for Blockstack clients.

I cannot see where those interfaces are documented. blockstack.org/docs only seems to document the CLI.

**Comment by muneeb-ali** [comment]
@JustinDrake the Blockstack API is documented in the [api/ directory](https://github.com/blockstack/blockstack-core/tree/master/api).

The RPC interface is a Blockstack internal thing now and we do **not** recommend using it. All interaction with Blockstack Core should happen through the RESTful interface. 

Feel free to re-open this issue, if you have other questions. You can also follow [this discussion RE API docs](https://github.com/blockstack/blockstack-core/issues/280) -- thanks!
