### ISSUE TITLE
How many public blockstack nodes are there?

### ISSUE THREAD

**Issue by JustinDrake** [blockstack/blockstack-core#262]
I see that the CLI by default connects to `node.blockstack.org:6264`. Are there alternative public nodes I can use?

**Comment by muneeb-ali** [comment]
That's the default public node. There are plans by other companies like Microsoft and others to run public nodes. You can deploy your own node on [Azure](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/blockstack.blockstack-core-v14) or [AWS](https://aws.amazon.com/marketplace/pp/B06XGBTRD7).

Also, this should be included in our [new FAQ section](https://github.com/blockstack/blockstack/blob/master/FAQ.md). Feel free to send a PR for this question or any other questions you might have. CC'ing @pstan26

**Comment by shea256** [comment]
As far as the number of nodes, we don't have an exact amount at the moment but we'll be coming out with a counter for the number of nodes that participate in our Atlas network. This is a good estimate of the total number of Blockstack nodes.

Also for reference, the macOS Blockstack app comes with a mediumweight Blockstack node, so quite a few users will be running nodes soon.

**Comment by pstan26** [comment]
added to FAQs

**Comment by jcnelson** [comment]
I'm guessing this is answered?  Closing the issue for now; please re-open if needed.
