### ISSUE TITLE
Package blockstack-core for the Sandstorm app store

### ISSUE THREAD

**Issue by john-light** [blockstack/blockstack-core#265]
We have talked about [Sandstorm](https://github.com/sandstorm-io/sandstorm) in the Blockstack community (I think @shea256 has linked to their blog before) but I don't think we've talked specifically about adding Blockstack to Sandstorm yet. So I am opening this issue to start the discussion. Some background:  

I recently started using Sandstorm to self-host open-source server applications. Self-hosting usually has a relatively high barrier to entry, so relatively few people do it. The result is massive centralization and insecurity of data. Sandstorm is one part of the solution to this problem by making it easy and secure to self-host open-source server applications.  

I would like to see blockstack-core packaged for the Sandstorm app store so Sandstorm users like myself can easily install and run our own Blockstack nodes. You can find instructions for packaging your app for Sandstorm here:  

https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/

**Comment by muneeb-ali** [comment]
@john-light is this still relevant given that [Sandstorm is shutting down](https://sandstorm.io/news/2017-02-06-sandstorm-returning-to-community-roots)?

**Comment by shea256** [comment]
The founders of the Sandstorm company are apparently still maintaining the project. They just don't have a company for now and have hinted at creating a new one in the future if they have more resources.

Personally I don't see this as a priority but up to you guys.

**Comment by john-light** [comment]
Revisiting - I would play wait and see to determine if the open source Sandstorm dev community sustains itself without the Sandstorm company. If in six months or so (or whenever it becomes a priority to make it really easy for non-technical end-users to run their own Blockstack full nodes) we can revisit. I will close this issue for now and reopen it later if needed.
