### ISSUE TITLE
Option to bypass email prompt

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#270]
Can we add an option (or is there one already?) to bypass the interactive email prompt for unattended installation of blockstack? (for example, when deployed with one of the native installers).

**Comment by jcnelson** [comment]
Added `-y/--yes` to assume defaults for all config fields

**Comment by jcnelson** [comment]
Okay, this should be fixed now.  Please re-open if it happens again.  Thanks!
