### ISSUE TITLE
Option to reduce verbosity of server output

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#271]
Running `blockstack-server --foreground` outputs lots of debug info. On explorer, we're seeing about 3-4gb of log output per day. Is there a way to only get warn/error output?

**Comment by muneeb-ali** [comment]
+1 Yeah I think it makes sense to have different levels of logging.

**Comment by muneeb-ali** [comment]
Added to 14.2 release which focuses on UX.

**Comment by jackzampolin** [comment]
We have 2 levels of logging now. Normal and `-debug`. Closing this as implemented.
