### ISSUE TITLE
Change Blockstack CLI password display

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#273]
We might already have an issue about this on the old CLI repo but starting a new one.

We should change the password display and hide the password.

**Comment by shea256** [comment]
This was the original issue and I thought it was merged but the password printout kept coming back:

https://github.com/blockstack/blockstack-cli/issues/48

**Comment by muneeb-ali** [comment]
Ah, that was the password display during the user input process. I pushed a fix for it then.

This is a display of password with the backup master key (after wallet generation).

**Comment by jackzampolin** [comment]
This has been implemented. Closing.
