### ISSUE TITLE
Automate zonefile + profile data updates in the CLI

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#278]
Right now the CLI works well for new registrations but we don't have a good way to update profile data and zonefiles. We need to automate these steps and improve the UX around this process. 

For reference here is the [update tutorial](https://www.youtube.com/watch?v=wA01UJwu7CY&t=220s&list=PLXS8JJHIn4nGCU2uW85dHXpkQJ7QA5JkX&index=5) and it only covers zonefile changes. Creating a new profile and signing it properly is another step.

**Comment by jcnelson** [comment]
We basically need an "accept name" command on the CLI.  Once the transfer completes, the user should run it to "finish" the transfer.  The command should:

* add a data public key to the user's wallet
* add the data public key to the user's zone file
* add our default storage bucket to the zone file
* put the new zone file hash with a `NAME_UPDATE`
* replicate the new zone file
* re-sign and replicate the profile with the data key once the `NAME_UPDATE` goes through

At the same time, we should update onename.com so it sends a little bit of BTC to the user's payment key so they'll be able to run the "accept name" command without further delay.

**Comment by muneeb-ali** [comment]
I can add support for sending some BTC to the new owner address when a name is transferred out.

It'd be great to automate all these steps because in 5-6 months we'll be asking a **lot** of users to move their names away from the Onename app and to a browser. The steps for transferring to the browser would be similar.

**Comment by jcnelson** [comment]
Want to create a milestone and add this issue to it?  While we're at it, we should add @vsund's issues for renewal so we can have auto-renew turned on by then.

**Comment by muneeb-ali** [comment]
Yep, added a milestone for 14.2 (that is the release after the current rc branch and we should focus on UX in that release).

**Comment by jcnelson** [comment]
I think this is two issues:
* **What do we do about renewal?**  Do we renew before transferring?  Do we do it if it's cheap enough?  Do we only renew users with social proofs?  Do we ask the user to tweet out their renewals in e.g. a newsletter in exchange for a free renewal?

* **What does the user do when we transfer the name to them?**  I think this is much more straightforward:  we implement a `receive_name` command that (1) fetches and authenticates their profile and zone file, (2) re-generates the zone file with their data key, (3) issues a `NAME_UPDATE`, and (4) replicates the new zone file and re-signed profile.

**Comment by jackzampolin** [comment]
See https://github.com/blockstack/blockstack-core/issues/567

**Comment by jcnelson** [comment]
Related: https://github.com/blockstack/blockstack-browser/issues/858#issue-262835274

**Comment by jackzampolin** [comment]
This discussion is slightly out of date at this point. The primary name registration platform is the browser and that does the automation now. I'm going to close this as stale and we can reopen it if needed. Restoring full functionality to the CLI will likely have new implementation details.
