### ISSUE TITLE
API code directory + docs

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#280]
I wanted to discuss where the API code is going. 

Right now, Jude has the interface defined in [blockstack_client/rpc.py](https://github.com/blockstack/blockstack-core/blob/rc-0.14.1b/blockstack_client/rpc.py). The old API code is in the [api](https://github.com/blockstack/blockstack-core/tree/master/api) directory.

I don't think this is important for the current sprint but we should have the new API code in the api/ directory as I feel that's the most natural place new developers will look for it. 

We've seen issues earlier about people [looking for the interfaces and docs](https://github.com/blockstack/blockstack-core/issues/260).

Our rule of thumb is to put all docs & protocol specs in blockstack/blockstack repo but for the API I think it makes sense to list the API interfaces here. Just like we have the installation instructions here, the API docs are part of "how to use this software". 

Let me know what you guys think. I started a [related issue on the blockstack-desktop-specs](https://github.com/blockstack/blockstack-desktop-specs/issues/8) repo (for moving API docs).

Two decision items are: 

 - [x] where should the code live (I'm proposing the api/ folder)
 - [x] where should the docs live (I'm proposing the api/ folder)

We can close this issue when we have a decision on this.

CC: @jcnelson, @larrysalibra, @shea256

**Comment by shea256** [comment]
+1 to the `/api/` folder for code.

I'm fine with either `blockstack/blockstack` or the `/api/` folder for docs. The original thinking with keeping them outside of here was to have an interface independent of the implementation. But if it's easier to just keep it in here then that makes sense. Merge in the commits from the other repo perhaps?

**Comment by muneeb-ali** [comment]
Sounds good. I had a call with @jcnelson and he agrees on docs in api/ folder and (eventually) code there as well. I'm marking this as decided.

Next steps:

- [ ] I will merge the [desktop-specs](https://github.com/blockstack/blockstack-desktop-specs/issues/8) repo and preserve commit history from it. 
- [ ] I will start a separate issue to move the API code to api/ (it won't be done this week).

**Comment by muneeb-ali** [comment]
Desktop-specs repo merged into this repo while preserving the commit history. 

I merged this to master and these changes shouldn't conflict with the v0.14.1 release candidate.

**Comment by muneeb-ali** [comment]
Created a new issue for [code reorg](https://github.com/blockstack/blockstack-core/issues/311) and closing this one.
