### ISSUE TITLE
Discuss new CLI interface 

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#287]
In v0.15 we will revamp the CLI interface. A reminder that major versions are either (a) consensus breaking changes or (b) interface changes. Since this change breaks the last CLI interface, we'll jump from v0.14.x to v0.15. 

I'm starting this issue as a thread for discussing CLI commands in general. For reference here is the current list:

```
(blockstack)muneeb@amsterdam:Desktop$ blockstack
usage: blockstack [-h]
                  {balance,configure,deposit,import,info,lookup,migrate,names,ping,price,register,renew,revoke,set_advanced_mode,transfer,update,whois}
                  ...

Blockstack cli version 0.14.0.7

positional arguments:
  {balance,configure,deposit,import,info,lookup,migrate,names,ping,price,register,renew,revoke,set_advanced_mode,transfer,update,whois}
    balance             Get the account balance
    configure           Interactively configure the client
    deposit             Display the address with which to receive bitcoins
    import              Display the address with which to receive names
    info                Get details about pending name commands
    lookup              Get the zone file and profile for a particular name
    migrate             Migrate a profile to the latest profile format
    names               Display the names owned by local addresses
    ping                Check server status and get server details
    price               Get the price of a name
    register            Register a name
    renew               Renew a name
    revoke              Revoke a name
    set_advanced_mode   Enable advanced commands
    transfer            Transfer a name to a new address
    update              Set the zone file for a name
    whois               Look up the blockchain info for a name

optional arguments:
  -h, --help            show this help message and exit
{}
```

There is also an advanced mode, which we can go over after the basic operations are fleshed out.

I can get feedback from everyone, try to reach consensus on what the next interface should look like, and lock-down the description and get sign off. We'll close this issue when we have the new interface locked down.

We'll support the new interface for at least a year (meaning Spring 2018) if not longer. So now is a good time to send any comments/concerns!

**Comment by larrysalibra** [comment]
From https://github.com/blockstack/blockstack-core/issues/286#issuecomment-278616862
> With regards to advanced mode. I'm not sure why we have this mode. In my view, if someone is using the command line interface, they're already "advanced" - If we're looking to not confuse people by showing them too many commands they may not need to know about, we could make it so that running blockstack or blockstack --help shows only the "basic" commands and that running something like blockstack --help-advanced shows info about the other commands. That there's state around which arguments are accepted on the command line makes it confusing to help people. I can't just say run blockstack get_name_blockchain_record larry.id - I need to first ask them to make sure they have advanced mode enabled.

**Comment by larrysalibra** [comment]
Would be also nice to have help for each command:

`blockstack help register` could give me a list of the parameters the command takes and a description of what it does. Right now my options are look at the source code or go through the command in interactive mode.

Another option would be to show detailed help for `blockstack register` when you run it without arguments. (See the `diskutil` command on macOS for an example of this.)

**Comment by jcnelson** [comment]
This can be added in the next sprint.  All the information is already present in the code's docstrings; all that is needed is a `help` CLI command that loads up the other command, grabs its docstring, and formats it.

**Comment by jackzampolin** [comment]
Moving discussion to: https://github.com/blockstack/blockstack-core/issues/567
