### ISSUE TITLE
Implement durable storage for DHT

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#29]
DHT storage is currently not durable (i.e., key-value pairs are not stored on disk and a DHT node will lose all data on a reboot). This might be fine when the DHT network becomes large, but for bootstrapping the network we want to ensure that we don't lose data in the DHT e.g., if AWS reboots the VMs that Onename is running. 

On a related note, we need more DHT nodes by different organizations running on different data centers.

For the durable storage, I'm thinking of just hooking in MongoDB or SQLite. Benefit of MongoDB is that our data is JSON anyway. Benefit of SQLite is that users won't have to install any DB.

**Comment by jcnelson** [comment]
If we're just getting/putting data with globally-unique keys, why not just store them directly into the filesystem?  Will we need to index or search them later?

**Comment by muneeb-ali** [comment]
This is somewhat covered with github.com/blockstack/dht-mirror having a MongoDB-backed mirror of the DHT. I do think that individual nodes being able to have persistent state between failures is still important.

**Comment by jcnelson** [comment]
This will be solved by Atlas nodes.

**Comment by jcnelson** [comment]
Solved in 0.14 with Atlas.
