### ISSUE TITLE
Issue running blockstack rc-0.14.1b after installation on macOS 

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-core#290]
Hey @jcnelson I tried installing from the `rc-0.14.1b` branch on my home computer and I'm having some problems. The installation went through just fine but now I'm not able to run the "blockstack" command.

Here's my traceback:

```
~-$ blockstack
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/blockstack", line 4, in <module>
    __import__('pkg_resources').run_script('blockstack-client==0.0.12.7', 'blockstack')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in <module>
    @_call_aside
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3056, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3083, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 645, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 946, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 833, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-bitcoinrpc==0.1' distribution was not found and is required by pybitcoin
```

I nuked the `.blockstack` folder already.

Any idea what might be going on here?

Thanks!

**Comment by jcnelson** [comment]
You're missing the `python-bitcoinrpc` package.

**Comment by shea256** [comment]
I have `python-bitcoinrpc==0.1` already installed and I installed virtualchain, dns-zone-file-py, and blockstack-profiles-py all from the rc-0.14.1 branches.

**Comment by jcnelson** [comment]
It's something in your imports.  The script itself isn't even loading.  The error is from the Python packing system.

**Comment by shea256** [comment]
What imports? My python version is 2.7.10 btw.

**Comment by shea256** [comment]
I have a clean environment, nothing was installed before I installed Blockstack.

**Comment by jcnelson** [comment]
Can you try it in a virtualenv?

**Comment by shea256** [comment]
Trying, currently working through some installation issues. I'll circle back.

**Comment by shea256** [comment]
Hitting more installation issues, I'm just going to upgrade to macOS Sierra and hope that fixes the problem. Brb, will take a bit of time to upgrade.

**Comment by jcnelson** [comment]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/blockstack", line 4, in <module>
    __import__('pkg_resources').run_script('blockstack-client==0.0.12.7', 'blockstack')
```

You have an old `blockstack_client` around, I bet.  Try `pip uninstall`-ing all of your `blockstack` and `blockstack_client` packages, and re-installing.

**Comment by shea256** [comment]
OK I'll try that first.

**Comment by shea256** [comment]
I found a folder called `.blockstore-client` but that's it.

I uninstalled everything and reinstalled Blockstack Core (and the required packages) only:

> sudo -H pip install git+https://github.com/blockstack/virtualchain.git@rc-0.14.1 git+https://github.com/blockstack/blockstack-profiles-py.git@rc-0.14.1 git+https://github.com/blockstack/dns-zone-file-py.git@rc-0.14.1 git+https://github.com/blockstack/blockstack-core.git@rc-0.14.1b

The installation was successful.

Did `blockstack-client` put anything in any other folder or location? Is there some other state somewhere else that is lying around?

**Comment by jcnelson** [comment]
It wasn't `~/.blockstack-client` or anything in your `$HOME` directory.  The problem was that you had multiple conflicting packages and scripts installed that had different interfaces and dependencies.

Specifically, the problem was that `/Library/Frameworks/Python.framework/Versions/2.7/bin/blockstack` was installed such that it required `blockstack_client=0.0.12.7` (or thought it could use `blockstack_client=0.0.12.7`).

**Comment by shea256** [comment]
OK to be clear, the installation was successful before and it was successful again.

I just still can't use the CLI.

I'm going to try to remove the `/bin/blockstack` file and try installing again.

**Comment by shea256** [comment]
Damn that didn't work.

```
~-$ blockstack
-bash: /Library/Frameworks/Python.framework/Versions/2.7/bin/blockstack: No such file or directory
```

**Comment by jcnelson** [comment]
I must emphasize that the program that you run (`blockstack`) is *not* the script in `blockstack_client/bin/blockstack`.  When you install with pip, it will generate a `blockstack` script that loads and executes our `blockstack_client/bin/blockstack` once it can be sure that all of the necessary dependencies are installed.  This pip-generated script is what's failing, not our code.

**Comment by shea256** [comment]
OK so any thoughts on what I should try next?

**Comment by shea256** [comment]
OK I just installed a new version of python (2.7.11) and now it works!

**Comment by jcnelson** [comment]
"When in doubt, throw it out" I guess :)

**Comment by shea256** [comment]
Yes haha, thank you. Glad it's working now :)
