### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by dsmurrell** [blockstack/blockstack-core#291]
'basic usage docs' and 'extended usage docs' links from here: https://github.com/blockstack/blockstack-core

are broken.

**Comment by muneeb-ali** [comment]
Thanks for pointing it out! Both links should temporarily point to https://blockstack.org/docs until we figure out how to organize basic vs. extended usage docs.

Can you submit a pull request with the changes and I can merge it? This PR can go to the Master branch.

**Comment by lacabra** [comment]
Just came across this issue and created a pull request as suggested (#386).

**Comment by jcnelson** [comment]
PR merged :)  links work again
