### ISSUE TITLE
Add CORS headers to the REST API

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#294]
The REST API needs to return `Access-Control-Allow-Origin: *` so that we can access it from other origins.

<img width="682" alt="screen shot 2017-02-11 at 10 44 55 pm" src="https://cloud.githubusercontent.com/assets/597182/22857525/61a717d4-f0af-11e6-857a-14391b626b25.png">

**Comment by shea256** [comment]
In the onename API we have this:

```python
from flask_crossdomain import crossdomain

@crossdomain(origin='*')
def an_actual_api_endpoint:
    pass
```

We could do this same on the REST API for Core.

**Comment by larrysalibra** [comment]
We have the same in the explorer. Code is here -> https://github.com/blockstack/blockstack-explorer/blob/master/tools/runserver.py#L8

**Comment by jcnelson** [comment]
Pushed fix to rc-0.14.1b

**Comment by larrysalibra** [comment]
Thank you! Works great!

**Comment by larrysalibra** [comment]
CORS doesn't work on `POST /v1/names` - it needs to respond to the browser's `OPTIONS` preflight check:

<img width="1030" alt="screen shot 2017-02-12 at 9 37 55 am" src="https://cloud.githubusercontent.com/assets/597182/22860447/20c73bec-f107-11e6-87e1-e1b644241e17.png">

**Comment by larrysalibra** [comment]
Almost there. Looks like we're still missing a header:
<img width="875" alt="screen shot 2017-02-12 at 3 57 04 pm" src="https://cloud.githubusercontent.com/assets/597182/22862678/02d94f6e-f13c-11e6-9ccb-6785431cb6b8.png">

**Comment by larrysalibra** [comment]
fixes merged. closing issue.
