### ISSUE TITLE
Integrate the search subsystem with the API

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#300]
After working on the search subsystem, I'm realizing that the developer UX can be improved significantly if we build a "fast sync" option for search as well. 

Similar to the [blockstack fast sync](https://github.com/blockstack/blockstack-core/issues/272) it can fetch an index (signed by developers) and immediately start serving search results in a new deployment. We can start a background process that creates a (trusted) index locally. 

Until the local index is created, yes, you're trusting the developers for the data you got but it's exactly the same security model as the general fast sync of Blockstack Core and can improve the UX a lot.

Keeping the discussion flag on this until I get more feedback and we get a yes/no decision for implementing this feature.

Not assigning a milestone right now.

**Comment by muneeb-ali** [comment]
We decided to not implement fast-sync for search and instead make search a separate subsystem.

@jcnelson, @shea256 and @larrysalibra here are new requirements: 

- Normally users will be pointed to search.blockstack.org (a public server) by default.
- The public server will have information/links for how to deploy their own node. 
- Initially, we will have a simple http://search.blockstack.org/v1/search?query=wenger interface
- Later, we'll merge the interface with the Blockstack API so you can turn search on and the v1/search end point will appear along with the rest of the Blockstack API.

Once I hear from the people tagged here, I will go ahead and close this issue.

**Comment by larrysalibra** [comment]
Sounds good. I'd also add that the separate subsystem should only interact with core via the Blockstack API. This will help us dogfood the API.

**Comment by muneeb-ali** [comment]
Agreeing that we don't need fast-sync for search. 

Changed the title of the issue to reflect that we're integrating the search end-point with the API. 

Removed the discussion label since we're decided on requirements.
