### ISSUE TITLE
Automate publishing of fast-sync images

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#304]
We need to automate the publishing of Blockstack state i.e., (a) Blockstack Core snapshots, (b) the Atlas DB, and (c) zonefiles for fast-sync mode. 

We decided on the following process: 

- We'll publish new state files (images) every 24 hours. So a new node using fast-sync can be at most 24 hours behind the latest state. 
- We'll get signatures from at least 3 Blockstack Core developers on the state files.
- We'll have a cron job that automates the publishing of these images.

**Comment by muneeb-ali** [comment]
This issue can be closed when we can have the functionality to publish images with signatures. 

The [cron job](https://github.com/blockstack/blockstack-core/issues/305) is a separate issue.

**Comment by muneeb-ali** [comment]
Retargeting this and moving out of the [Feb 13-23 sprint](https://github.com/blockstack/blockstack-core/projects/4).

**Comment by jcnelson** [comment]
Auto-publishing is working.  Only 1 signature though (need you and Ryan to set up your own servers).

**Comment by jcnelson** [comment]
Confirmed working.
