### ISSUE TITLE
Cron job for making fast-sync images daily

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#305]
Once we can [publish fast-sync images](https://github.com/blockstack/blockstack-core/issues/304), we'll have a cron job to automatically refresh the images every 24 hours.

**Comment by muneeb-ali** [comment]
Retargeting this and moving out of the [Feb 13-23 sprint](https://github.com/blockstack/blockstack-core/projects/4).

**Comment by jcnelson** [comment]
Got this working with `bin/blockstack-snapshots`
