### ISSUE TITLE
Share API secret between Core and clients

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#306]
We need to share an API secret between Core and any clients like the Portal. We're currently thinking about using the CLI interface to share this secret. 

We'll post more details here after ironing out this process.

**Comment by jcnelson** [comment]
This is doable in Core by passing `--api_password PASSWORD`.

**Comment by muneeb-ali** [comment]
Marking as done for --api_password. I'll open a separate issue for UX improvements of this process.
