### ISSUE TITLE
Live design simple page for search.blockstack.org

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#309]
We can use the Blockstack design like the [explorer](https://explorer.blockstack.org) and display something better than [this page](http://search.onename.com).

I'll work with Guy on this. 

@guylepage3 please keep in mind that this task is low-priority and we need something super simple and quick. Ideally, we'd just take the design from the explorer and apply to a simple 1-page HTML.

**Comment by guylepage3** [comment]
@muneeb-ali can we just take from what we currently have styled on the profiles app? recycle code?

**Comment by shea256** [comment]
@guylepage3 I believe what @muneeb-ali wants is something like this:

https://bitnodes.21.co/nodes/24.251.195.61-8333/

![screen shot 2017-02-14 at 6 04 03 pm](https://cloud.githubusercontent.com/assets/994646/22953625/05355988-f2e0-11e6-8a61-32f4e9cae34e.png)

That means the page would only have some simple info about the server and would have instructions for how developers can hit the API endpoints. It would not have any UI for searching.

@muneeb-ali please correct me if I'm wrong.

**Comment by shea256** [comment]
I imagine it being even simpler and being a welcome page to the API. As in, it wouldn't have nearly as many stats or the graph above. This could be a page that would be the same for a publicly facing Blockstack Core API.

We decided in our meeting that the search service is going to be an extension of the main API, and not a separate thing. That was the conclusion right @muneeb-ali @jcnelson?

**Comment by muneeb-ali** [comment]
Yep, so I'm thinking of this as in the short-term: 

a) We have something (anything!) better than this: 

![image](https://cloud.githubusercontent.com/assets/669932/22954272/79fa9c12-f2e3-11e6-9d9a-6c861c0b8147.png)

because to finish this sprint search.blockstack.org needs to go live and replace the old search service.

and then in the long-run we have

b) The Blockstack API welcome/doc page, where you'll have search enabled. So that task is really designing the Blockstack API page (and not search). 

This issue is for the short-term task i.e., when we go live on 2/23 with search.blockstack.org what will the users see when they visit that page.

I think it can be something super simple that describes what search.blockstack.org is, and points to instructions for how can they run their own node. We can include some simple stats but I'm not thinking about anything fancy.

**Comment by guylepage3** [comment]
Ok so the site is just a search result view? not a place where someone can go and enter in a query into an input field and then see a search result?

**Comment by muneeb-ali** [comment]
@guylepage3 can we mark a few hours tomorrow to work on this?

**Comment by guylepage3** [comment]
sounds good.

**Comment by guylepage3** [comment]
ok. so I am not understanding the actual requirements here?

what is needed? what views are needed? is it just styling that one line?

**Comment by muneeb-ali** [comment]
@guylepage3 Here is some sample test. 

Heading: Blockstack Seach

Description: The search subsystem for Blockstack Core creates a search index for data associated with names registered on Blockstack. The search subsystem currently indexes the .id namespace but can be easily expanded to include other namespaces. 

You can query this node by sending queries like: 

> https://search.blockstack.org/search?query=wenger

You can deploy your own search node by following the instructions on [this Github repo](https://github.com/blockstack/blockstack-core/tree/search/api/search). The search subsystem is part of Blockstack Core, which is released as open-source software.

**Comment by guylepage3** [comment]
complete. pushed to the `search` branch.

<img width="1247" alt="screenshot 2017-02-26 21 11 26" src="https://cloud.githubusercontent.com/assets/1711854/23346434/3449a526-fc68-11e6-874c-f3dfeea52723.png">

**Comment by muneeb-ali** [comment]
New search service is now live at: https://search.blockstack.org

Great work @guylepage3.
