### ISSUE TITLE
update the description for this repo

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-core#312]
Can we discuss what the description should be for this repo?

Currently we have this for the description:

> The reference implementation of Blockstack

We also have this in the readme:

> Blockstack Core is the reference implementation of Blockstack.

With this language, we're implying that "Blockstack" refers only to the scope that Blockstack Core encompasses (the node backend software). If that were the case, it'd be appropriate to use separate brands for software that's not a part of Blockstack Core.

The way I see it is "Blockstack" refers to an entire suite of software, from the main server / node backend to the browser portal. Thus, we should avoid referring to Blockstack Core as a reference implementation of Blockstack.

In my view, Blockstack Core could be referred to as a reference implementation of Blockstack nodes or of the Blockstack server.

As a separate point, is there something that we want to communicate in the description for someone who suddenly happens upon https://github.com/blockstack/blockstack-core? What is most appropriate to include in the description?

Starting a conversation on this and tagging @muneeb-ali @jcnelson @guylepage3 @larrysalibra @pstan26 on this conversation.

**Comment by guylepage3** [comment]
>The way I see it is "Blockstack" refers to an entire suite of software, from the main server / node backend to the browser portal. Thus, we should avoid referring to Blockstack Core as a reference implementation of Blockstack.

@shea256 are you suggesting that "Core" is Blockstack. Everything else is not? If you are I am in agreement. But, we also need to think about maintaining multiple brands with the community we have today. If we feel that adding separate brands for separate products, which I believe would garner a higher level of interest amongst developers, then we should devise a strategy around community community engagement and bump up the level of priority so that we execute adding more community involvement to the team. imo

**Comment by muneeb-ali** [comment]
My intention here is to say that Blockstack protocol goes to github.com/blockstack/blockstack and the reference implementation of that protocol is Blockstack Core.

This is similar to how most other projects are organized e.g., IPFS, Bitcoin etc. 

Is there a protocol that Portal follows? To me it looks like an application level thing and there can be many many applications that are build on top of Blockstack the protocol (implemented by Blockstack Core).

**Comment by muneeb-ali** [comment]
Let's take TCP/IP as an example. You have TCP/IP the protocol and then various implementations of TCP/IP. Any apps or higher-level services built using TCP/IP are not included in the protocol or the reference implementation of that protocol.

**Comment by jackzampolin** [comment]
Going to close this as complete. We stayed with `The reference implementation of Blockstack`
