### ISSUE TITLE
Improve core fee estimates

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#313]
Core's estimated fees seem low and result in long confirmation times.

**Comment by jcnelson** [comment]
Is this only for `withdraw`, or for all transactions?

**Comment by larrysalibra** [comment]
I've only experienced it with withdraw so far. I'll be trying a registration in about 6 blocks or so and will will let you know how that goes.

**Comment by larrysalibra** [comment]
an example: i submitted[ this withdraw request ](https://live.blockcypher.com/btc/tx/1361bfe2ad3d179c5057bda11afcdb6e05e26088cde4d54bc040cbd653827d68/)for some bitcoin in my blockstack core wallet  before[ i sent more bitcoin to the core wallet from bread wallet ](https://live.blockcypher.com/btc/tx/270b45fa38d9cfcc5f002803f218e919f2568f2d51057029125529dda4ead1d4/) - presumably because of bread wallet's higher fee, its transaction has already been confirmed (2/6) while the earlier transaction has yet to be included in a block.

**Comment by larrysalibra** [comment]
In the process of trying a registration. The preorder fee looks fine: https://live.blockcypher.com/btc/tx/e3b7cec21350c689ae70cab39e392f5cdf3af000a95c3769ae7a308312c727eb/

**Comment by jcnelson** [comment]
Good to know :)

Up until recently, `withdraw` had a hard-coded tx fee.  That has been fixed in my tree, but not yet pushed.

Every other transaction uses dynamic fee estimation from `bitcoind`.

**Comment by larrysalibra** [comment]
Great. Yes - can confirm that all 4 steps of the registration call worked and the fees were such that they were picked up immediately in the next block.

**Comment by jcnelson** [comment]
Awesome!  Can we close this issue?

**Comment by larrysalibra** [comment]
Yes. Thank you.
