### ISSUE TITLE
Setup Blockstack marketplace account and finish testing

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#314]
AWS has a fairly strict testing/ingestion process for images. Need to start early on this task because they can take 3-5 days for testing/publishing.

@guylepage3 tagging you because, like with Azure, we'll need some logos for the AWS marketplace.

**Comment by guylepage3** [comment]
Thanks @muneeb-ali can we get some image specifications from them and we will need access and a visual of where they're being placed. thanks.

**Comment by muneeb-ali** [comment]
I got this setup. 

@guylepage3 I'll get you specs.

**Comment by muneeb-ali** [comment]
Thanks @guylepage3 for [putting up the contact info](https://blockstack.com/team). I just updated the AWS folks that they can check the contact info now.

**Comment by muneeb-ali** [comment]
@guylepage3 can you kindly update the zipcode to 10012?

**Comment by guylepage3** [comment]
@muneeb-ali on it now

**Comment by muneeb-ali** [comment]
Our AWS account got approved. AMI submitted for testing.

**Comment by guylepage3** [comment]
Logo production, here: https://github.com/blockstack/designs/issues/214
