### ISSUE TITLE
Failed to start RPC endpoint in the CLI

### ISSUE THREAD

**Issue by MaveriQ** [blockstack/blockstack-core#316]
This refers to the blockstack-cli issue https://github.com/blockstack/blockstack-cli/issues/175 and comment by @muneeb-ali 

The workaround I have found is by deleting the api_endpoint.pid file in .blockstack/ directory. Please include this 'fix' once the CLI is merged here. 

Thanks

**Comment by muneeb-ali** [comment]
Here is the original error reported by @borisreitman:

```

$ blockstack register borisr__at__hushmail__dot__com__email.id
API endpoint already running (PID 53284, /home/vagrant/.blockstack/api_endpoint.pid)
Failed to start RPC endpoint (in working directory /home/vagrant/.blockstack).
Please check your password, and verify that the working directory exists and is writeable.
```

Also, tagging @cryptocracy who had a similar issue.

**Comment by jcnelson** [comment]
Should be working in `rc-0.14.1b`.

**Comment by jackzampolin** [comment]
This is working in the current release. Closing
