### ISSUE TITLE
Pass wallet password as API argument 

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#317]
We currently (#275) pass the wallet password to the core api at api start up using the `--password` flag

It seems to me like it would make more sense to pass this password with each request that performs an API call the requires using the wallet.

I'm opening this issue as a reminder / to start a discussion about this.

**Comment by jcnelson** [comment]
Added in my (unpushed) tree as `--api_password <PASS>`

**Comment by jcnelson** [comment]
This has been pushed.

**Comment by jcnelson** [comment]
I think the plan going forward is that Core will be given a "callback URL" that it will `GET` when a sensitive operation gets invoked (like name registration or fund withdraw).  I'm open to supporting both the wallet password and the callback URL, but let's talk more about this.

**Comment by muneeb-ali** [comment]
@larrysalibra did we decide on this?

**Comment by jackzampolin** [comment]
Core is getting removed from the browser so I'm going to go ahead and close this issue.
