### ISSUE TITLE
Failed building wheel for fastecdsa

### ISSUE THREAD

**Issue by Rimann91** [blockstack/blockstack-core#318]
I recieve this error everytime I try to install the blockstack-core. Running Ubuntu 16.04

	Failed building wheel for fastecdsa
	  Running setup.py clean for fastecdsa
	Failed to build fastecdsa
	Installing collected packages: virtualchain, jsonpointer, jsonpatch, warlock, blockstack-profiles, fastecdsa, typing, urllib3, dropbox, blockstack
	  Found existing installation: virtualchain 0.14.0
	    Uninstalling virtualchain-0.14.0:
	Exception:
	Traceback (most recent call last):
	  File "/home/riley/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
	    status = self.run(options, args)
	  File "/home/riley/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
	    prefix=options.prefix_path,
	  File "/home/riley/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 778, in install
	    requirement.uninstall(auto_confirm=True)
	  File "/home/riley/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
	    paths_to_remove.remove(auto_confirm)
	  File "/home/riley/.local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
	    renames(path, new_path)
	  File "/home/riley/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
	    shutil.move(old, new)
	  File "/usr/lib/python2.7/shutil.py", line 300, in move
	    rmtree(src)
	  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
	    onerror(os.remove, fullname, sys.exc_info())
	  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
	    os.remove(fullname)
	OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/virtualchain-0.14.0.egg-info/not-zip-safe

**Comment by jcnelson** [comment]
Hey @Rimann91, thanks for reporting!  Are you using `sudo pip install` or just `pip install`?  You may need to do the former (unless you're using a virtualenv).

**Comment by Rimann91** [comment]
i am using a virtualenv and I use sudo on every install, thanks for the reply

**Comment by jcnelson** [comment]
Are you able to install `fastecdsa` by itself?  e.g. with `sudo pip install fastecdsa`.  You may also need to install `libgmp-dev` (with `apt-get install`).

**Comment by jcnelson** [comment]
Closing the issue from inactivity.  If the problem persists, please re-open.

**Comment by radicalpraxis** [comment]
This fixed the issue for me: `export LDFLAGS="-L/usr/local/opt/openssl/lib -L /usr/local/opt/gmp/lib" && export CPPFLAGS="-I/usr/local/opt/openssl/include -I/usr/local/opt/gmp/include"`

**Comment by larrysalibra** [comment]
Thanks for sharing that @radicalpraxis !

**Comment by Elliot-Cokie** [comment]
> libgmp-dev
sudo apt-get install libgmp-dev
then 
pip3 install fastecdsa

**Comment by gawd-coder** [comment]
> > libgmp-dev
> > sudo apt-get install libgmp-dev
> > then
> > pip3 install fastecdsa

Thanks for sharing, this worked <3

**Comment by beginnerslvl** [comment]
what about windows?

**Comment by maxisacoder** [comment]
what about macOS

**Comment by Neo77-cyber** [comment]
> 

?????

**Comment by FledPaul** [comment]
> This fixed the issue for me: `export LDFLAGS="-L/usr/local/opt/openssl/lib -L /usr/local/opt/gmp/lib" && export CPPFLAGS="-I/usr/local/opt/openssl/include -I/usr/local/opt/gmp/include"`

Thank you, that worked.

**Comment by ninjainfosec** [comment]
> Are you able to install `fastecdsa` by itself? e.g. with `sudo pip install fastecdsa`. You may also need to install `libgmp-dev` (with `apt-get install`).

This is brilliant and helped and my same issue has been resolved. thanks a ton dear

**Comment by darixsamani** [comment]
this solution work for me, change path python below depend on your python version

Fix 2: Add include header
If the header file is in the path /usr/include/python3.10/Python.h, add the following line in your C/ C++ code:

#include <python3.10/Python.h>
