### ISSUE TITLE
Typo in quick start manual

### ISSUE THREAD

**Issue by vsund** [blockstack/blockstack-core#319]
I guess you mean `pip install blockstack-server` instead of `blockstack` at https://github.com/blockstack/blockstack-core#quick-start?
`blockstack` doens't ship the server part for me :) After installing `blockstack-server` everything worked as intended.

**Comment by vsund** [comment]
Just noticed that there's a `start_server` command in `blockstack`. Did you mean that command?

**Comment by jcnelson** [comment]
We merged everything into `blockstack` as of 0.14.1 :).  Installing `blockstack` should also install `blockstack-core`, which is the indexer (renamed from `blockstack-server`).  Are you still seeing this problem?

**Comment by vsund** [comment]
This is resolved now :)
