### ISSUE TITLE
Switching to bin/blockstack-core 

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#323]
We're still using bin/blockstack-server and now calling the repo Blockstack Core. We should add an alias “bin/blockstack-core” to bin/blockstack-server. This way the older bin/blockstack-server will still work while we update our docs at various places.

Also, now that the CLI and Core are in the same repo, we should include Core in the installation of “blockstack” i.e.,

> pip install blockstack

will give you everything and users can then do

> $ blockstack-core start

as well as

> $ blockstack info

and there will be no need to install blockstack-core separately.

**Comment by jcnelson** [comment]
Done. b48022efa12228e788b2a5cb165fe74f781364f5
