### ISSUE TITLE
Windows Bash setup fails on `pip install blockstack` [w/ fix]

### ISSUE THREAD

**Issue by csuwildcat** [blockstack/blockstack-core#324]
I was having an issue with the final `pip install blockstack` command throwing an `ImportError`. I was able to fix the error by removing pip and reinstalling as described here: https://odedrabhavesh.blogspot.in/2017/02/importerror-no-module-named.html

Here are the relevant commands

```bash
sudo su root

apt-get purge -y python-pip

wget https://bootstrap.pypa.io/get-pip.py

python ./get-pip.py

apt-get install python-pip
```

Perhaps this should be added to the docs?

**Comment by jcnelson** [comment]
Looks like we need the latest `pip` (9.0.1 or higher).  Thanks for the info!

**Comment by muneeb-ali** [comment]
@csuwildcat I think you had a fix for this and were sending a PR?

**Comment by jackzampolin** [comment]
@csuwildcat is this still applicable? Can I go ahead and close the issue?

**Comment by jcnelson** [comment]
Closing as stale.
