### ISSUE TITLE
Add Sia as a Backend for Blockstack

### ISSUE THREAD

**Issue by DavidVorick** [blockstack/blockstack-core#325]
Sia is a decentralized cloud storage platform with highly competitive pricing. Given that the ultimate goal of Blockstack is decentralization, it seems fitting that the two would go together.

Sia has a full API that is documented here: https://github.com/NebulousLabs/Sia/blob/master/doc/API.md

**Comment by muneeb-ali** [comment]
Thanks for starting the issue. Adding the discussion label. 

We'll go over the Sia API. Tagging @jcnelson as well.

**Comment by jcnelson** [comment]
Hey @DavidVorick, added a skeleton driver and documentation here: https://github.com/blockstack/blockstack-core/blob/rc-0.14.1b/blockstack_client/backend/drivers/_skel.py

**Comment by jackzampolin** [comment]
We are now doing storage drivers in Gaia hubs. I'm going to open an issue there and reference this one.
