### ISSUE TITLE
External per-device keychains

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#326]
@shea256 points out that we not only need per-device keychains (one for your laptop, one for your phone, etc.), but also that these keychains must be external to Blockstack.  This is because your phone can't run a Core node, or have any long-running process.

What this means for Core is that there's some more work to be done on the storage end of things:

* A name's zone files should have the signing public key *for each device* in its zone file.  For example, my zone file might have something like this:

```
$ORIGIN judecn.id
$TTL 3600
pubkey.19db6d10-5cac-43d3-a055-b11e9d0e6cc7 TXT "pubkey:data:03cabba0b5b9a871dbaa11c044066e281c5feb57243c7d2a452f06a0d708613a46"
pubkey.c6b22bea-379c-424a-925c-9d3aad465128 TXT "pubkey:data:0267cd02e6ceae7ed58e3c8ca856633bf5424ccce73c44f0eb7b71d1fe3a6f5e0f"
```

where my device-specific public keys are named as `pubkey.{uuid4}`.

* Devices need a way to share their datastore-specific public keys.  This is problematic, because datastore private keys are hardened children of the device's signing private key---one device cannot derive the datastore public key of another device.  The device that wishes to share must somehow broadcast an attestation from its signing key that the datastore public key is specific to the given application.
    * Maybe datastore public keys can go into the name's profile?
    * Maybe a datastore private key can be an unhardened child of the signing key, but with 256 bits of entropy to make a brute-force search intractable?

* The RESTful API authentication endpoint needs to take a public key from the application, and not rely on the device-specific private key.
    * Blockstack libraries will need to generate the signatures themselves.
    * We'll need to keep the storage-write interface simple: just a signature and the raw payload.

* Various refactoring will need to be done internally to support multiple data public keys.

**Comment by jackzampolin** [comment]
We have gone with a BIP44 compliant HD wallet that works cross device. I'm going to close this as not applicable.
