### ISSUE TITLE
Separate naming, storage, and profile APIs

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#328]
@shea256, @muneeb-ali, @larrysalibra, and myself talked this over, and we feel that in order to support lite clients (e.g. mobile), it will be necessary to move most of the Core functionality off of the device.  Moreover, the functionality may be split across multiple endpoints.  For example, a mobile client may use a 3rd party service's naming API endpoint for doing name management, but may use a separate, personal storage API endpoint (e.g. running in something like Google AppEngine or Amazon Lambda) for loading and storing data to/from their storage providers.

In order to support this, we need to tweak Blockstack Core so that the storage and naming APIs can run in separate instances.  In particular:

* The Core node only indexes the blockchain, participates in the Atlas network, and queues up transactions for sending if its naming API endpoint is activated.  Otherwise, the node does not do anything in the background (making it suitable for running in PaaS platforms).
* The Core node only loads and runs storage drivers if its storage API endpoint is activated.  Otherwise, it never tries to connect to remote storage services nor needs to import storage-specific modules.
* The profiles APIs shouldn't be in the Core server at all.  Only clients should be responsible for parsing a name's zone file and decoding the profile.

**Comment by jackzampolin** [comment]
We have separated this and moved most of this code to JS. Closing as implemented. 🎉
