### ISSUE TITLE
Automate testing of Core on different supported OS

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#335]
We can use VMware Fusion or Virtualbox to test on macOS.

We should be testing on the latest masOS along with earlier versions like Mac OS X 10.10 (Yosemite), Mac OS X 10.9 (Mavericks), Mac OS X 10.8 (Mountain Lion), Mac OS X 10.7 (Lion).

**Comment by jackzampolin** [comment]
Changed name to widen scope.

**Comment by jcnelson** [comment]
Closing this issue as stale.  Blockstack Core is officially supported on UNIX-like platforms, and we ship Docker images to users who don't want to run it directly.
