### ISSUE TITLE
New Blockstack logo on the API page 

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#344]
For now I've taken the old Onename logo out and replaced with a simple Blockstack text. I'll need help from @guylepage3 later to update a new logo there. 

@guylepage3 no need to worry about it in this sprint. I'm just logging it here so we don't forget.

**Comment by guylepage3** [comment]
>@guylepage3 no need to worry about it in this sprint. I'm just logging it here so we don't forget.

sounds good @muneeb-ali

**Comment by muneeb-ali** [comment]
@guylepage3 I'm closing this issue. We can revisit when you have the bandwidth to take a pass over the API docs. For now the hacks I have worked well.
