### ISSUE TITLE
Move wallet keys outside of the "kernel" and into "CLI" 

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#349]
We have three types of access credentials: 

a) Name ownership keys
b) Data signing keys
a) Access keys for storage backends 

The diagram below shows which components within Core have access to them: 

![image](https://cloud.githubusercontent.com/assets/669932/24163113/fb1fdd8a-0e3f-11e7-846d-21f33178da4e.png)

The components of Core are: 

1) CLI (this is a client but is being developed as part of the Core repo)
2) Kernel (this sometimes gets referred to as "Core", this process has most of the complexity) 
3) Indexer (for processing the underlying blockchain) 

Core needs to have access to "access keys for storage backends" but name ownership keys and data signing keys will only be with clients (i.e., the CLI or any other JavaScript client) in the future.

Current status is that we have moved "data keys" to client-only but name ownership keys can be accessed by the kernel process.

We expect to tackle moving name ownership keys outside of the kernel process in a Q2 sprint. Current estimate for time required for that work is 1-2 week (Jude's estimate). 

I'm marking this for v0.15.

**Comment by jackzampolin** [comment]
Closing this as complete.
