### ISSUE TITLE
ensure that miners can't effectively register names for free

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-core#35]
Problem:

With the current design, names are purchased by paying tribute with mining fees. The problem here, though, is that miners can effectively register domain names for free because they're simply paying themselves the mining fees. This could cause the incentives in the system to break down.

**Comment by kef** [comment]
Without thinking about this too hard, one left field idea here would be to stop paying tribute fees to miners and just let them have the ability to register free names as their payment.

Doesn't work too well to begin with since the names might not be worth much unless blockstore gets some traction. Perhaps give them fees as well to begin with and then phase them out as names become more valuable.

New names are essentially as valuable as whatever fee users pay to register them, so giving free names to the miners is pretty much just saving the step of miners swapping fees for names.

Much simpler, but there's probably a hole you could drive a truck through somewhere in this idea.

**Comment by shea256** [comment]
Good idea, thanks for bringing this up.

This is much simpler, but unfortunately it could have massive problems. Imagine GoDaddy and Namecheap and all the registrars could register names for free. Then they'd just get all the names for themselves and there would be no opposing force preventing squatting. The very reason you can get a (somewhat) reasonable domain right now is that the registrars can't register an unlimited number of names (which they'd be able to do if they were free). This is the truck you can drive through that idea.

As it turns out, solution 3 with OP_CHECKLOCKTIMEVERIFY works absolutely perfectly. It's just that we need to wait for that opcode to come out, which could take a few months.

**Comment by jcnelson** [comment]
We're burning fees at least until OP_CHECKLOCKTIMEVERIFY becomes widely available.  Even when it does become widely available, I suspect that using it would let mining pools mass-register a bunch of namespaces (proportional to their mining power) and be statistically guaranteed that they will regain their share of the fees.  For example, if one miner controls 20% of the mining power, that miner can expect to register 20% of the namespaces and regain 20% of the OP_CHECKLOCKTIMEVERIFY rewards at a later date (assuming they still control 20% by the time they have all been reclaimed).  The reward might not sum exactly to 20% of the BTC spent, but it would likely be significant enough to make it worthwhile (and possibly profitable).  My point is, it looks like mining pools' entrenched positions would allow them to gain control of all the namespaces without losing much money.

**Comment by shea256** [comment]
@jcnelson any way you slice it, a mining pool with 20% mining power gets an expected discount of 20%. I'd think of it that way rather than "1 namespace is free for every 5 registered."

**Comment by shea256** [comment]
As @jcnelson said above, back in September we switched over to burning coins as a method for paying name fees to the name gods.

At this point in time, OP\_CHECKLOCKTIMEVERIFY has been merged and pushed out in the latest Bitcoin Core release (0.11.2):

https://www.reddit.com/r/Bitcoin/comments/3t04fp/psa_please_upgrade_to_bitcoin_core_0112_to/

Now we just need to wait for 95% of miners to upgrade to the new version and OP\_CHECKLOCKTIMEVERIFY will be live and ready to be incorporated into Blockstore.

**Comment by eordano** [comment]
:+1:

You can check the stats for when CLTV will be activated here: http://bitcoin.sipa.be/ver-2k.png How to read the graph: Look at the red line, and wait for it to reach 4 (actually, 3.95 is enough).

The blue line means "how many days, if 100% of miners switch immediately to CLTV-enforcing blocks, before there are at least 950 blocks supporting CLTV out of the last 1001 blocks".
I use it as "check back again in N days; fork can't happen before".

**Comment by shea256** [comment]
Awesome, thanks @eordano!

**Comment by jackzampolin** [comment]
This seems to have been acted on. I'm going to go ahead and close this issue. Reopen if it is still a problem.
