### ISSUE TITLE
API doesn't set proper CORS headers

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#350]
In the process of [integrating `0.14.1.2` with the Portal](https://github.com/blockstack/blockstack-portal/issues/278):

When trying to `GET` my payment address with the `Authorization` header set to my `--api-password`, the endpoint fails CORS preflight...it's missing `Access-Control-Allow-Headers` (might be missing other headers too).

<img width="570" alt="screen shot 2017-03-22 at 4 30 26 am" src="https://cloud.githubusercontent.com/assets/597182/24169350/4cfdc874-0eb8-11e7-8ca6-196c42fb91c1.png">

**Comment by jcnelson** [comment]
I just modified the `Access-Control-Allow-Headers` reply to include the `Authorization` header.

**Comment by larrysalibra** [comment]
This fixes it for me. Thank you!
