### ISSUE TITLE
API Authorization type is basic - should probably be bearer

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#351]
The API expects `Authorization: basic <api password>`. The basic authentication method requires a username and password with a specific encoding of a username and password pair. 

Would the `bearer` type would be more appropriate?

See: https://github.com/blockstack/blockstack-core/blob/6c840c0a170bf8fc7686381e2ed9b7edbe487008/blockstack_client/rpc.py#L417

**Comment by jcnelson** [comment]
`bearer` works too.  I used `basic` just to make it easier to implement the parsing logic (i.e. with `bearer`, I know to only expect a JWT).

**Comment by jcnelson** [comment]
This has been fixed in `rc-0.14.2`.  `Authorization` headers now require `bearer` always.
