### ISSUE TITLE
Add an (approximate) expiry time for names

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#353]
@vsund commented on [Mon Jan 16 2017](https://github.com/blockstack/blockstack-cli/issues/189)

I did a `blockstack whois vsund.id` to see when I have to renew my name, but there are only blocks for creation and expiry

An (approximate) expire in time would be helpful to have a better understanding for when a renewal is necessary.

---
Related: https://forum.blockstack.org/t/will-you-remove-users-who-are-name-squatting/469/4

**Comment by larrysalibra** [comment]
This would make it trivial to add them to the explorer as well which is an often requested feature: https://github.com/blockstack/blockstack-explorer/issues/29

**Comment by jackzampolin** [comment]
This would likely need to be implemented in the API no?

**Comment by jackzampolin** [comment]
We have done a considerable amount of work to make expiration more user friendly. Closing this as complete.

**Comment by vsund** [comment]
We currently seem to return an expiration date in the profile requests. So should be up now to the several interfaces (browser, new cli somewhen) to display this.
Also I think we should see the approximate time as an op-top information and that it's up to the interface to evaluate this (although we could provide methods to make this more straight forward).
