### ISSUE TITLE
CLI should have auto completion for a couple of shells (e.g. bash/zsh/etc)

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#354]
@vsund commented on [Tue Jan 10 2017](https://github.com/blockstack/blockstack-cli/issues/185)

Would be really cool to have auto completion for the sub commands of `blockstack-cli` for `bash`, `zsh` and maybe even more.

**Comment by muneeb-ali** [comment]
@vsund we merged the CLI repo with [blockstack-core](http://github.com/blockstack/blockstack-core) and I moved this issue there. Closing this copy of the issue.

**Comment by jackzampolin** [comment]
Related to https://github.com/blockstack/blockstack-core/issues/567 Click has bash completion: http://click.pocoo.org/5/bashcomplete/ Would need to be enabled.

**Comment by jackzampolin** [comment]
This issue is part of a larger CLI redesign topic that needs to be tackled. This should be provided by any CLI framework we choose.

**Comment by jcnelson** [comment]
Closing this issue here.  Please re-open on the CLI repository.

**Comment by vsund** [comment]
@jcnelson Just to make sure, the right repository is still the one owned by you?

**Comment by jcnelson** [comment]
Correct.  Will transfer that repo to blockstack once it's considered stable.
