### ISSUE TITLE
Compartmentalize name ownership

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#355]
@john-light commented on [Wed Nov 30 2016](https://github.com/blockstack/blockstack-cli/issues/177)

1. Add the ability to generate new addresses on the fly and specify what address should be used to register a name.  

2. Make sure the bitcoin change from one name op tx isn't sent to an address that's been used for another name, to ensure compartmentalization.  

One potential solution is to introduce the notion of "accounts", similar to the way the [Mycelium bitcoin wallet](https://github.com/mycelium-com/wallet#features) works. Each account is its own branch of the master HD wallet and is used to create a bunch of derivative addresses that are completely isolated from addresses generated by other accounts. This way change from one account never unintentionally spills over into other accounts.

**Comment by jackzampolin** [comment]
See https://github.com/blockstack/blockstack-core/issues/567

**Comment by john-light** [comment]
Following up on this issue. #567 referenced above was closed. AFAICT account compartmentalization has not been implemented in the Blockstack Browser wallet yet. Please correct me if this is not the case.

**Comment by jackzampolin** [comment]
We switched to a BIP44 compliant HD wallet and moved the wallet from the Core node to the Browser since the last this happened. I'm going to go ahead and close this.
