### ISSUE TITLE
Support for multiple addresses within the blockstack wallet

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#356]
@koinster commented on [Fri Mar 04 2016](https://github.com/blockstack/blockstack-cli/issues/55)

Currently my wallet only allows for one address.  For privacy, this should be implemented as multiple accounts will be owned by one address.

---

@muneeb-ali commented on [Sun Mar 06 2016](https://github.com/blockstack/blockstack-cli/issues/55#issuecomment-192923290)

The functionality for this is kind of already there since we're using a HD wallet. We've artificially limited the number of addresses to just 1 "payment address" and 1 "owner address" for simplicity. We plan to work on enabling multiple addresses.

**Comment by muneeb-ali** [comment]
we merged the CLI repo with [blockstack-core](http://github.com/blockstack/blockstack-core) and I moved this issue there. Closing this copy of the issue.

**Comment by jackzampolin** [comment]
We've done this in the browser.
