### ISSUE TITLE
Finalize identity/profile endpoints

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#359]
Our specs for the [identity API](https://github.com/blockstack/blockstack-core/blob/master/api/README.md) are currently out of sync from the code. 

We also need to iron out the exact/final endpoints.

**Comment by jcnelson** [comment]
CC @larrysalibra @shea256

**Comment by muneeb-ali** [comment]
Closing this issue. I think it will get re-opened when we start on multiplayer storage.
