### ISSUE TITLE
Implement data put and get endpoints

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#360]
We need to finalize the Core API PUT and GET functionality for persistent storage.

**Comment by jcnelson** [comment]
This has stabilized.  Where's the best place to document it?  The API table we have in the api/README.md file isn't expressive enough, since we need to also document how to construct the inputs and how to parse the outputs.

**Comment by muneeb-ali** [comment]
@jcnelson Closing this and starting a new issue for documentation.
