### ISSUE TITLE
Spawning a new API process 

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#361]
Right now we use sys.executable for spawning a new process [in rpc.py](https://github.com/blockstack/blockstack-core/blob/master/blockstack_client/rpc.py#L3508). This works as long as we're invoking it from Python. But other executables, e.g., uWSGI, can also end up calling such functions. 

We could either explicitly check for Python and read the correct path some other way e.g., PYTHONPATH or now spawn a new process.

I had a discussion with @jcnelson about this earlier and he seemed to prefer the "not spawning a new process" route. 

Not including this for v0.14.2.

**Comment by jcnelson** [comment]
Fixed in `rc-0.14.2`
