### ISSUE TITLE
Post instructions for users to upgrade their CLI/Core

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#372]

**Comment by crislar** [comment]
commenting

**Comment by jcnelson** [comment]
Related: #371

**Comment by jcnelson** [comment]
The CLI will now check the local Core node version and ask the user to upgrade.

**Comment by jcnelson** [comment]
The CLI will also auto-migrate the config file and wallet now (it will prompt the user for the wallet password to decrypt and then migrate before doing anything else if it detects an out-of-date wallet).

**Comment by jackzampolin** [comment]
Closing this as complete.
