### ISSUE TITLE
Automatically kill/restart CLI daemon

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#373]
Some users upgrade Blockstack and then hit issues like

```
→ blockstack info
  File "/usr/bin/blockstack", line 58
    print result['result']
               ^
SyntaxError: Missing parentheses in call to 'print'
```

This is because an older CLI daemon is running and the new CLI code is trying to talk to it. Maybe we should include a check for this where we test if the background daemon is running the latest/correct version and if not then we kill that process and start a new one?

**Comment by jcnelson** [comment]
That particular issue is because they're using Python 3 (pip3) by mistake.

But yes, the CLI should check the running version of the API server and request the user to stop it first.

**Comment by jcnelson** [comment]
The CLI now reports whether or not the running API server has the wrong version.  It prompts the user to re-start the API daemon.
