### ISSUE TITLE
Look into the return latency of the price call

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#374]
It seems like the price call takes a while to return. Cryptocracy ran into this issue [in his demo](https://www.youtube.com/watch?v=5QJfqsWTn_Q&feature=youtu.be).

@jcnelson can you kindly post more info on where the current bottleneck is?

**Comment by jcnelson** [comment]
It's in pybitcoin's use of `/dev/random`.  I've sent a PR here: https://github.com/blockstack/pybitcoin/pull/59.

I can also try to remove pybitcoin from Blockstack Core, which is a long-term goal anyway.

**Comment by muneeb-ali** [comment]
OK, cool. Looks like circle-ci tests are the current roadblock. 

How about we try to get the PR into pybitcoin in the short-term and look into getting away from pybitcoin later?

Also, would love to know more about the dependency i.e., how is the available entropy getting looped into the price call path. If you can point to where BitcoinPrivateKey() is being used in the call flow then I can just pick the logic from there -- thanks!

**Comment by jcnelson** [comment]
I've updated the `rc-0.14.2` so we *never* call into pybitcoin, which avoids the problem entirely.  It also gets rid of the need for `rng-tools`.

**Comment by muneeb-ali** [comment]
Awesome! Should we mark this as fixed-in-next-release?

Looks like you switched to keylib in https://github.com/blockstack/blockstack-core/commit/f777a890acd4120787aa0267e4deccf27ed74384 which [uses urandom](https://github.com/blockstack/keylib-py/blob/master/keylib/utils.py). Makes sense.

**Comment by jcnelson** [comment]
Let me try it on a VM that has exhausted `/dev/random` to confirm :)

**Comment by kantai** [comment]
After pushing [this](https://github.com/blockstack/blockstack-core/commit/a930da48e6dd96a3c4bccab2eb0d5a90df21c481) to RC14.2, fake private keys are hardcoded, which speeds up the price calculation a lot.

``$ time curl -s https://core.blockstack.org/v1/prices/names/muneeb.id > /dev/null``
``real	0m1.496s``

**Comment by jcnelson** [comment]
This is all fixed in rc-0.14.2.

**Comment by jackzampolin** [comment]
Closing as fixed! 🎉
