### ISSUE TITLE
Start a new UTXO provider using the insight-api

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#376]
We're (finally!) going to have our own UTXO provider. I'm pretty excited about this because we've seen issues with UTXO providers manifest themselves in all sort of weird ways and having control over the reliability of the UTXO provider will help a lot. 

We decided to use the [insight-api](https://github.com/bitpay/insight-api) for this.

I'm starting this basic issue for just getting our deployment up and running and will start other issues for testing and scaling out.

**Comment by jcnelson** [comment]
This is done and ready at https://utxo.blockstack.org
