### ISSUE TITLE
Scale out our UTXO deployment using a fleet + load balancer 

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#378]
We can use Azure for this for now and can have a setup where we have a few (say 3 nodes) behind a load balancer. We can scale this out further. 

The code for this should probably go in a unix-tools package. Thought @jcnelson?

**Comment by jcnelson** [comment]
There's not much code to this, beyond simply making the VMs, giving them each a big disk, and installing bitcore.  The load-balancer configuration script is already committed; some install-specific tweaks may be necessary (i.e. to select VMs with the right tag).

**Comment by muneeb-ali** [comment]
Cool, so many just instructions + load-balancer script? As in if someone wants to run their own fleet, they should be able to. We might point Microsoft and others to this.

**Comment by jcnelson** [comment]
Spinning up here: http://13.64.150.50:3001

**Comment by jcnelson** [comment]
Can add instructions to the README.md

**Comment by jcnelson** [comment]
Added instructions for load-balancer here: https://github.com/blockstack/unix-tools/tree/master/haproxy

**Comment by jcnelson** [comment]
Live at https://utxo.blockstack.org.  Scripts and instructions are in the `unix-tools` repo.
