### ISSUE TITLE
Figure out API documentation 

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#379]
@jcnelson [commented](https://github.com/blockstack/blockstack-core/issues/360) on new data PUT and GET endpoints:

> This has stabilized. Where's the best place to document it? The API table we have in the api/README.md file isn't expressive enough, since we need to also document how to construct the inputs and how to parse the outputs.

This opens up the general question that where should we document the API. Options are:

1) The [api_v1.md](https://github.com/blockstack/blockstack-core/blob/api/api/api/api_v1.md) file that is rendered by the node once it's deployed e.g., at https://core.blockstack.org. We can make that file more visible. It doesn't look very readable on Github though. 

2) api/README.md. 

The issue with using #2 is that #1 needs to be there regardless. So #2 will become a mirror and realistically out of sync with time.

Tagging: @jcnelson @kantai @larrysalibra @shea256

**Comment by kantai** [comment]
What if we use a script to generate the api/README.md file from the api_v1.md file or vice-versa? It would solve the syncing problem.

**Comment by jackzampolin** [comment]
We generate API docs now. Closing this as complete.
