### ISSUE TITLE
Building single executable for macOS

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#380]
@jcnelson created a `.spec` file for `pyinstaller` https://github.com/blockstack/blockstack-core/commit/6206aaf6819a7fc531a5c1714d750b85255811be (yay!)

I'm on macOS `10.12.4` and can build the executable successfully but encounter the problem below when i try to run it:

```
Vanquish:dist larry$ ./blockstack 
Traceback (most recent call last):
  File "blockstack", line 42, in <module>
    
  File "/private/var/folders/nf/ylp1ctks7c11dfpdly8pv_980000gn/T/pip-build-tnh0a2/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "blockstack_client/__init__.py", line 24, in <module>
    
  File "/private/var/folders/nf/ylp1ctks7c11dfpdly8pv_980000gn/T/pip-build-tnh0a2/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "blockstack_client/app.py", line 27, in <module>
ImportError: No module named keylib
Failed to execute script blockstack
Vanquish:dist larry$
```

this is my modified `blockstack.osx.spec`:

```python
# -*- mode: python -*-

block_cipher = None
# options = [('v', None, 'OPTION'), ('W ignore', None, 'OPTION')]

build_path_osx = '/Users/larry/git/blockstack-core'

bitcoin_data_osx = [
    ('/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/bitcoin/english.txt', 'bitcoin/')
]

fastecdsa_data_osx = [
    ('/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/fastecdsa/_ecdsa.so', 'fastecdsa/'),
    ('/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/fastecdsa/curvemath.so', 'fastecdsa/'),
]

build_path = build_path_osx
datas = bitcoin_data_osx + fastecdsa_data_osx

a = Analysis(['bin/blockstack'],
             pathex=[build_path],
             binaries=[],
             datas=datas,
             hiddenimports=['scrypt', '_scrypt', 'fastecdsa', 'fastecdsa._ecdsa', 'fastecdsa.curvemath', 'blockstack_client.backend.drivers.disk', 'blockstack_client.backend.drivers.s3', 'blockstack_client.backend.drivers.dht', 'blockstack_client.backend.drivers.blockstack_server', 'blockstack_client.backend.drivers.blockstack_resolver', 'blockstack_client.backend.drivers.http'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='blockstack',
          debug=False,
          strip=False,
          upx=True,
          console=True )
```

I'm also a bit concerned (not sure if it's unwarranted) by how the `pyinstaller` docs describe how one file mode functions:

https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#how-the-one-file-program-works

It extracts files to `/tmp` and runs them from there similarly to what we've been doing now.

**Comment by jcnelson** [comment]
> I'm also a bit concerned (not sure if it's unwarranted) by how the pyinstaller docs describe how one file mode functions:
> It extracts files to /tmp and runs them from there similarly to what we've been doing now.

I'd be fine using the one-folder mode if we can get it to work: https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#how-the-one-folder-program-works

Will give this a try today.  It might even be more reliable (I have no realistic way to debug your situation, for example).

**Comment by larrysalibra** [comment]
@jcnelson 
`ImportError: No module named keylib`
Is that an external dependency? 

I'll give it another try tomorrow.

**Comment by kantai** [comment]
The circleCI build for branch osx-single-file-build (https://circleci.com/gh/blockstack/blockstack-core/tree/osx-single-file-build) builds an artifact which is a single executable of Blockstack core for macOS.

I'll eventually want to move to a single folder build, as that will also allow us to include the other executables that we'll eventually want (blockstack-core and the integration tests).

**Comment by muneeb-ali** [comment]
Awesome, @kantai! Closing the issue.
