### ISSUE TITLE
Use Blueprint for integrating search

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#382]
I recently converted the [resolver](https://github.com/blockstack/blockstack-core/blob/api/api/resolver.py) interface to be used as a Blueprint [in the Flask API](https://github.com/blockstack/blockstack-core/blob/api/api/__init__.py).

And now the following (legacy) endpoint work in the Blockstack API:

> /v2/users/muneeb

We need to do the same for the [search subsystem](https://github.com/blockstack/blockstack-core/tree/api/api/search). The most important endpoint to support/test is: 

> /search?query=wenger

Demo at: https://search.blockstack.org/search?query=wenger

Our goal is to retire both resolver.onename.com and search.blockstack.org eventually and
support the (legacy) resolver and search functionality at http://core.blockstack.org

**Comment by kantai** [comment]
Completing with PR #387
