### ISSUE TITLE
Update API tests with resolver and search

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#383]
The API tests are currently out of date. We need to: 

- [x] Remove old tests from [api_tests.py](https://github.com/blockstack/blockstack-core/blob/api/api/tests/api_tests.py) i.e., endpoints that are no longer supported (and were in the older api_v1.py)
- [x] Include and update [resolver_tests.py](https://github.com/blockstack/blockstack-core/blob/api/api/tests/resolver_tests.py)
- [x] Include and update [search_tests.py](https://github.com/blockstack/blockstack-core/blob/api/api/tests/search_tests.py)
- [x] Update the license for the test files.
- [x] Integrate tests for the [(internal) API daemon](https://github.com/blockstack/blockstack-core/blob/api/blockstack_client/rpc.py) 

@jcnelson can you please comment if there is overlap between the integration tests and tests in api/. The motivation here is to have "lightweight" tests in api/tests/ i.e., something we can integrate with CircleCI and test every time there is a commit to api/. No consensus logic or other Core functionality is being tested here; the tests are only for the API interface.

**Comment by muneeb-ali** [comment]
@kantai I'm not putting this on any sprint and we can chat during our weekly meeting about how much time do you think this will likely take and given the estimate we can put it in an appropriate sprint. Looking forward to chatting soon!

**Comment by kantai** [comment]
Updated tests in PR #388 -- still need to update their license files though...

**Comment by kantai** [comment]
As of [ea80960](https://github.com/blockstack/blockstack-core/commit/ea809600600d46a06ad6fddee6dfb20d04e5382a) in api branch, the API unit tests hit all of the GET interfaces of the internal API daemon too. 

I'm not sure it makes sense to test the other interfaces in the unit tests, as those will have side effects, so should be run in a testing environment (which would fit into the integration test framework, I think). I'm closing this for now, can reopen if we want to rethink that.

**Comment by jcnelson** [comment]
Let's wait until these tests are ready, and then @kantai and I will fold them into the integration test framework.  I'm in favor of keeping them as a separate module so we can run them from CircleCI; the integration test framework will simply import them and run them against its Core node.
