### ISSUE TITLE
Test API install instruction and switch core.blockstack.org

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#384]
I wrote up the initial version of the [install instructions for the API](https://github.com/blockstack/blockstack-core/blob/api/docs/install-api.md). 

We need to test them out on a fresh Debian/Ubuntu machines and iron out any issues. The goal of the instructions is to be step-by-step and assume that a user would literally be copy/pasting the instructions and doesn't necessarily have much Linux background.

Earlier, I enabled @kantai's access to a new node on Azure. We'll switch https://core.blockstack.org to that node once he is finished testing the API deployment. Future API versions will be pushed out to the public server managed by @kantai.

**Comment by kantai** [comment]
Should I pull in the changes from rc-0.14.2 to the API branch? 
The setup instructions will be a little different depending on which branch core+client api is running.

**Comment by kantai** [comment]
API install instructions work on the new node, and the API is deployed there. We should be able to switch core.blockstack.org over.

**Comment by muneeb-ali** [comment]
@kantai I just switched core.blockstack.org to your server. You'll need a new security certificate from Let's Encrypt. Feel free to close the issue when that's done!
