### ISSUE TITLE
Blockstack roadmap for upcoming releases

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#389]
I had a discussion with @jcnelson & @kantai and we came up with the following plan: 

- We'll work on the 0.14.2 release (end-April) as listed on [this milestone](https://github.com/blockstack/blockstack-core/milestone/6).
- After 0.14.2, Jude will fork master/stable for a consensus-breaking 0.16 release
- Muneeb and Aaron will fork master/stable for a UX-breaking 0.15 release
- Aaron will be the 0.15 release manager and will maintain the stable release over the summer until we switch to 0.16. 

All of us will, of course, start working on 0.16 later on and the plan is more about how the work will be split initially, how we'll deal with maintaining the stable release, and how we'll introduce consensus-breaking features.

Please leave your comments. @kantai and @jcnelson let me know if I missed something or if the plan sounds good. Excited about the upcoming releases!

**Comment by jackzampolin** [comment]
Closing this as we just released 0.17 :P
