### ISSUE TITLE
Decide on API enhancements going into 0.15

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#392]
@larrysalibra gave this great feedback on our API on this forum post:

https://forum.blockstack.org/t/blockstack-core-api-feedback/854

We should probably figure out action items from that list and create Github issues. 

Once we have converted API feedback into actionable Github issues, we can close this discussion thread.

**Comment by larrysalibra** [comment]
@kantai can you post links to the action item issues from that discussion here? (I came here to check on the status of programmatically consumable error messages which was one of the items i mentioned in the feedback)

**Comment by kantai** [comment]
Sure -- I've created 4 issues from that discussion.

#420 for improving configuration
#421 for the wallet integration 
#422 for improving error responses
#423 on deciding on a versioning policy

I haven't looked at these API improvements for v0.15 yet, but will move to that later this week.

The issues related to testing and deploying on macOS should be in #380 and #411

**Comment by muneeb-ali** [comment]
Closing this since Aaron started individual issues.
