### ISSUE TITLE
Enable automatic search re-indexing on core.blockstack.org

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#394]
I had this [enabled earlier](https://github.com/blockstack/blockstack-core/issues/307) and in my experience, 6 hours was as fast as we could go (a single run was taking ~3 hours or more). 

This was also for a dedicated search server (https://search.blockstack.org). I'm thinking that for core.blockstack.org maybe we can have a 12 hour re-indexing. 

I'll let @kantai decide on what makes sense. 

With this enabled we'll have both (legacy) resolver and (legacy) search running with our public Core node!

**Comment by muneeb-ali** [comment]
@kantai this can be pushed to next sprint if needed (especially given the new macOS testing work)

**Comment by kantai** [comment]
Automatic search index enabled on core (every 12 hours) -- if we want to improve the time on this, I think we'd need to re-architect the search indexer a little bit, but for now, I'm marking this as closed.
