### ISSUE TITLE
macOS testing for 0.14.2

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#399]
We need to heavily test our macOS build (for 0.14.2). I have an iMac and can help with testing towards the end of this week but we probably need to figure out a more automated process where we boot new machines and also test different versions of the OS. 

We can buy licenses to macOS VMs if needed.

Assigning @kantai so he can take the lead on setting up the test environment and tagging @jcnelson and @larrysalibra.

**Comment by kantai** [comment]
Okay, I can work on this, but I don't have access to a Mac at the moment, and OSX doesn't play nicely (legally) in a VM, even with a license I believe.

**Comment by lacabra** [comment]
Hi there, I have a Mac OSX and could help on this with a little bit of guidance, if that would be of help. Let me know.

**Comment by muneeb-ali** [comment]
@lacabra we'd love any help on OS X testing! Right now we're focusing on testing the [0.14.3 branch](https://github.com/blockstack/blockstack-core/tree/rc-0.14.3). Can you kindly start an issue for OS X testing instruction and we'll take it from there? 

Closing this issue as I'm closing the 14.2 release milestone.
