### ISSUE TITLE
zonefiles directory tree is enormous

### ISSUE THREAD

**Issue by dominictarr** [blockstack/blockstack-core#403]
the way that the zonefiles are stored, with deep directory trees actually takes up a massive amount of file system space. If I do `du -sh ~/.blockstack-server/zonefiles` I get 5gb!
how did that come out of a 70 mb fast_sync file?

well, the answer is that files always take at least 1 block, which is 4kb on my machine.
that means that a lot of directories with only one file can really add up. for example, the disk usage of the first zonefile is 4k
```
du -h ~/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03/8c/e0/67/42/47/db/96/1a/88/d4/5e/cb/82/zonefile.txt 
4.0K    /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03/8c/e0/67/42/47/db/96/1a/88/d4/5e/cb/82/zonefile.txt
```
although it's only one line long (101 bytes)

however, if we `du` the lowest lonely directory

```
 du -h ~/.blockstack-server/zonefiles/00/02/                                                       
8.0K    /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03/8c/e0/67/42/47/db/96/1a/88/d4/5e/cb/82
12K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03/8c/e0/67/42/47/db/96/1a/88/d4/5e/cb
16K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03/8c/e0/67/42/47/db/96/1a/88/d4/5e
20K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03/8c/e0/67/42/47/db/96/1a/88/d4
24K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03/8c/e0/67/42/47/db/96/1a/88
28K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03/8c/e0/67/42/47/db/96/1a
32K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03/8c/e0/67/42/47/db/96
36K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03/8c/e0/67/42/47/db
40K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03/8c/e0/67/42/47
44K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03/8c/e0/67/42
48K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03/8c/e0/67
52K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03/8c/e0
56K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03/8c
60K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79/03
64K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20/79
68K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc/20
72K     /home/dominic/.blockstack-server/zonefiles/00/02/c6/fc
76K     /home/dominic/.blockstack-server/zonefiles/00/02/c6
80K     /home/dominic/.blockstack-server/zonefiles/00/02/
```
that expands to 80k! that is 20 times the size of one file. this also puts each zonefile at the end of a linked list on your file system. It is a good idea to not have directories with thousands and thousands of files, but many directories with only a single file is also bad. If this pattern was fixed at 2 or 3 levels, that would probably be fine. Another option would be an leveldb or similar, which would avoid the overhead of a whole block per zonefile.

**Comment by jcnelson** [comment]
Hey @dominictarr, thanks for bringing this up!  We cut down the number of directories per zone file to 2 levels in the `rc-0.14.2` release.  Another problem the previous behavior introduced was that small VMs in cloud hosts would run out of inodes this way.

The disk usage in `rc-0.14.2` currently stands at:
```
$ du -sh ~/.blockstack-server/zonefiles/
374M	/home/blockstack/.blockstack-server/zonefiles/
```

**Comment by dominictarr** [comment]
@jcnelson oh yeah, that is how I encountered this problem. closing.
