### ISSUE TITLE
Run core api integration tests on macOS

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#411]
Is it possible for us to set up core integrations tests so that they automatically run on macOS in addition to linux? 

It would save a lot of time if we could catch issues like https://github.com/blockstack/blockstack-core/issues/410 earlier than the packaging and shipping a version stage of a sprint.

My goal is to make sure that the API calls work as expected using the versions of dependencies that we ship using the live external services that core defaults to.

**Comment by kantai** [comment]
The API unit tests should work on macOS, in fact, I used them this week for testing. We could merge those into 0.14.2 from the API branch (Jude and Muneeb probably have an opinion on that) and then they could be run pretty easily.

I think right now though the biggest challenge with macOS testing and deployment is that we don't have a "baseline" mac. Ideally we'd have a mechanism that allowed us to (1) build the portal app on some kind of build box given X, Y, Z commits on portal, virtualchain, and core, and then (2) a separate box or VM which has no devtools whatsoever installed, on which we could deploy the app, start it up, and then fire the test suite off.

I could work on getting such a process setup on the mac mini in the office this coming week.

**Comment by larrysalibra** [comment]
That would be great @kantai! 

Ideally, we could have multiple versions of the machine with no dev tools: 

1. Current macOS release
2. Latest developer/public beta (if any) so that we get a heads up of any breakage that may occur with future operating system updates. 
3. Latest version of previous major release (Example: Once 10.13 comes out in the fall, this version would be the last update to 10.12.x)


It would be great to use CircleCI - however they are very slow to update their machine images and install devtools by default. (It took them ~9-10 months to come out with a Sierra image)
---

We have macOS support on our circleci account and it looks like they've released Sierra support. https://discuss.circleci.com/t/announcing-xcode-8-3-support-and-opt-in-upgrades-for-macos/11528

**Comment by muneeb-ali** [comment]
+1 on merging PI units tests. 

I think getting rid of various dependencies (the work done last week) was the most important step towards a stable macOS release. 

Once that is fully ironed out, we can look into classifying typical macOS environments. I agree with Larry on current vs. latest. I started a similar setup for [Core install scripts](https://github.com/blockstack/blockstack-core/tree/master/images/scripts). 

@kantai wrote:
> I could work on getting such a process setup on the mac mini in the office this coming week.

I think getting the macOS release stable is top priority and we can push back v0.15 stuff. We can chat more about this on Mon. I'm also freeing up from the thesis work and can have another pair of eyes (plus another machine in the office) to test it out.

**Comment by kantai** [comment]
Great. I agree on the priority of stabilizing the macOS release. And getting a circleCI build running for macOS would be a huge step. I think I need to be added to the access list for blockstack/blockstack-core to start on that.

**Comment by shea256** [comment]
@kantai You should be able to access the CircleCI project for Blockstack Core. Here's the link: https://circleci.com/gh/blockstack/blockstack-core. Let me know if you're still unable to get it to work.

**Comment by kantai** [comment]
As of PR #417, 0.14.2 is running (and passing!) CircleCI tests on OSX using the core service API with default configuration settings.

**Comment by jackzampolin** [comment]
Closing this as complete and/or unnecessary since we moved core out of the browser.
