### ISSUE TITLE
Create transaction broadcast service

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#418]
Registering Blockstack names requires broadcasting a number of bitcoin transactions and waiting between them. Transactions need to be broadcast within certain intervals, otherwise the name registration will fail.

This is fine when a registration is performed on a server which is always running and connected to the network.

It poses a problem for registrations conducted by end users using Blockstack Portal because most of them use machines that are not always on and many use laptops which can have limited power and intermittent network connectivity. 

Name registration will fail if the user is unable to broadcast the transactions at the right time.

This can happen in several scenarios:
1. The user turns her computer off after submitting the registration and doesn't turn it back on and restart Blockstack within a certain window of time (~12 hours)
2. The user's computer loses network connectivity and is unable to broadcast the transactions at the right time.

One way to solve this is to create an optional service where a user can generate transactions in advance and send them to a trusted 3rd broadcast service that queues them up and sends them out at the appropriate time.

We'd make this on by default in Blockstack for Mac and likely other end user platforms. Advanced users should be able to disable this feature in which their local machine would be responsible for broadcasting the transactions at the proper time. They should also be able to point it to alternative deployments of the service.

There should be two API endpoints: 1 for submitting the transactions and another for checking their status in the broadcast queue.

Tagging @muneeb-ali @shea256 @kantai @jcnelson for additional input.

**Comment by muneeb-ali** [comment]
Thanks, @larrysalibra for starting the issue and giving details. 

We had a lunch discussion around this and are currently thinking of accepting only name_update and name_transfer in the broadcast service. This way the service cannot censor name registrations by front-running users. 

We can also announce name_preorder and name_register transactions within 2-3 blocks of each other. So that's the time that the user will need to keep the laptop on for and there can be a status bar that shows progress.

**Comment by jackzampolin** [comment]
Moving this discussion over to the browser repo: https://github.com/blockstack/blockstack-browser/issues/1163
