### ISSUE TITLE
Wallet integration with Portal

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#421]
* Supporting wallet entirely on portal *

To support using portal's wallet for both identity and coin storage, core needs to support an API endpoint for generating transaction templates that can be signed and sent by portal.
See issue #363 

* Supporting core wallet via the API *

If we move forward with using the core wallet instead of the portal wallet, we will need an API that lets users work with wallets. They need to be able to create, delete, backup, and restore wallets.

Importantly, these methods should require the wallet password as a parameter _not_ the API key.

Currently, the API server requires the wallet password on startup. The API server should be able to start without yet knowing the wallet password, and fail on endpoints that require the password if it isn't entered yet.

**Comment by muneeb-ali** [comment]
I think we've already made a bunch of progress on this. Would love to see an update.

**Comment by kantai** [comment]
The core wallet is no longer used for bitcoin transactions or blockstack operations from the browser (the local core node is still required currently, but that's a different issue). Closing this issue.
