### ISSUE TITLE
Decide on versioning policy for API endpoints

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#423]
The Blockstack Core API currently uses a "coarse" versioning system where version 1 is placed in the sub-directory `/v1`. The thinking is that once the API is stable, we will commit to supporting `/v1/`.

One of the biggest frustrations as the user of an API is refactoring your code for changes to the API. Along the same lines, one of the biggest frustrations for the developer of the API is being unable to change it for fear of breaking backward compatibility.

There's two options here:

1. Continue with coarse versioning. The problem here is that as developers come to rely on not just the endpoint existing, but returning a specific JSON schema, slight changes in the API will need to bump the version number.

2. Move to a more finely grained approach. Allow apps to request the version of the API for which they were designed and use a compatibility layer to translate.

My feeling is that option (1) will devolve into option (2) over time, leaving behind a lot of ad hoc translation code. If we commit to option (2), we may end up with an easier codebase to manage over time.

**Comment by muneeb-ali** [comment]
References this forum discussion as well:

https://forum.blockstack.org/t/blockstack-core-api-feedback/854/11

**Comment by larrysalibra** [comment]
Must read article on API versioning: https://stripe.com/blog/api-versioning
Hope we can adopt some of the practices they discuss in our versioning approach.

**Comment by jcnelson** [comment]
I think the convention we've begun using is a simple counter (`v1`, `v2`, `v3`, etc.) that gets incremented whenever there's a breaking change.  This is already implemented and tested with `/v2/prices` for example.

**Comment by jcnelson** [comment]
Closing as stale.  We're doing versioning as `v1`, `v2`, etc.
