### ISSUE TITLE
Withdrawing more bitcoin the available balance error

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#425]
POST `{"address":"1Mp5vKwCbekeWetMHLKDD2fDLJzw4vKxiQ","min_confs":0,"amount":0.9}` to `/v1/wallet/balance` results in a `500` error (wallet is almost empty)

I'd expected something in the 4xx range since this is a client error - the client is trying to withdraw more than the available balance. Probably 400 bad request?

**Comment by jcnelson** [comment]
Just pushed a possible fix.  You'll get 400 on bad input, and 503 if the Core node fails to send the transaction.

**Comment by larrysalibra** [comment]
thanks
