### ISSUE TITLE
Failure when installing Blockstack CLI on Windows Subsystem for Linux. 

### ISSUE THREAD

**Issue by thehenrytsai** [blockstack/blockstack-core#428]
Has anyone successfully installed Blockstack CLI on Windows Subsystem for Linux? I got to the part where I run "sudo pip install blockstack" and it blows up with:

Installing collected packages: fastecdsa, basicrpc, boto, urllib3, dropbox, blockstack
  Running setup.py install for fastecdsa ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-iVREOX/fastecdsa/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Db4pZS-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/fastecdsa
    copying fastecdsa/__init__.py -> build/lib.linux-x86_64-2.7/fastecdsa
    copying fastecdsa/curve.py -> build/lib.linux-x86_64-2.7/fastecdsa
    copying fastecdsa/ecdsa.py -> build/lib.linux-x86_64-2.7/fastecdsa
    copying fastecdsa/keys.py -> build/lib.linux-x86_64-2.7/fastecdsa
    copying fastecdsa/point.py -> build/lib.linux-x86_64-2.7/fastecdsa
    copying fastecdsa/test.py -> build/lib.linux-x86_64-2.7/fastecdsa
    copying fastecdsa/util.py -> build/lib.linux-x86_64-2.7/fastecdsa
    running build_ext
    building 'fastecdsa.curvemath' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc/ -I/usr/include/python2.7 -c src/curveMath.c -o build/temp.linux-x86_64-2.7/src/curveMath.o -O2
    In file included from src/curveMath.c:1:0:
    src/curveMath.h:6:17: fatal error: gmp.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

   ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-iVREOX/fastecdsa/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Db4pZS-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-iVREOX/fastecdsa/

**Comment by kantai** [comment]
It looks like it's failing to find libgmp -- can you try installing libgmp3-dev?

```
$ sudo apt install libgmp3-dev
```

**Comment by thehenrytsai** [comment]
You are right Aaron, I got it working by running "apt-get install  libgmp3-dev" to install libgmp3-dev first.
