### ISSUE TITLE
Search bug on api.blockstack.com

### ISSUE THREAD

**Issue by lacabra** [blockstack/blockstack-core#431]
There seems to be something wrong with the way searches are performed through the api.blockstack.com (which the blockstack-portal relies on to do search for people).

Take for example my username I registered through onename.com: victoris.id. It certainly exists if you look it up directly through https://api.blockstack.com/v1/users/victoris, but it doesn’t show up if you do a search https://api.blockstack.com/v1/search?query=victoris or any other search with substrings like "victori", "victor",… (other results are returned, but not this particular one).

**Comment by muneeb-ali** [comment]
Thanks for reporting! I'll take a look.

**Comment by muneeb-ali** [comment]
Just a heads up that I'll likely get to this next week. Let me know if it's urgent and I can see what I can do, thanks!

**Comment by lacabra** [comment]
Not urgent, no worries. Thanks for checking in :) 👍 Let me know how I can help.

**Comment by jackzampolin** [comment]
We don't maintain this API anymore. If you are looking for profile lookup see the documentation at `core.blockstack.org`
