### ISSUE TITLE
[Gaia] Add GitHub as storage provider

### ISSUE THREAD

**Issue by vsund** [blockstack/blockstack-core#432]
Adding GitHub as storage provider for i.e. [profiles](https://gist.github.com/vsund/faf5a085fcf441b179d19593cd2e6812). Bigger files wouldn't be that convenient here I guess.

---
moved from [the old repository](https://github.com/blockstack/storage-drivers/issues/67) to this one, as storage provider got in-cooperated here

**Comment by pstan26** [comment]
Like this one.

**Comment by jackzampolin** [comment]
Closing in favor of https://github.com/blockstack/gaia/issues/85
