### ISSUE TITLE
[Gaia] Add private servers as storage provider (WebDav, SFTP, RemoteStorage)

### ISSUE THREAD

**Issue by vsund** [blockstack/blockstack-core#433]
Would be cool to use own generic servers as storage provider (pro: I know who is responsible for broken things, how much space I have; con: I am responsible).

Maybe with using current standards as a base (thinking of WebDav), it's even possible to be compatible with all the WebDav servers out there. SFTP is an option too.

Alternatively https://remotestorage.io would be a thing. [Unhosted apps](https://unhosted.org/) use this for adding own application storage.
([Demo](https://litewrite.net/) top right corner)

---
moved from [the old repository](https://github.com/blockstack/storage-drivers/issues/68) to this one, as storage provider got in-cooperated here

**Comment by michielbdejong** [comment]
Yes! There is a library called remotestorage.js which actually supports not only the remoteStorage protocol, but also GoogleDrive and Dropbox. And it works in any browser (not just in the blockchain browser), so app developers can publish their app both via both DNS and BNS, and have a bigger audience as long as their app just needs the per-user storage.

**Comment by jackzampolin** [comment]
Closing this in favor of: https://github.com/blockstack/gaia/issues/86
