### ISSUE TITLE
Switch from scrypt to cryptography's Scrypt back-end

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#444]
In the upcoming release, we use `scrypt` for key-lengthening in the wallet implementation.  We might be able to get away with using the `scrypt` backend in the cryptography.io package ([docs](https://cryptography.io/en/latest/hazmat/backends/interfaces/#cryptography.hazmat.backends.interfaces.ScryptBackend.derive_scrypt)).  This would be nice since it cuts down our dependency graph and it makes the Mac OS X build easier to come by.

Thoughts @kantai?

**Comment by kantai** [comment]
This was my original thought when I was trying to get `scrypt` distribution to work for OSX.

There's two downsides --

First, the `scrypt` backend in Cryptography only provides a KDF -- while we are using the simple `scrypt` encryption/decryption functions. So we'd have to re-implement [scryptenc.c:scryptenc_buf](https://github.com/Tarsnap/scrypt/blob/master/lib/scryptenc/scryptenc.c#L310) and the decryption function. Not so bad though.

The second, and bigger downside, is that `scrypt` in Cryptography requires linking with OpenSSL >= 1.1. This is fine for the OSX distribution, as the mac wheels in pip are statically linked with the latest OpenSSL. This is, however, problematic on many Linux distributions. In Ubuntu, for example, you'd need an unofficial PPA (even the next release 17.10 only includes OpenSSL 1.0.2g) or to build it yourself.

I think that the second problem outweighs the potential benefits of moving to Cryptography.

**Comment by jcnelson** [comment]
Ah, good points.   Let's keep `scrypt` for now, then :)  Better to have one build that works everywhere.
