### ISSUE TITLE
Ways to decrease name costs

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#452]
This is a list of ways we can decrease name cost both in terms of bitcoin and time:

1. don't spend dust utxos (see #453)
2. remove `NAME_TRANSFER` step (require portal provide the owner_address private key)
3. remove multisig from core
4. pass browser bitcoin wallet private key
5. `NAME_TRANSFER` & `NAME_REGISTER` should take a value hash (removing need for `NAME_UPDATE` when performing these transactions.)

tagging @jcnelson @kantai @muneeb-ali @shea256

**Comment by larrysalibra** [comment]
@jcnelson are 1, 2 and 4 feasible in this sprint? (3 is irrelevant if we use the browser wallet and 5 is consensus breaking, right?)

**Comment by jcnelson** [comment]
I think 1, 2, and 4 are feasible this sprint.

**Comment by shea256** [comment]
I love 1,2 and 4 for this sprint. 3 whenever we get to it. 5 is interesting but I might have something even better. Will share in a bit.

**Comment by jcnelson** [comment]
3 gets added for free by way of 2 and 4.  Browser passes a single-sig payment and owner key, and Core uses them to generate p2pkh scripts.

**Comment by jcnelson** [comment]
Core (rc-0.14.2-portal) now supports 1, 2, and 4.

**Comment by jackzampolin** [comment]
We might want to revive this discussion in light of the recent BTC price increase.

**Comment by jcnelson** [comment]
This will be addressed in the STACKS blockchain, which will move the bulk of Blockstack's transactions off-chain.

**Comment by larrysalibra** [comment]
Something else that belongs on this list is shipping subdomains. Not having a name is a blocker to multi reader storage apps & asking people to pay a lot for them will make growth impossible for multi reader apps on our platform

**Comment by jcnelson** [comment]
I think we've addressed this sufficiently with our new subdomain-based onboarding flow.  Users don't need to spend Bitcoin, and we can do ~130 names per NAME_UPDATE on `id.blockstack`.  Going to go ahead and close this, since this is probably as far as we can take making names cheap until we have a full-fledged blockchain.
