### ISSUE TITLE
Don't spend dust UTXOs

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#453]
It doesn't make sense to spend an unspent transaction output (UTXO) when the value of the output is less than the fee. It makes sense to spend the largest UTXOs first and filter out small ones.

Tagging @jcnelson

**Comment by jcnelson** [comment]
This has been merged to `rc-0.14.2`.  Our integration tests confirm that we select UTXOs in order from largest-value to smallest-value to avoid spending dust.
