### ISSUE TITLE
Get rid of advanced mode in CLI

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#457]
Every time I go to use a command that's listed in CLI help, it fails because I apparently don't have advanced mode turned. I really can't think of a situation where someone is using the CLI and not "advanced". Can we remove advanced mode?

**Comment by kantai** [comment]
Advanced mode is now gone in 0.14.3 as of #474

**Comment by larrysalibra** [comment]
This makes me so happy :-D thanks @kantai
