### ISSUE TITLE
Calls to logger should use Error instead of Debug

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#462]
Right now, almost all of the Python logger calls use `debug()`, even for errors. Because of this, unless `--debug` is set, we won't get useful logfiles in error cases. However, with `--debug` on, the logfiles generated by Browser+Core are ~100mb a day. 

GZipping helps a lot (reduces this to roughly 5MB a day), so rotating + gzipping is another option.

**Comment by jackzampolin** [comment]
Sounds like this is still an issue.

**Comment by jackzampolin** [comment]
I'm happy to take a crack at this. Looks like the logger we use is [defined in `virtualchain`](https://github.com/blockstack/virtualchain/blob/master/virtualchain/lib/config.py#L81). 

Also just to clarify, I'm looking for `log.debug()` calls anywhere in the code? Are there some folders or files I should start with? I would imagine opening a couple of PRs (one for each area of the code) would be the right call here.

**Comment by jcnelson** [comment]
This should be the case upstream (`develop`) already for errors.  Closing as completed.
