### ISSUE TITLE
Price lookup with invalid characters returns unclear error

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#464]
A user tried `blockstack price test123*.id` and got a response that doesn't make sense. I'd expect to be told that the name I'm trying is invalid or something to that effect.

This is related to #422 and I suggest we fix it along with improved error responses across the board.

The bug report and output can be found in this forum post: https://forum.blockstack.org/t/special-characters-alphanumeric/1212?u=larry

**Comment by kantai** [comment]
Actually, the error outputted there was due to a bug in rc-0.14.2 at the time, which has since been fixed.

Now -- if you use the command line:

```
$ blockstack price test123*.id
{
    "error": "Neither a valid name or namespace:\n   * The name specified is invalid. Names may only contain lowercase alphanumeric characters and underscores.\n   * The namespace specified is invalid.  Namespace IDs cannot have \".\" or \"+\" in them."
}
```

**Comment by kantai** [comment]
Anyways, since this error output is now okay, I'm closing this issue. The issue with errors in general is still open (and a bigger task overall).

**Comment by larrysalibra** [comment]
Thank you @kantai
