### ISSUE TITLE
Release notes for 0.14.2 and notes/requirements for 0.14.3

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#467]
I had a discussion with @jcnelson and @kantai and we'll be treating release notes as requirements for upcoming releases. The idea is to capture everything that goes into a release (things that are dependent on each other for example) and the sign off on the requirements/target. 

We're also planning to increase the frequency of releases. 

As a next step, we need to: 

[ ] update our Github with the [release notes of 0.14.2](https://github.com/blockstack/blockstack-core/tree/master/release_notes)
[ ] start a draft of 0.14.3 

I'll let @jcnelson comment and take the lead on this.

**Comment by jcnelson** [comment]
0.14.2 release notes: https://github.com/blockstack/blockstack-core/blob/master/release_notes/changelog-0.14.2.md

**Comment by jcnelson** [comment]
0.14.3 anticipated release notes: https://github.com/blockstack/blockstack-core/blob/rc-0.14.3/release_notes/changelog-0.14.3.md

cc @kantai to see what he thinks

**Comment by muneeb-ali** [comment]
@kantai are we trying for "Initial subdomain support" in this release? What was the consensus after the weekly meeting? 

@jcnelson "Multi-player Storage" seems a bit ambitious but it seems like you're moving on to testing for it soon?

Also, to confirm this is scheduled for Mon July 17th? Sorry, I missed the meeting earlier in the week, so catching up.

**Comment by kantai** [comment]
The consensus after the weekly meeting was to work on low-confirmation
registrations and cleaning up the API documentation first, and then move on
to subdomain support (which I think was even moved out of the sprint) after
finishing that.

**Comment by muneeb-ali** [comment]
Confirmed that subdomains will not be in the 0.14.3 release now.

**Comment by jackzampolin** [comment]
Closing this as complete.
