### ISSUE TITLE
macOS: error when setting up blockstack-core integration tests 

### ISSUE THREAD

**Issue by jay-hwang** [blockstack/blockstack-core#470]
Following the README for [blockstack-core/integration_tests](https://github.com/blockstack/blockstack-core/tree/master/integration_tests#blockstack-integration-tests)

I setup the virtualenv, activate it and clone 'blockstack-core' repo. However when I run :

`(blockstack-testing) blockstack-core$ ./setup.py install`,

it exits with this error saying it can't find openssl file, but I have openssl installed. Here's the error msg: 

`scrypt-1.2.0/libcperciva/crypto/crypto_aes.c:6:10: fatal error: 'openssl/aes.h' file not found
#include <openssl/aes.h>
         ^
1 error generated.
error: Setup script exited with error: command 'cc' failed with exit status 1`

**Comment by kantai** [comment]
Hi Jay, sorry to see that you're having difficulty getting the integration tests set up on macOS. 
When building your own virtualenv on macOS, you'll need to `brew install openssl`

**Comment by jay-hwang** [comment]
Hey Aaron, thanks for the response! Jude told me the same thing earlier, to no avail.

`brew install openssl`  gives me `Warning: openssl 1.0.2l is already installed`

**Comment by kantai** [comment]
Let's trying reinstalling py-scrypt from my repo (scrypt is packaged strangely on macOS, so I've tried to fix it up over time)

```
(blockstack-testing) $ pip install git+https://github.com/kantai/py-scrypt.git --upgrade
```

**Comment by jay-hwang** [comment]
That didn't work either unfortunately /: 
It gave me this:

`Collecting git+https://github.com/kantai/py-scrypt.git
  Cloning https://github.com/kantai/py-scrypt.git to /private/var/folders/dq/c2_1kmrn2tbg0zmmvlscs5240000gn/T/pip-rqFthU-build
Installing collected packages: scrypt
  Running setup.py install for scrypt ... error
    Complete output from command /Users/jayhwang/.sandbox/blockstack/blockstack-testing/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/dq/c2_1kmrn2tbg0zmmvlscs5240000gn/T/pip-rqFthU-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/dq/c2_1kmrn2tbg0zmmvlscs5240000gn/T/pip-B18K2K-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/jayhwang/.sandbox/blockstack/blockstack-testing/include/site/python2.7/scrypt:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.12-intel-2.7
    copying scrypt.py -> build/lib.macosx-10.12-intel-2.7
    running build_ext
    building '_scrypt' extension
    creating build/temp.macosx-10.12-intel-2.7
    creating build/temp.macosx-10.12-intel-2.7/src
    creating build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0
    creating build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/lib
    creating build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/lib/crypto
    creating build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/lib/scryptenc
    creating build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/lib/util
    creating build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/libcperciva
    creating build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/libcperciva/alg
    creating build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/libcperciva/crypto
    creating build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/libcperciva/util
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -Iscrypt-1.2.0 -Iscrypt-1.2.0/lib -Iscrypt-1.2.0/lib/scryptenc -Iscrypt-1.2.0/lib/crypto -Iscrypt-1.2.0/lib/util -Iscrypt-1.2.0/libcperciva/cpusupport -Iscrypt-1.2.0/libcperciva/alg -Iscrypt-1.2.0/libcperciva/util -Iscrypt-1.2.0/libcperciva/crypto -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/scrypt.c -o build/temp.macosx-10.12-intel-2.7/src/scrypt.o
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -Iscrypt-1.2.0 -Iscrypt-1.2.0/lib -Iscrypt-1.2.0/lib/scryptenc -Iscrypt-1.2.0/lib/crypto -Iscrypt-1.2.0/lib/util -Iscrypt-1.2.0/libcperciva/cpusupport -Iscrypt-1.2.0/libcperciva/alg -Iscrypt-1.2.0/libcperciva/util -Iscrypt-1.2.0/libcperciva/crypto -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c scrypt-1.2.0/lib/crypto/crypto_scrypt_smix_sse2.c -o build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/lib/crypto/crypto_scrypt_smix_sse2.o
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -Iscrypt-1.2.0 -Iscrypt-1.2.0/lib -Iscrypt-1.2.0/lib/scryptenc -Iscrypt-1.2.0/lib/crypto -Iscrypt-1.2.0/lib/util -Iscrypt-1.2.0/libcperciva/cpusupport -Iscrypt-1.2.0/libcperciva/alg -Iscrypt-1.2.0/libcperciva/util -Iscrypt-1.2.0/libcperciva/crypto -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c scrypt-1.2.0/lib/crypto/crypto_scrypt_smix.c -o build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/lib/crypto/crypto_scrypt_smix.o
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -Iscrypt-1.2.0 -Iscrypt-1.2.0/lib -Iscrypt-1.2.0/lib/scryptenc -Iscrypt-1.2.0/lib/crypto -Iscrypt-1.2.0/lib/util -Iscrypt-1.2.0/libcperciva/cpusupport -Iscrypt-1.2.0/libcperciva/alg -Iscrypt-1.2.0/libcperciva/util -Iscrypt-1.2.0/libcperciva/crypto -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c scrypt-1.2.0/lib/crypto/crypto_scrypt.c -o build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/lib/crypto/crypto_scrypt.o
    scrypt-1.2.0/lib/crypto/crypto_scrypt.c:115:31: warning: implicit conversion loses integer precision: 'unsigned long long' to 'unsigned long' [-Wshorten-64-to-32]
            if ((V0 = malloc(128 * r * N + 63)) == NULL)
                      ~~~~~~ ~~~~~~~~~~~~^~~~
    1 warning generated.
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -Iscrypt-1.2.0 -Iscrypt-1.2.0/lib -Iscrypt-1.2.0/lib/scryptenc -Iscrypt-1.2.0/lib/crypto -Iscrypt-1.2.0/lib/util -Iscrypt-1.2.0/libcperciva/cpusupport -Iscrypt-1.2.0/libcperciva/alg -Iscrypt-1.2.0/libcperciva/util -Iscrypt-1.2.0/libcperciva/crypto -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c scrypt-1.2.0/lib/scryptenc/scryptenc.c -o build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/lib/scryptenc/scryptenc.o
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -Iscrypt-1.2.0 -Iscrypt-1.2.0/lib -Iscrypt-1.2.0/lib/scryptenc -Iscrypt-1.2.0/lib/crypto -Iscrypt-1.2.0/lib/util -Iscrypt-1.2.0/libcperciva/cpusupport -Iscrypt-1.2.0/libcperciva/alg -Iscrypt-1.2.0/libcperciva/util -Iscrypt-1.2.0/libcperciva/crypto -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c scrypt-1.2.0/lib/scryptenc/scryptenc_cpuperf.c -o build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/lib/scryptenc/scryptenc_cpuperf.o
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -Iscrypt-1.2.0 -Iscrypt-1.2.0/lib -Iscrypt-1.2.0/lib/scryptenc -Iscrypt-1.2.0/lib/crypto -Iscrypt-1.2.0/lib/util -Iscrypt-1.2.0/libcperciva/cpusupport -Iscrypt-1.2.0/libcperciva/alg -Iscrypt-1.2.0/libcperciva/util -Iscrypt-1.2.0/libcperciva/crypto -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c scrypt-1.2.0/lib/util/memlimit.c -o build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/lib/util/memlimit.o
    scrypt-1.2.0/lib/util/memlimit.c:194:15: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
                    *memlimit = memrlimit;
                              ~ ^~~~~~~~~
    scrypt-1.2.0/lib/util/memlimit.c:240:15: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
                    *memlimit = totalmem;
                              ~ ^~~~~~~~
    2 warnings generated.
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -Iscrypt-1.2.0 -Iscrypt-1.2.0/lib -Iscrypt-1.2.0/lib/scryptenc -Iscrypt-1.2.0/lib/crypto -Iscrypt-1.2.0/lib/util -Iscrypt-1.2.0/libcperciva/cpusupport -Iscrypt-1.2.0/libcperciva/alg -Iscrypt-1.2.0/libcperciva/util -Iscrypt-1.2.0/libcperciva/crypto -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c scrypt-1.2.0/libcperciva/alg/sha256.c -o build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/libcperciva/alg/sha256.o
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -Iscrypt-1.2.0 -Iscrypt-1.2.0/lib -Iscrypt-1.2.0/lib/scryptenc -Iscrypt-1.2.0/lib/crypto -Iscrypt-1.2.0/lib/util -Iscrypt-1.2.0/libcperciva/cpusupport -Iscrypt-1.2.0/libcperciva/alg -Iscrypt-1.2.0/libcperciva/util -Iscrypt-1.2.0/libcperciva/crypto -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c scrypt-1.2.0/libcperciva/crypto/crypto_aes_aesni.c -o build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/libcperciva/crypto/crypto_aes_aesni.o
    cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DHAVE_CONFIG_H -DHAVE_SYSCTL_HW_USERMEM=1 -Iscrypt-1.2.0 -Iscrypt-1.2.0/lib -Iscrypt-1.2.0/lib/scryptenc -Iscrypt-1.2.0/lib/crypto -Iscrypt-1.2.0/lib/util -Iscrypt-1.2.0/libcperciva/cpusupport -Iscrypt-1.2.0/libcperciva/alg -Iscrypt-1.2.0/libcperciva/util -Iscrypt-1.2.0/libcperciva/crypto -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c scrypt-1.2.0/libcperciva/crypto/crypto_aes.c -o build/temp.macosx-10.12-intel-2.7/scrypt-1.2.0/libcperciva/crypto/crypto_aes.o
    scrypt-1.2.0/libcperciva/crypto/crypto_aes.c:6:10: fatal error: 'openssl/aes.h' file not found
    #include <openssl/aes.h>
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/jayhwang/.sandbox/blockstack/blockstack-testing/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/dq/c2_1kmrn2tbg0zmmvlscs5240000gn/T/pip-rqFthU-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/dq/c2_1kmrn2tbg0zmmvlscs5240000gn/T/pip-B18K2K-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/jayhwang/.sandbox/blockstack/blockstack-testing/include/site/python2.7/scrypt" failed with error code 1 in /private/var/folders/dq/c2_1kmrn2tbg0zmmvlscs5240000gn/T/pip-rqFthU-build/
`

**Comment by kantai** [comment]
Ah, yeah, now I'm remembering all the joys of openssl linking on macOS. So brew will install openssl, but it doesn't link it automatically for a large collection of esoteric reasons. So you have to tell the compiler (called by `pip`), which openssl to use specifically.

If you build py-scrypt like this:

```
(blockstack-testing) $ PYSCRYPT_NO_LINK_FLAGS=1 LDFLAGS="/usr/local/opt/openssl/lib/libcrypto.a /usr/local/opt/openssl/lib/libssl.a" CPPFLAGS="-I/usr/local/opt/openssl/include" pip install git+https://github.com/blockstack/virtualchain.git@rc-0.14.2
```

This should *hopefully* work. Failing that, I think you should try using our pre-packaged virtualenv.

**Comment by jay-hwang** [comment]
Didn't work either. I'll try using the pre-packaged virtualenv. Where can I find it?

**Comment by kantai** [comment]
It's packed in the macOS app.

You can get that here:
https://github.com/blockstack/blockstack-browser/releases

and then the virtualenv tarball is:

```
/Applications/Blockstack.app/Contents/Resources/blockstack-venv.tar.gz
```
