### ISSUE TITLE
Inclusion of dust UTXOs in account balance

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#475]
Currently, core includes dust UTXOs in your account balance. When verifying that PREORDER, REGISTER, UPDATE, TRANSFER will all succeed, core will include the dust UTXOs in that verification. However, these aren't spendable.

To fix this, the price check in `safety.py`, should only include non-dust UTXOs in its calculation. This will probably require adding a parameter to the balance calculation. It will also need a more verbose error response than currently supported.

**Comment by jcnelson** [comment]
This issue is now deprecated, since we handle fee estimation in blockstack.js.  Closing this out here.
