### ISSUE TITLE
Index the blockchain at varying heights to speed up registration

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#480]
Blockstack Core waits 6 confirmations before accepting transactions, and this makes name registrations take a while.  What we could do instead is run two separate indexers inside of Core--a "stable" indexer that waits 6 confirmations, and an "unstable" indexer that waits 1 or 2 confirmations.  The "unstable" indexer would constantly check the "stable" indexer to see whether or not it has diverged (i.e. processed a short-lived and now-dead fork), and if so, wipe its state and start anew from the "stable" indexer state.  This process is described in more detail in the [virtualchain paper](https://blockstack.org/virtualchain_dccl16.pdf).

API clients could query the "unstable" indexer for name lookups with a pretty good degree of confidence that the state is stable.  This would make name registrations appear to go faster in most cases.  Using the "unstable" index carries the risk that the query result gets invalidated (i.e. `whois` information could change after the read), but this is fine in a lot of non-critical cases, like getting started with the software or trying out some tutorials.  Clients that need high confidence in the name state would use the "stable" indexer state.

**Comment by muneeb-ali** [comment]
+1 to have this -- it'll be really useful. 

Is it possible to just maintain recent "unstable state" instead of a full unstable indexer and then throw away / update that unstable state as blocks come in? If we can, then we don't need to check this unstable state against the stable indexer. The stable indexer is always the source of truth and the recent unstable state is just hints that we give to apps/users for a better UX.

**Comment by jcnelson** [comment]
> Is it possible to just maintain recent "unstable state" instead of a full unstable indexer and then throw away / update that unstable state as blocks come in?

The logic required to accept unstable but valid state is basically the same as the validation logic required to run an indexer.  I was thinking we'd just do something like this:

```
index_block_heights = [...]
blockstack_dir = ...
stable_height = bitcoin.getblockcount() - MIN_CONFS_REQUIRED

# index most-stable to least-stable
index_block_heights.sort()

# build up indexes at each index height
for block_height in index_block_heights:
   unstable_state_dir = os.path.join(blockstack_dir, "unstable-{}".format(block_height)
   sync_virtualchain(block_height, working_dir=unstable_state_dir)

# discard less-stable indexes that have diverged from more-stable indexes
all_index_heights = [stable_height] + index_block_heights
all_index_heights.reverse()

for i in xrange(0, len(all_index_heights)-1):
   more_stable_state_dir = os.path.join(working_dir, "unstable-{}".format(index_block_heights[i+1]))
   less_stable_state_dir = os.path.join(working_dir, "unstable-{}".format(index_block_heights[i]))

   if is_empty_dir(more_stable_state_dir):
      continue

   if is_empty_dir(less_stable_state_dir):
      continue

   more_stable_ch = get_consensus_hash(more_stable_state_dir)
   less_stable_ch = get_consensus_hash(less_stable_state_dir)

   if more_stable_ch != less_stable_ch:
      # less-stable state was on a minority fork
      # blow it away and try again from the stable state
      shutil.rmtree(less_stable_state)
      bootstrap_from_existing_state(more_stable_state, less_stable_state)
```

Queries like `lookup` or `whois` would optionally take an index height they'd like to check, allowing the client to trade stability for faster results.

**Comment by muneeb-ali** [comment]
> The logic required to accept unstable but valid state is basically the same as the validation logic 

Makes sense. 

My intention was to try and avoid the work of checking for conflicts with the stable indexer and/or rebuilding it after detecting a fork i.e., we shouldn't care if the unstable indexer is in sync or not.

**Comment by jcnelson** [comment]
Yeah, exactly.  If unstable state does not match stable state, we blow it away and re-build it from the stable state.  We can do this arbitrarily far back in time as well, at arbitrarily many different heights.

**Comment by jackzampolin** [comment]
Is this discussion still ongoing @jcnelson?

**Comment by jcnelson** [comment]
Yes.  Automatically recovering from reorgs, especially in radial-2 settings in the STACKS blockchain, will be critical to its long-term operation.

**Comment by jcnelson** [comment]
Closing as stale.  We have instant name registration with subdomains, which does not require this.  The Stacks blockchain will do something else entirely.
