### ISSUE TITLE
macOS testing for 0.14.3

### ISSUE THREAD

**Issue by lacabra** [blockstack/blockstack-core#489]
Need to heavily test our macOS build (for 0.14.3). 

At @muneeb-ali request: we probably need to figure out a more automated process where we boot new machines and also test different versions of the OS. We can buy licenses to macOS VMs if needed.

Tagging @kantai so he can take the lead on setting up the test environment and tagging @jcnelson and @larrysalibra.

**Comment by jackzampolin** [comment]
Duplicate issue. Closing in favor of: https://github.com/blockstack/blockstack-core/issues/335
