### ISSUE TITLE
Withdraw balance with specified min_confs

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#492]
I've gotten really spoiled with low confirmation transactions. However, we don't currently support withdraws of low min_conf transactions

```
aaron@cornelius $ blockstack balance
{
    "addresses": [
        {
            "address": "FOO", 
            "bitcoin": 0.0, 
            "satoshis": 0
        }
    ], 
    "total_balance": {
        "bitcoin": 0.0, 
        "satoshis": 0
    }
}

aaron@cornelius $ blockstack balance 0
{
    "addresses": [
        {
            "address": "FOO", 
            "bitcoin": 0.0103179, 
            "satoshis": 1031790
        }
    ], 
    "total_balance": {
        "bitcoin": 0.0103179, 
        "satoshis": 1031790
    }
}

aaron@cornelius $ blockstack withdraw ADDRESS
Enter wallet password: 
{
    "error": "Failed to find UTXOs for wallet payment address"
}
```

This would be nice to support (and is a UX issue on browser, which shows a zero-conf balance which the user won't be able to withdraw).

**Comment by jackzampolin** [comment]
I would love to see this! I believe https://github.com/blockstack/blockstack-core/issues/480 is related?

**Comment by kantai** [comment]
This shipped -- see the `min_confs` argument of `POST /v1/wallet/`:

http://blockstack.github.io/blockstack-core/index.html#core-wallet-management-withdraw-payment-wallet-funds
