### ISSUE TITLE
Find a better place to store storage related meta data

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#495]
Currently we're storing storage provider indices in the same data structure we use to storage social media and other accounts intended to be user visible. Because of this, a "storage" account appears in profiles (see explorer screenshot below)

We should consider if this is the appropriate place to store storage related metadata going forward

![](http://i.imgur.com/YL2Yv5w.jpg)

**Comment by shea256** [comment]
Ah good catch. This shouldn't go in here.

As a general approach, I think of the profile as a structure that should only contain information that people want to be displayed to the world (in a visual form).

Metadata that doesn't need to be displayed should be placed in another structure in the token file.

**Comment by jackzampolin** [comment]
Closing as we have fixed this issue.
