### ISSUE TITLE
Add discovery of user's core node to authentication process

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#496]
During the authentication process, an app verifies that the authentication response is signed by the keys authorized by the owner of the name the user is claiming. It does this by doing a lookup against a core node that the app trusts.

The authentication response also includes a core session token that should be used for requests against the core node that issues it. 

Do we have a mechanism for the app to discover the user's code?

Related: https://github.com/blockstack/blockstack-browser/issues/290

tagging @jcnelson @kantai

**Comment by larrysalibra** [comment]
It looks like there's a key `api_endpoint` in the core session token that might have this information: https://github.com/blockstack/blockstack-storage-js/blob/master/src/datastore.js#L532

**Comment by jackzampolin** [comment]
This has been done! Closing.
