### ISSUE TITLE
Gaia: add support for Range queries and XmlHttpRequests

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#500]
In order to help 3rd party libraries load files out of Gaia, the Core node needs to be able to handle `Range:` headers and respond to XmlHttpRequests for file bytes.  This will be combined with https://github.com/blockstack/blockstack-storage-js/issues/10.

**Comment by icidasset** [comment]
Few more details:

1. The response should have the header `Content-Range`
2. Allowed CORS headers `Range` & exposed CORS header `Content-Range`

Will let you know when I think of anything else.
Thanks again!

**Comment by jcnelson** [comment]
Range: headers have been merged to master :tada:

**Comment by icidasset** [comment]
Awesome! Thanks @jcnelson 😄

**Comment by jackzampolin** [comment]
Closing this as implemented 🎉
