### ISSUE TITLE
Update Core API Docs to include accurate return values

### ISSUE THREAD

**Issue by vbrandl** [blockstack/blockstack-core#509]
The return values for the REST endpoints are not properly documented. https://core.blockstack.org/ is the closest it gets to a documentation of types but these are only example values and there is no formal documentation about the results Rand their attributes. It would be great to have every possible attribute documented along with their data types and if a attribute is required or mandatory. Something like
```
{
  "status": String, 
  "version": String
}
```
for every type would be great. It is hard to develop against an API when you don't know the exact values that will be returned.

I also found some inconsistent uses of data types. E.g. in `GET /v1/node/config` there is something like this:
```
{
         "bitcoind": {
             [...]
             "port": "18332",
             "regtest": "True",
             [...]
         },
}
```
Where port und regtest are strings whereas changing the configuration via `POST /v1/node/config/{section}?{key}={value}` will return `{ 'status' : true }` where status is a boolean value. Same goes for number types.

**Comment by vbrandl** [comment]
Also the authorization mechanism should be documented better. The doc says for some endpoints, that the `Authorization` is needed but not, if it is `Authorization: Basic` or `Authorization: Bearer` (or something completely different).
And I found an inconsistency: For the auth endpoint at `GET /v1/auth?authRequest={authRequestToken}`, the doc states `Requires a pre-shared secret in the Authorization: header.` that's not true from my understanding.

**Comment by muneeb-ali** [comment]
Thanks @vbrandl for reporting -- we'll take a look!

**Comment by jcnelson** [comment]
In the specific case of `/v1/node/config`, your `GET` request returns the literal key/value pairs from the node's config file (which is a `.ini` file).  They are not typed, since `.ini` files do not carry type information.

**Comment by vbrandl** [comment]
At least in the example at https://github.com/blockstack/blockstack-core/blob/master/docs/api-specs.md#get-the-nodes-config-get-v1nodeconfig there is
```json
"bitcoind": {
    "regtest": "True"
},
"blockstack-client": {
    "anonymous_statistics": false
}
```
For other cases I would have to read through the document again.

**Comment by jackzampolin** [comment]
I can get this one.

**Comment by jcnelson** [comment]
This has all been merged -- Core now documents both examples and schemas for all error paths.
