### ISSUE TITLE
blockstack-browser deb repo is not current

### ISSUE THREAD

**Issue by dantrevino** [blockstack/blockstack-core#511]
Not sure if this belongs in -core or -browser, but since the instructions are in core ....

blockstack-browser installed by following linux instructions is not current.  Current release appears to be v.0.12.0, version installed by following instructions is v.0.11.1.

To replicate:
```
$ wget -qO - https://raw.githubusercontent.com/blockstack/packaging/master/repo-key.pub | sudo apt-key add -
$ echo "echo 'deb http://packages.blockstack.com/repositories/ubuntu/ xenial main' > /etc/apt/sources.list.d/blockstack.list" | sudo -E bash -
$ sudo apt update
$ sudo apt install blockstack-browser
```
expected behavior:
```
Setting up blockstack-browser (0.12.0) ...
```
current behavior:
```
Setting up blockstack-browser (0.11.1) ...
```

**Comment by jcnelson** [comment]
Thanks for reporting!  I just uploaded 0.12.

**Comment by kantai** [comment]
Closing this -- creating a new issue for automating the apt package building process (#515)
