### ISSUE TITLE
data writes from apps aren't succeeding

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-core#514]
Here's a screenshot from the to-do list app:

<img width="1272" alt="screen shot 2017-08-01 at 2 43 10 pm" src="https://user-images.githubusercontent.com/994646/28841327-ddfcf4fe-76c7-11e7-9ff0-b01ecda6d8c7.png">

Happy to provide additional logs as needed. Just let me know what you'd like.

**Comment by shea256** [comment]
@jcnelson @larrysalibra @kantai Wasn't sure which repo to place this issue in but I decided on core since it seems it's an issue with permissions on a particular Gaia endpoint.

**Comment by shea256** [comment]
@jcnelson DM'ing it to you.

**Comment by jcnelson** [comment]
This is partially addressed in `hotfix-one-month-sessions`.

**Comment by jackzampolin** [comment]
We have moved core out of the write path. Closing this as not an issue.
