### ISSUE TITLE
Automating builds for apt repository

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#515]
Looking at #511 made me think we should set up an automated build process for our apt repository (for core, browser, etc.), as the apt installs really simplify the process of getting blockstack running on linux.

The blockstack/packaging repo already builds and deploys from a pretty straight-forward script, so this shouldn't be too difficult. We can integrate that into the Jenkins VM we have for running integration tests, and have it rebuild automatically on pushes to master branches (or be manual, but *less* manual than it is now)

Thoughts?

@jcnelson @jackzampolin

**Comment by vsund** [comment]
A documented release process could help with that too :)

**Comment by jcnelson** [comment]
@kantai integrating with Jenkins sounds like a good idea.  We do this with Syndicate every time we run tests, for example.  I can give you the private key I use to sign repo data of you or @jackzampolin has a few cycles to spare to set this up.

**Comment by jackzampolin** [comment]
Some sort of CI for sure. I'm getting acclimated to the Azure environment. I'll see about setting up a Jenkins server.

**Comment by kantai** [comment]
I used an Azure VM with Jenkins for tesing the 0.14.3 release-- can set you up on that machine. Will ping you on slack.

**Comment by kantai** [comment]
Last release to our apt repository was choreographed on Jenkins. Should be a pretty smooth process now for future releases.
