### ISSUE TITLE
Support for updating subdomain zonefile entries

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#529]
Currently, our subdomain registrar only handles registration requests. It should additionally handle updating those entries. 

The resolver supports parsing and verifying these updates, but an endpoint needs to be added to the registrar (and verification code for the registrar, so that it doesn't add invalid entries to it's zonefiles, even if the resolvers will ultimately ignore them).

**Comment by jcnelson** [comment]
Moving this over to the subdomain registrar issue tracker: https://github.com/blockstack/subdomain-registrar/issues/13
