### ISSUE TITLE
Setting up server with `blockstack setup -y` still requires user input

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-core#530]
@kantai

**Comment by kantai** [comment]
The issue in question here is that when you run `blockstack setup -y`, it runs fine without user input, but the "client email" entry isn't automatically skipped. So the next time you run `blockstack`, it will prompt you for an e-mail signup.

**Comment by kantai** [comment]
Fixed with commit 529f71530ee2b1d44965279e6690b6fdaa97f13c
