### ISSUE TITLE
Local core should speak HTTPS to node.blockstack.org

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#533]
Interactions between local core node and node.blockstack.org should be over HTTPS. While secrets are not communicated over this link, interactions like name lookups and price lookups are, which leaks potentially information about how a given user is interacting with the network as well as information about names the user may be considering registering.

This can be fixed directly by getting our proxy service for node.blockstack.org a certificate and updating the client to allow URLs for connections to the blockstack indexers (this will allow us to specify "https").

**Comment by jackzampolin** [comment]
☝️ Done! Added cron too.

**Comment by kantai** [comment]
Thanks Jack! It works when I manually CURL the endpoints, working on getting the blockstack client to speak HTTPS now.

**Comment by kantai** [comment]
Merged into devel branch with PR #544
