### ISSUE TITLE
Installation Issue: Ubuntu 16.04 Unmet dependencies

### ISSUE THREAD

**Issue by rcnewman** [blockstack/blockstack-core#536]
Getting an error on `sudo apt install blockstack`

```
The following packages have unmet dependencies:
 blockstack : Depends: python-dropbox but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by kantai** [comment]
Thanks for reporting the issue -- looking into it now.

**Comment by kantai** [comment]
It looks like there was a bug in our python->deb packager that caused it to generate a malformed python-dropbox deb. I've updated the repo and it should work now if you run

```
$ sudo apt update
$ sudo apt install blockstack
```

**Comment by kantai** [comment]
Apt repository has been updated and this issue should be addressed. If you're still having problems, report back and we can reopen.
