### ISSUE TITLE
Export Username from Onename to Blockstack Browser

### ISSUE THREAD

**Issue by shaftgunk** [blockstack/blockstack-core#539]
After attempting to Export Username from Onename to Blockstack Browser, my Onename profile now shows as "Profile Being Processed". Previously, it did not display this message.

Also, 0.000055 BTC magically appeared in my Blockstack Browser Wallet: https://blockchain.info/address/3PbNfxu2iVfY6vnmzz9czHbdE2GJWoJBke

I have added screenshots below:

![export-username](https://user-images.githubusercontent.com/25827955/29322835-939f4596-81a4-11e7-8e42-7826896e04d4.png)
![profile-processed](https://user-images.githubusercontent.com/25827955/29289994-2fa52010-8104-11e7-94ea-5512130884f1.png)
![btc-appears](https://user-images.githubusercontent.com/25827955/29290002-3245c8d8-8104-11e7-93e8-1bbc9fdef469.png)

**Comment by jackzampolin** [comment]
Closing this issue as stale.
