### ISSUE TITLE
Subdomain registrar endpoint doesn't handle CORS preflight

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#540]
It needs to respond to `OPTIONS` preflight and also have the right headers so that the browser can POST to it.

<img width="594" alt="screen shot 2017-08-15 at 8 16 30 pm" src="https://user-images.githubusercontent.com/597182/29315638-c326b324-81f6-11e7-90e4-916da5d26c47.png">

I'm using the circleci blockstack-venv artifact from core commit 95d8645dc1d781d4cb488834dd41ebc268d9c05c running in regtest mode.

**Comment by kantai** [comment]
PR #541 adds an OPTIONS endpoint which returns CORS headers, and adds Access-Control-Allow-Origin header to the `/v1/names` and `/status/` endpoints.

**Comment by larrysalibra** [comment]
This is fixed for me. Thank you again @kantai !
