### ISSUE TITLE
Interactive mode doesn't kill API endpoint on shutdown

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#542]
When you run blockstack integration tests in interactive mode (which is how we test and develop on browser, etc.), sending a Ctrl-C SIGINT to the process *usually* shuts down the blockstackd process and bitcoind, but the API endpoint is almost always still alive:

```
$ blockstack-test-scenario --interactive 2 blockstack_integration_tests.scenarios.portal_test_env 2>&1 | tee /tmp/stdout | grep "inish"
...
Test finished; doing checks
^C
```
```
$ ps aux | grep blockstack-test
aaron    19669  3.4  0.4 1019232 66712 ?       Sl   13:49   0:31 /home/aaron/devel/blockstack-core.2/.venv/bin/python2 /home/aaron/devel/blockstack-core/.venv/bin/blockstack-test-scenario --interactive 2 blockstack_integration_tests.scenarios.portal_test_env
```

This is a mild annoyance, but a persistent one that I hope to get around to squashing sooner rather than later.

**Comment by jcnelson** [comment]
I think this is fixed in the above commit

**Comment by jackzampolin** [comment]
Closing this as fixed.
