### ISSUE TITLE
Uncatched exceptions from zone file library on profiles with old zone file formats

### ISSUE THREAD

**Issue by vsund** [blockstack/blockstack-core#546]
I found two IDs with old zone file formats that cause an exception in the zone file library ([`asdf.id`](https://explorer.blockstack.org/name/asdf.id) and [`rayan.id`](https://explorer.blockstack.org/name/asdf.id)).
These both have (obviously) incorrect zone files and the zone file library throws this error rightfully. However the lookup method should catch this exception and expose an own message instead of the zone file exception.

**Comment by kantai** [comment]
I think we just need to silence the stack trace in blockstack-zones:

https://github.com/blockstack/zone-file-py/pull/21

Thoughts, @jcnelson ?

**Comment by jcnelson** [comment]
Should be fine.  Let's only print a stack trace if `BLOCKSTACK_DEBUG` is set in the environment.

**Comment by kantai** [comment]
> Should be fine. Let's only print a stack trace if BLOCKSTACK_DEBUG is set in the environment.

I believe that's already the behavior in the latest blockstack_zones

**Comment by jackzampolin** [comment]
Closing this as fixed.
