### ISSUE TITLE
Start a production subdomain registrar node

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#547]
In order to ship subdomain support in the browser, we'd need to spin up a production subdomain registrar node that registers subdomains for a given domain.

We need to:

1. Figure out what domain to use.
2. Start a blockstack-core node which can submit updates on behalf of that domain.
3. Point a subdomain registrar at that blockstack-core node, and perform _some_ kind of spam protection.

For the spam protection, we could read the submitted zonefile, lookup the associated profile object, and require a valid social proof (which raises a related issue of whether or not social proofs will be valid with subdomain strings `foo.bar.id`).

Tagging @muneeb-ali @jcnelson for thoughts on spam control.

**Comment by jackzampolin** [comment]
Does core.blockstack.org have this functionality?

**Comment by jackzampolin** [comment]
https://registrar.blockstack.org
