### ISSUE TITLE
Tumbleweed Install with pip fails due to 'gcc' being unavailable

### ISSUE THREAD

**Issue by 84adam** [blockstack/blockstack-core#549]
Running OpenSUSE Tumbleweed.

Ran:
`$ sudo zypper update && zypper install rng-tools python-devel libffi-devel`
`$ sudo pip install blockstack --upgrade`

Got errors at the end of the install process relating to 'gcc':

```
creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/libcperciva/alg
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/libcperciva/crypto
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/libcperciva/util
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -DOPENSSL_LOAD_CONF -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -fPIC -DHAVE_CONFIG_H -DHAVE_CLOCK_GETTIME=1 -DHAVE_LIBRT=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_STRUCT_SYSINFO=1 -DHAVE_STRUCT_SYSINFO_MEM_UNIT=1 -DHAVE_STRUCT_SYSINFO_TOTALRAM=1 -DHAVE_SYSINFO=1 -DHAVE_SYS_SYSINFO_H=1 -D_FILE_OFFSET_BITS=64 -Iscrypt-1.2.0 -Iscrypt-1.2.0/lib -Iscrypt-1.2.0/lib/scryptenc -Iscrypt-1.2.0/lib/crypto -Iscrypt-1.2.0/lib/util -Iscrypt-1.2.0/libcperciva/cpusupport -Iscrypt-1.2.0/libcperciva/alg -Iscrypt-1.2.0/libcperciva/util -Iscrypt-1.2.0/libcperciva/crypto -I/usr/include/python3.6m -c src/scrypt.c -o build/temp.linux-x86_64-3.6/src/scrypt.o -O2
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-l_04wob_/scrypt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-fown61g_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-l_04wob_/scrypt/
```

My guess is that this is related to SUSE-based OS not relying on 'gcc' specifically, but a different compiler?

Thanks!

**Comment by kantai** [comment]
Hi, thanks for reporting this. Can you try installing `gcc` through zypper? You may also need to reconfigure your default python, blockstack requires python2, but it looks like your pip is trying to install via python3.

**Comment by 84adam** [comment]
I tried installing 'gcc' as it was in fact missing. Install of 'gcc' succeeded, see default below:

```
$ sudo zypper install gcc

$ which gcc
/usr/bin/gcc

$ gcc --version
gcc (SUSE Linux) 7.1.1 20170629 [gcc-7-branch revision 249772]
```

NOTE: Tumbleweed just recently moved from gcc 6 to gcc 7. (See: https://lists.opensuse.org/opensuse-factory/2017-05/msg00516.html )

---

Next, I checked my Python version(s):

```
$ which python
/usr/bin/python

$ ls /usr/bin | grep python
python
python2
python2.7
python2.7-config
python2-config
python3
python3.6
python3.6m
python-config

$ python --version
Python 2.7.13
```

I then ran the 'pip install' command again; errored out again, see below:

```
$ sudo pip install blockstack --upgrade
[...]

gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -DOPENSSL_LOAD_CONF -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -fPIC -DHAVE_CONFIG_H -DHAVE_CLOCK_GETTIME=1 -DHAVE_LIBRT=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_STRUCT_SYSINFO=1 -DHAVE_STRUCT_SYSINFO_MEM_UNIT=1 -DHAVE_STRUCT_SYSINFO_TOTALRAM=1 -DHAVE_SYSINFO=1 -DHAVE_SYS_SYSINFO_H=1 -D_FILE_OFFSET_BITS=64 -Iscrypt-1.2.0 -Iscrypt-1.2.0/lib -Iscrypt-1.2.0/lib/scryptenc -Iscrypt-1.2.0/lib/crypto -Iscrypt-1.2.0/lib/util -Iscrypt-1.2.0/libcperciva/cpusupport -Iscrypt-1.2.0/libcperciva/alg -Iscrypt-1.2.0/libcperciva/util -Iscrypt-1.2.0/libcperciva/crypto -I/usr/include/python3.6m -c src/scrypt.c -o build/temp.linux-x86_64-3.6/src/scrypt.o -O2
    src/scrypt.c:27:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-iwrexe41/scrypt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lquy48h6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-iwrexe41/scrypt/
```

There also appears to be an error with 'Python.h' -- as you can see above -- I didn't notice this before:

```
[...]
    src/scrypt.c:27:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
[...]
```

Any additional suggestions?

**Comment by vsund** [comment]
Seems like `pip` tried to use `python3` again although `python` is configured as `python2`. Just out of curiosity, could you try `pip2 install blockstack`?

**Comment by 84adam** [comment]
OK. So I installed pip2 first:

`$ sudo zypper install python2-pip`

Then tried again:

`$ sudo pip2 install blockstack`

Result:

```
gcc -pthread -fno-strict-aliasing -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -DOPENSSL_LOAD_CONF -fwrapv -fPIC -DHAVE_CONFIG_H -DHAVE_CLOCK_GETTIME=1 -DHAVE_LIBRT=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_STRUCT_SYSINFO=1 -DHAVE_STRUCT_SYSINFO_MEM_UNIT=1 -DHAVE_STRUCT_SYSINFO_TOTALRAM=1 -DHAVE_SYSINFO=1 -DHAVE_SYS_SYSINFO_H=1 -D_FILE_OFFSET_BITS=64 -Iscrypt-1.2.0 -Iscrypt-1.2.0/lib -Iscrypt-1.2.0/lib/scryptenc -Iscrypt-1.2.0/lib/crypto -Iscrypt-1.2.0/lib/util -Iscrypt-1.2.0/libcperciva/cpusupport -Iscrypt-1.2.0/libcperciva/alg -Iscrypt-1.2.0/libcperciva/util -Iscrypt-1.2.0/libcperciva/crypto -I/usr/include/python2.7 -c scrypt-1.2.0/libcperciva/crypto/crypto_aes.c -o build/temp.linux-x86_64-2.7/scrypt-1.2.0/libcperciva/crypto/crypto_aes.o -O2
    scrypt-1.2.0/libcperciva/crypto/crypto_aes.c:6:10: fatal error: openssl/aes.h: No such file or directory
     #include <openssl/aes.h>
              ^~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dqdQkB/scrypt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-02_scF-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-dqdQkB/scrypt/
```

I don't believe openssl is the issue here, seems I'm up to date:

```
'openssl' is already installed.
No update candidate for 'openssl-1.0.2l-2.1.noarch'. The highest available version is already installed.
```

**Comment by kantai** [comment]
Cool -- looks like you'll need the zypper openssl source package to compile the python cryptography libraries -- can you install `libopenssl-devel` ?

**Comment by 84adam** [comment]
OK. Installed; re-ran:

```
$ sudo zypper install libopenssl-devel
$ sudo pip2 install blockstack
```

Appears install was successful: 

```
[...]
Installing collected packages: scrypt, basicrpc, boto, dropbox, PyYAML, rsa, pyasn1-modules, oauth2client, uritemplate, google-api-python-client, pydrive, onedrivesdk, blockstack
  Running setup.py install for scrypt ... done
  Running setup.py install for basicrpc ... done
  Running setup.py install for PyYAML ... done
  Running setup.py install for onedrivesdk ... done
  Running setup.py install for blockstack ... done
Successfully installed PyYAML-3.12 basicrpc-0.0.2 blockstack-0.14.4.2 boto-2.48.0 dropbox-8.0.0 google-api-python-client-1.6.2 oauth2client-4.1.2 onedrivesdk-1.1.8 pyasn1-modules-0.0.11 pydrive-1.3.1 rsa-3.4.2 scrypt-0.8.0 uritemplate-3.0.0
```

Attempted test of installation; input email address for notification; got error:

```
$ blockstack info
Would you like to receive an email when there is a new release of this software available?
Email address (leave blank to opt out): <handle>@<domain>.<tld>
Saving configuration to /home/<user>/.blockstack/client.ini
{
    "error": "Failed to contact blockstack daemon.  Please ensure that it is running with the `api` command."
}
```

Should I open a separate issue/ticket for the 'email notification' error?

Would I need to do: `$ blockstack api start` first? ... Or should I run the 'fast_sync' with 'blockstack_core' command next?

Thanks for your help!

**Comment by kantai** [comment]
Awesome -- it looks like this successfully installed.

Yeah, you need to run `blockstack api start` before the `blockstack info` command will return anything useful. You should also run `blockstack setup`. Our CLI interface isn't the most intuitive right now, but we are planning on doing some user-experience improvement to it in the near-term.

I'll collect the issues you ran into here and update the instructions in the `readme.md`. Thanks!

**Comment by 84adam** [comment]
Appreciate your help. Excited for this project!

---

Suggestions for OpenSUSE & Tumbleweed Installation Instructions:

**For SUSE and openSUSE**

```
$ sudo zypper update && zypper install rng-tools python-devel libffi-devel gcc python2-pip libopenssl-devel
$ sudo pip2 install blockstack --upgrade
```

Suggestion for General Post-Install Setup Instructions:

```
$ blockstack setup
<ENTER A NEW PASSWORD>
```

On the above step, I would suggest:

1. *obfuscate password* on "Got backup?" query; do not print out on terminal.
2. Note to user that config files have been installed to `$HOME/.blockstack`
3. Note to user that 'wallet.json' file in `$HOME/.blockstack/` contains public key, payment address, and 'enc' (encrypted private key, I presume?)

Following `$ blockstack setup`, start the api, entering your password when prompted:

```
$ blockstack api start
Enter wallet password:
{
    "status": true
}
```

Next run `$ blockstack info` to test and verify your setup.

---

**Comment by kantai** [comment]
Thanks for the feedback @84adam !

I've added your suggestions for improvements to the setup command to a new issue.

The post-install setup instructions have also been updated as of PR #563 

Closing this issue now.

**Comment by vutukurisainikhil** [comment]
hi, I am trying to install requests_kerberos, in opensuse linux server 
but i am getting error like this, kindly helpme out:

 ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-G3pUg3/pykerberos/setup.py'"'"'; __file__='"'"'/tmp/pip-install-G3pUg3/pykerberos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tRBbmC/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-G3pUg3/pykerberos/
    Complete output (13 lines):
    running install
    running build
    running build_ext
    building 'kerberos' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    gcc -pthread -fno-strict-aliasing -fmessage-length=0 -grecord-gcc-switches -fstack-protector -O2 -Wall -D_FORTIFY_SOURCE=2 -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -fstack-protector -O2 -Wall -D_FORTIFY_SOURCE=2 -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o
    src/kerberos.c:17:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-G3pUg3/pykerberos/setup.py'"'"'; __file__='"'"'/tmp/pip-install-G3pUg3/pykerberos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tRBbmC/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
