### ISSUE TITLE
[Gaia] Key file deployment

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#556]
One of the prerequisites for implementing multi-reader storage is to ensure that Alice can discover all of the public keys needed to authenticate data written by Bob in application `foo.com`.  This is achieved with a "key file," whose tentative structure is documented [here](https://github.com/blockstack/blockstack-browser/blob/master/docs/key-delegation.md).

In this design, there is one major drawback of key files: all software that expects to receive a profile will break.  This is because the key file specification moves the profile inside the key file.

I think this can be solved simply by changing the structure of the key file to be a well-formed profile, but with some extra information.  The signature requirements on app keys, delegation keys, and profile data still hold, but the verification steps will change to the following:

1. get name owner address
2. get name zonefile
3. get name profile
4. extract app keys and delegation keys
5. verify that the public keys in the delegation object JWT match its signature
6. verify that the name owner address was derived from the delegation object's public keys (i.e. the delegation object's public keys correspond to the private keys that own the name)
7. verify that each app key JWTs was signed by the appropriate device's delegation public key
8. verify that the profile was signed by one of the delegation object's public keys

This would be just as secure as what was originally proposed, but with the added benefit that **all resolvers and explorers will keep on working without modification.**  The only remaining engineering tasks would be to:

[ ] finalize the app key derivation logic (blockstack-core, blockstack-browser)
[ ] automatically generate and insert the app and delegation JWTs into a profile when the owner starts the browser (blockstack-browser)
[ ] derive and insert application- and device-specific keys into the app key JWT when the user signs into an app for the first time (blockstack-core, blockstack-browser)
[ ] invalidate any existing application sessions to force upgrading to multi-reader Gaia (blockstack-core)

cc @kantai @shea256 @larrysalibra

**Comment by jcnelson** [comment]
I also propose two slight changes to the structure of delegation and app key objects:

* The application key file bundle should be modified to include a list of URLs to the device's application-specific Gaia datastore.  This would make datastore discovery faster and less dependent on blockstack-core.

* The delegation bundle, the app key bundle, and the profile should all include a monotonically-increasing `timestamp` field to prevent stale keys from being used.  Client libraries should cache timestamps locally to enforce this.

**Comment by muneeb-ali** [comment]
Awesome, thanks, Jude! One quick point. If we're doing a 1.0 release soon, then maybe we don't need to worry about a breakage at resolvers and explorers. 

Most resolver functionality is getting redirected to http://core.blockstack.org (and that'll have the latest version) and the only other component to upgrade is the explorer and it needs an upgrade regardless.

**Comment by muneeb-ali** [comment]
OB is releasing a new version. 
Onename.com uses api.onename.com and we're pointing that to http://core.blockstack.org (instead of resolver.onename.com) 
search is getting pointed to core.blockstack.org as well

I think (a) browser, (b) Core, and (c) explorer are the main upgrades but all of them are actively developed and we can pick a release, say 1.0, when we upgrade them and sync their versions.

**Comment by jcnelson** [comment]
The key file isn't being consumed by anything yet (besides multi-reader Gaia).  Even then, Gaia accesses key file elements via methods instead of direct loads/stores, so the internal methods would be unaffected by changing the key file structure.

The point I was trying to make is that it would be much faster and require much less coordination between us to have me restructure the key file as a profile.  No systems or libraries would have to be changed, since they already expect to deal with profiles.  We could get multi-reader out the door a lot faster with no loss of functionality or security.

**Comment by shea256** [comment]
Hey looping in @csuwildcat to join in on this conversation and provide feedback here.

**Comment by jcnelson** [comment]
This is now implemented.

**Comment by shea256** [comment]
Nice @jcnelson, awesome work! Excited to see multi-reader storage pushed out.

@jcnelson @muneeb-ali The other thing we could do is push off the release of 1.0 until when we do a deeper design push on this file format.

Basically, we do what Jude is suggesting and get out an MVP of multi-reader storage out right now, without breaking any interfaces.

Then, we work on finalizing a 1.0 spec for this file and then break the interfaces once the 1.0 has been finalized.

What do you think?

**Comment by shea256** [comment]
Also @jcnelson can you share a link to this alternative format?

I only see this one here: https://github.com/blockstack/blockstack-browser/blob/master/docs/key-delegation.md.

**Comment by csuwildcat** [comment]
There's a lot to unpack viewing this fresh as an outsider, so take that into account when addressing my questions/comments.

Assuming this is all bound to Blockstack's Zone File direction (which is fine, because a resolver driver can just synthesize a DDO), how does this work and the related examples I saw here: https://github.com/blockstack/blockstack-browser/blob/master/docs/key-delegation.md, account for multi-factor conditions? I wrote up a strawman in the Hubs repo to highlight the possible need for something like it: https://github.com/decentralized-identity/hubs/blob/master/docs/authentication.md#factors

**Comment by jackzampolin** [comment]
Is this still an active concern @jcnelson? If so, can we move this issue to the blockstack/gaia repo?

**Comment by jcnelson** [comment]
I think this needs to be closed here, and re-opened in `blockstack.js` as "how to support multiple devices."  A lot of this discussion relates to an early prototype of multi-reader Gaia that I no longer believe will be released.
