### ISSUE TITLE
Blockstack CLI Redesign

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-core#567]
I've done a bit of work to see what a potential `blockstack` CLI redesign would look like. I've got that up in a [separate repo](https://github.com/jackzampolin/blockstack-cli). It is currently a [`click`](http://click.pocoo.org/) skeleton with all of the endpoints from our [`blockstack api`](https://blockstack.github.io/blockstack-core/) mapped to commands. I've gone with the groupings from that document:

```bash
$ blockstack-cli --help
Usage: blockstack-cli [OPTIONS] COMMAND [ARGS]...

  A command line interface for the blockstack network and local
  installations

Options:
  --host TEXT       blockstack api node to connect to
  --directory TEXT  directory for blockstack configuration and data files
  --help            Show this message and exit.

Commands:
  blockchain  perform blockchain operations with your...
  gaia        these are gaia commands
  name        commands for name operations
  namespace   these are namespace commands
  node        commands for conifguring and reaching...
  price       query the price of names or namespaces
  wallet      commands to perform operations on your...
```

Then each top level command like `gaia` has its own subcommands (I know we are pulling directories out of the next release):

```bash
$ blockstack-cli gaia --help
Usage: blockstack-cli gaia [OPTIONS] COMMAND [ARGS]...

  these are gaia commands

Options:
  --help  Show this message and exit.

Commands:
  directory  crud for gaia directories
  file       crud for gaia files
  inode      get info about inode at PATH from STORE
  store      store

$ blockstack-cli gaia file --help
Hello gaia
Usage: blockstack-cli gaia file [OPTIONS] COMMAND [ARGS]...

  crud for gaia files

Options:
  --help  Show this message and exit.

Commands:
  create  create file at given PATH from STORE
  delete  delete file at given PATH from STORE
  get     get file at given PATH from STORE
  update  update file at given PATH from STORE
```

Each of the commands has a callback. Currently each of the callbacks just prints to `stdout` but the project already pulls in `blockstack` so we can just use the library functions to fill out this skeleton. Here are a couple of examples:

```python
# blockstack-cli node ping
# https://blockstack.github.io/blockstack-core/#core-node-administration-ping-the-node
@node.command()
@pass_config
def ping(config):
    """check availibiltiy for connected node"""
    click.echo(blockstack.blockstack_client.ping())

# blockstack-cli blockchain send_transaction
# https://blockstack.github.io/blockstack-core/#blockchain-operations-broadcast-transaction
@blockchain.command()
@click.option('--blockchain', default='bitcoin', help='blockchain to which address belongs. Currently only bitcoin is supported')
@click.argument('JSON', type=click.File('rb'))
@pass_config
def send_transaction(config,blockchain,json):
    """send a transaction to the underlying blockchain"""
    click.echo('Sending transaction to the {} blockchain from file {}...'.format(blockchain,json))
```

**Comment by shea256** [comment]
Awesome work on this @jackzampolin. Excited to build off of this and continue the earlier discussion with @larrysalibra and @kantai and @muneeb-ali.

**Comment by kantai** [comment]
Okay, so in a redesign, the `blockstack-cli` is a RESTful client of the blockstack API (described at https://blockstack.github.io/blockstack-core/), then we have 3 scripts:

1. `blockstack-cli`
2. `blockstack-api [stop, start]`
3. `blockstack-core [stop, start]`

I think it's important that the cli remain a RESTful client, so that we don't have the issue that we currently have in `rpc.py` and `actions.py` not have synchronized functionality.

Also, I whole-heartedly approve of moving to Click (or another cli-library)

**Comment by kantai** [comment]
Also, tagging @jcnelson, because he is definitely a stake-holder in the CLI.

**Comment by shea256** [comment]
@kantai Do you even need start?

**Comment by muneeb-ali** [comment]
blockstack-api and blockstack-core script functionality can be behind just a "blockstack-cli" script correct? 

I generally prefer
> $ blockstack 
over
> $blockstack-cli

For example, keybase is just keybase and docker is just docker.

**Comment by jackzampolin** [comment]
So I've named it `blockstack-cli` to avoid naming conflicts locally with other installed programs. I agree with @muneeb-ali we should call it `blockstack`.

**Comment by jackzampolin** [comment]
I think separating into three scripts is good for a couple of reasons:

- Can write separate `systemd`, `wininit` or `launchd` unit files for `blockstack-core` and `blockstack-api`
- Keeps the components separate to allow for clear delineation of responsibility. This will make things more clear for users as well as developers.

**Comment by jcnelson** [comment]
@jackzampolin I'd hold off on working on the Gaia interface, since it's unstable.

**Comment by jcnelson** [comment]
Also, do *not* touch the methods in `actions.py`.  The API server calls them to carry out most of its functionality.

**Comment by muneeb-ali** [comment]
@jcnelson This is a mock CLI script https://github.com/jackzampolin/blockstack-cli

It's not touching any code in blockstack-core yet. We're just playing around with an interface (in a separate box) and can chat about implementing it in blockstack-core later.

**Comment by jcnelson** [comment]
> I think it's important that the cli remain a RESTful client, so that we don't have the issue that we currently have in rpc.py and actions.py not have synchronized functionality.

I'm not sure what you mean by this?  The point of having API routes in `rpc.py` call into the CLI entry points in `actions.py` is to avoid duplicating code.

I agree that having the CLI interface match the RESTful interface is a good design goal.  Is this what you were getting at?

**Comment by kantai** [comment]
>Also, do not touch the methods in actions.py. The API server calls them to carry out most of its functionality.

This is actually pretty problematic. They're called by the API server, and then many of the calls in there call back to the API server, causing function call graphs that invoke the call in actions.py twice (cli_register for example), and obfuscate or mangle option defaults. In general, the `args` object doesn't handle default well, and makes it so that if a function call wants to specify say the second optional argument, it has to also specify the first. This isn't good long term. The API server should be invoking methods that look more like methods, and the CLI should interact through the API server. 

I think moving away from the current structure of the actions.py will help with code maintenance a great deal.

**Comment by jcnelson** [comment]
> This is actually pretty problematic. They're called by the API server, and then many of the calls in there call back to the API server, causing function call graphs that invoke the call in actions.py twice (cli_register for example), and obfuscate or mangle option defaults. In general, the args object doesn't handle default well, and makes it so that if a function call wants to specify say the second optional argument, it has to also specify the first. This isn't good long term. The API server should be invoking methods that look more like methods, and the CLI should interact through the API server.

I definitely agree that this aspect of the codebase needs to be refactored.  We originally did it this way because we wanted read-only methods (like `whois` and `lookup`) to work without requiring the user to unlock their wallet.  However, this was during a time when the CLI was the *only* interface to the system, and the background daemon was only responsible for registering names.

Since this is no longer the case, and since users will be expected to be running an API daemon all the time anyway, the current call graph no longer makes sense.  Nevertheless, changing the structure of `actions.py` is going to be a somewhat big undertaking.  We should attack it once our interfaces are stable to minimize conflicts (i.e. after multi-reader Gaia and the subdomain registrar are merged in, and once we're happy with the 1.0 API for core.blockstack.org).  Just my $0.02.

**Comment by muneeb-ali** [comment]
Just to be clear the API server here is not the Flask API but the internal API daemon, for anyone wondering :-) 

I agree that yes we should just have 1 interface to what we're now calling blockstackd (currently the internal API daemon) and the CLI can directly interact with it. 

I also agree that this can be a bigger undertaking. We can potentially start the process by keeping actions.py in there while directing calls to blockstackd wherever possible and slowly phasing out / merging actions.py.

**Comment by jcnelson** [comment]
> I also agree that this can be a bigger undertaking. We can potentially start the process by keeping actions.py in there while directing calls to blockstackd wherever possible and slowly phasing out / merging actions.py.

This is already mostly the case (which leads to the confusing call graphs).  In most methods, `actions.py` connects to `blockstackd` to load and store data.  However, since `actions.py` does a lot of non-trivial input/output processing that is necessary for both clients and servers, `blockstackd` also calls into its copy of `actions.py` as part of `rpc.py`.  The method stubs in `rpc.py` can tell whether it's the server or client calling them, and route the call appropriately.

What needs to happen is the non-trivial logic in `actions.py` needs to go into its own module, so both the client and server can use it without creating weird call graphs.

**Comment by jackzampolin** [comment]
Ok it seems like we have agreement on a couple of points. Just want to make sure everyone is on the same page:

- There should be 3 command line tools: `blockstack`, `blockstack-api` and `blockstack-core` (current naming)
- The `blockstack` cli should be a wrapper around http calls to [`blockstack-api`](https://blockstack.github.io/blockstack-core/)

This means that its going to be extremely important to keep the [API Docs](https://blockstack.github.io/blockstack-core/) up to date as that is what the CLI is going to be built off of. Does this sound right to everyone?

**Comment by muneeb-ali** [comment]
> There should be 3 command line tools: blockstack, blockstack-api and blockstack-core (current naming)

What's the new naming for blockstack-api and blockstack-core? Also, we should see if we can reduce the no. of command-line tools.

**Comment by jackzampolin** [comment]
@muneeb-ali @kantai mentions above his desire to keep the `blockstack` cli as an HTTP client for the `blockstack api` (current naming). This seems to me a good idea. It opens the door for us to deal with the components individually. This will allow for separation of concerns and make development on top of the API easier. We maintain reference implementations (`blockstack-cli`, `blockstack.js`) and the [API spec](https://blockstack.github.io/blockstack-core/) and then users can build out their own implementations as they see fit (`blockstack-golang`, `blockstack-swift`, etc..). This will reduce our development effort and allow for more extensibility. It also eliminates the need for a config file for the CLI: just set the `host` and auth credentials to connect to a different server.

I think that reducing the number of command line tools is not necessarily a good goal. If we are searching for user understanding and ease of use then having a single command line tool for each component of the architecture helps users better understanding how the system is working (i.e. when I type `blockstack` I'm a client operating on the `blockstack-api` node. The `blockstack-api` node depends on `blockstack-core`, `bitcoind` and `bitcoin-utxo` nodes). When you are communicating with multiple components via the same CLI this mental model quickly becomes muddied and causes confusion. Also more command line tools doesn't necessarily mean more mental overhead. The `blockstack-api` and `blockstack-core` tooling will just have `stop` and `start` with little else.

Another other option could be to add more documentation in the `--help` for the cli to make sure users understand what is going on. In that model we would implement `blockstack api` and `blockstack core` subcommands for spinning up the Indexer and API respectively. I think this could be good (fewer command line tools for users to remember) but would keep the current tight coupling we have between components and retard the development of other implementations. If you look at systems like Elastic, Spark,  a profusion of CLIs: 1 (just a process) or 2 (server/client like `bitcoind` and `bitcoin-cli`) per component in the system.

Thoughts @larrysalibra @shea256 @jcnelson ?

**Comment by jcnelson** [comment]
> The blockstack cli should be a wrapper around http calls to blockstack-api

I agree in principle, but this is not correct to assume that it's only a wrapper.  If we treat `blockstack-api` as outside of the trusted computing base (i.e. it can't know my keys), then a lot of our commands will be mostly implemented client-side.  This is definitely the case with Gaia and name registrations, for example, where even today the Javascript libraries will need to do several HTTP calls to the `blockstack-api` process and carry out some non-trivial data serialization/deserialization and signing/verifying on their own.

**Comment by kantai** [comment]
>  If we treat blockstack-api as outside of the trusted computing base (i.e. it can't know my keys), then a lot of our commands will be mostly implemented client-side. 

To me, that's a separate issue. Moving `blockstack-api` out of the trusted computing base is a bigger re-architecture, and (I think) part of the discussion that started over in [this forum post](https://forum.blockstack.org/t/component-architecture/1417/22)

Changing the blockstack-cli to be a simple HTTP client (of the still trusted blockstack-api) could *hopefully* be completed within a single sprint and shouldn't be interface breaking.

**Comment by jackzampolin** [comment]
I went ahead and implemented the `jackzampolin/blockstack-cli` with just Python `requests`. Its working pretty well locally for me if anyone wants to give it a try!

**Comment by jackzampolin** [comment]
We have decided to go a different direction with the CLI. Closing this as outdated.
