### ISSUE TITLE
Blockstack Api fails to start in Docker only with debug flag enabled

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-core#575]
When running the docker image with `blockstack api start-foreground --password foo --api_password foo --debug` it exits with the following error:

```
Set BLOCKSTACK_DEBUG to 1
{
    "error": "Unexpected error:\nTraceback (most recent call last):\n  File \"/usr/local/bin/blockstack\", line 52, in <module>\n    result = run_cli()\n  File \"/usr/local/lib/python2.7/dist-packages/blockstack_client/cli.py\", line 393, in run_cli\n    fd = write_secrets(secbuf)\n  File \"/usr/local/lib/python2.7/dist-packages/blockstack_client/constants.py\", line 460, in write_secrets\n    assert p.returncode == 0, \"'{}' failed with code {}\".format(command, p.returncode)\nAssertionError: 'lsof -nP +L1 | grep \"/tmp/tmpNsfqZN/secrets\"' failed with code 1\n",
    "help": "Try getting latest version of CLI with \"sudo pip install blockstack --upgrade\""
}
```

But when running w/o the `--debug` flag the process comes up with no issues. Don't really now where to start debugging this but I'm going to remove the `--debug` flag from the standard docker run.

**Comment by jcnelson** [comment]
Does the command `lsof -nP +L1` work in your Docker image?  You may need the GNU `lsof` if you're using Alpine as your base.

**Comment by kantai** [comment]
Adding `lsof` and mounting `/tmp/`on the docker image resolves this issue.
