### ISSUE TITLE
Enable encryption in gaia storage

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#581]
Our current release of gaia storage has not yet enable encryption. This will be enable in a future release. This is a tracking issue for that functionality.

**Comment by kantai** [comment]
This seems like something best implemented client-side in `blockstack.js`. I can take a look at this.

**Comment by kantai** [comment]
This was implemented in `blockstack.js`. Closing this for now, can reopen if we want to go a different route for encryption.
