### ISSUE TITLE
Out of date python libraries in apt

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#595]
Unfortunately, it looks like there are some out-of-date python packages in `apt` which affect blockstack-core.

This will be an issue for people trying to run `blockstack-core` with browser via our apt repository (or the docker containers built using that repository).

In particular, blockstack-core depends on python-cryptography >= 2.0 (not in apt) and also python-requests >= 1.10 (not in xenial, I think)

It's not obvious to me how to solve this problem. For the docker containers, shipping them with `pip` builds is simple enough. But if someone wants to run blockstack-core outside of a container, there'll be issues...

Adding @jackzampolin for input here. Maybe we just move to install either from docker or (for devs) from pip?

**Comment by jackzampolin** [comment]
I'm def in favor of this. This would eliminate a step from our release process  (good) also would significantly simplify the install instructions and reduce confusion for users. This means we should update the core `/Dockerfile` to be more like the one here: [`/integration-tests/deployment/docker/Dockerfile.dev`](https://github.com/blockstack/blockstack-core/blob/fda07ad35a86bb867b2a6d59d697b8fbe8b2798f/Dockerfile.dev). That one works with the current launcher and I was planning on doing this reciently (want to add automated builds for each push to `master`, `develop` and `develop*`)

**Comment by jackzampolin** [comment]
I'm also going to be in the `README` today and could pull out the apt build steps.

**Comment by kantai** [comment]
Cool. Regarding the docker builds, I also went through and added `lsof` to the apt install lists in the develop branch, so make sure that gets pulled in.

I also made some edits to the `launcher` command line script while working on the windows stuff. Will add as PR on the browser repo.

**Comment by kantai** [comment]
PR #599 removes apt installation from the docker image.

**Comment by kantai** [comment]
Closing this issue for now. Getting taken over by issue here: https://github.com/blockstack/blockstack/issues/352
