### ISSUE TITLE
Story: Storage service provider

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#597]
Users should have a reliable storage service provider.

Related issues:
- Investigate using Minio Storage #584

**Comment by kantai** [comment]
This is going to end up touching three different projects:

1. gaia -> https://github.com/blockstack/gaia/issues/69
1. core -> https://github.com/blockstack/blockstack-core/issues/602
1. browser -> (no issue created yet)

Progress on gaia and core is pretty good -- at this point, I've run the blockstack todo list app with a local hub connected to a personal s3 bucket, and it "works" -- I just needed to setup the storage initialization stuff manually. We still need to add social proof checking to the hub, among some other things (probably an endpoint for obtaining config information for the hub like the hub's challenge text, etc.).

On the browser side of things, we need to add the dialog for picking dropbox or our gaia hub, and replace the dropbox init call to core with a gaia_hub init call to core (which will involve adding challenge signing code). Assuming the browser changes are going in the next sprint.

**Comment by jackzampolin** [comment]
Have the Hub passing write tests connected to actual s3 and actual Azure Blob Storage (not a great name btws). Might want to add a health check endpoint as well.

**Comment by muneeb-ali** [comment]
We decided to go ahead with Gaia Hub and @kantai has made good progress on it.

**Comment by larrysalibra** [comment]
@kantai has a pull request for this here -> https://github.com/blockstack/blockstack-browser/tree/feature/storage-service-hacks

Our plan is to get this merged in as the default storage provider for `develop` branch early in this sprint so that we can test it out.

**Comment by jackzampolin** [comment]
We have a [gaia hub](https://github.com/blockstack/gaia/tree/master/hub) deployed at `https://hub.technofractal.com`.

**Comment by shea256** [comment]
@jackzampolin @kantai @larrysalibra What's the current update here? Sounds like we have the hubs ready but we need to fully integrate them into the browser? And there's also some work to be done on verification checking?

**Comment by kantai** [comment]
There's a couple moving pieces here:

1. Verification checking works on the gaia_hub side, as long as the verifications are passed as a header. We'll need to integrate that into browser though once we have a user-flow for creating the verifications.

2. The gaia-hub driver for core and browser setup works right now without the verifications.

3. Integrating this into multi-reader storage is happening now, I'm ironing out some of the kinks in that today. If I'm still trying to run down bugs this afternoon, I think that will have to be abandoned.

**Comment by jackzampolin** [comment]
I'm waiting for @kantai to get the integration branch into a testable state and then jumping on testing.

**Comment by larrysalibra** [comment]
I'm working on on-boarding screens here: https://github.com/blockstack/blockstack-browser/issues/835

and then will merge into develop.

**Comment by larrysalibra** [comment]
This is merged into develop.

The next steps for this story in my view are:
* a review and finalization of #835 on-boarding language.
* adding proofs support including prompts in the browser if the user doesn't have enough valid proofs
* deploying the production hub

@jackzampolin can you create issues for these and coordinate the people who need to help with this?

**Comment by larrysalibra** [comment]
Here's an issue for social proofs for gaia hubs: https://github.com/blockstack/gaia/issues/71

**Comment by kantai** [comment]
Closing this-- we've moved to supporting gaia hubs and providing a default storage provider for our users. Other items we'd like to have such as easy setup of self-operated storage, etc, correspond to other user stories.
