### ISSUE TITLE
Story: Ship the hard fork

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#609]

**Comment by shea256** [comment]
From our Monday meeting we concluded that we're going to do a hard fork internal test on 9/29 and then execute the live hard fork on 10/4.

@jcnelson Anything else I'm missing here?

**Comment by jcnelson** [comment]
Yup, that's the schedule I'm aiming for.

**Comment by kantai** [comment]
Leaving this here so that we don't forget --

- [ ] We'll need to upgrade our bitcoind fleet to 0.15.0 (tagging @jackzampolin)

**Comment by jackzampolin** [comment]
No SSH access on the plane sadly otherwise I would do it now. Heres the download URL:

`https://bitcoincore.org/bin/bitcoin-core-0.15.0/bitcoin-0.15.0-x86_64-linux-gnu.tar.gz`

I can take care of this Monday.

**Comment by jcnelson** [comment]
I started a 0.17 node up last night, and so far it agrees with 0.14 (but it's only at around block 400000 right now).  The integration tests all seem to be passing.  Great work @jackzampolin on automating the integration test framework!  It really sped things up :D

**Comment by jcnelson** [comment]
My 0.17 node has reached consensus with the 0.14 node.

**Comment by jcnelson** [comment]
Hard fork successfully executed!  Happy Blockstack New Year!
