### ISSUE TITLE
python3 question

### ISSUE THREAD

**Issue by laerus** [blockstack/blockstack-core#616]
Why isn't this project written in python3?
Will it ever port?

the [Clock](https://pythonclock.org/) is ticking.

will this project continue to be in python2 
after the cpython core development team
drops support for security and bug fixes?

is this going to be abandon for an implementation in another language?

**Comment by kantai** [comment]
Hi @laerus -- these are good questions.

We currently don't have a roadmap for porting to python3, and we haven't discussed yet whether we'll do the work of porting to python3 or re-implement in a different language. However, we do plan to address this before the EOL of python2.

**Comment by kantai** [comment]
Closing this issue for now, we'll revisit as we approach the EOL of python2.
