### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by Vadorequest** [blockstack/blockstack-core#623]
I know this is still Alpha work, but I was curious so I got started. And I got lost 💃 

I installed the executable on my windows, launched Blockstack browser, waited for the install to finish, chose a password (even though I still don't know if the copy/paste worked or if I put a blank one...) and... I don't know what to do next. I've got "Blockstack is running" message. I killed it, launched it again and same message. I was expecting some kind of app, like a "browser" to open somehow and give me access to some kind of marketplace/app store.

I launched the virtualbox VM in case of, but that doesn't show up more useful info, even thou it seems to be working.

Any guidance? :)

**Comment by kantai** [comment]
When you run the Windows app "Blockstack Browser", and you get the "Blockstack is running" message, you should be able to open your native browser and go to `localhost:8888` to access the Browser.

The browser window *should* have opened automatically, so if that was the issue, that's a bug we'll have to fix in the Windows script.

**Comment by Vadorequest** [comment]
Ah, indeed. I've got something up and running there. But I had Chrome open and it didn't open any kind of new tab for http://localhost:8888/
W8.1

**Comment by kantai** [comment]
Closing this out -- this issue was resolved, and in any case, the Windows distribution has changed significantly.
