### ISSUE TITLE
Core API version number confusion 

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#628]
@yknl pointed out a confusion between v1 and v2 versions of the API.

I see where the confusion is coming from. All endpoints on core.blockstack.org are v1 other than the (legacy) resolver endpoint which is tagged as v2:

https://core.blockstack.org/#resolver-endpoints-lookup-user

I think the v2 there refers to profile version 2 or something (honestly, I don't fully remember the reasoning for the legacy resolver having the v2 version). 

We should:
- [x] Change the endpoint to use v1 to make the API version number consistent
- [x] Check if any other endpoints have this issue. I couldn't find any but someone else should double-check and confirm.
- [x] Silently support the v2/users call to continue legacy support for applications that are making these calls
- [ ] Skip the v2 version and either move to a date/time based version or at least jump to v3 directly to avoid confusion 

Let me know what you guys think.

**Comment by kantai** [comment]
I like this plan -- silently support `/v2/`, and when we switch to a better API versioning scheme (where we should revisit the suggestions @larrysalibra made about date-based versioning and trying to replicate the API versioning of stripe), make sure to skip `/v2/`

**Comment by kantai** [comment]
The only other `v2` prefixed endpoints are:

`/v2/namespaces/` and `/v2/namespace`, which have been no-ops and error responses for core.blockstack.org's entire life. I plan to simply remove those routes.

**Comment by muneeb-ali** [comment]
+1 on removing them. They will likely not impact any legacy apps. Only the v2/users endpoint will.

**Comment by kantai** [comment]
Closing this issue as `/v1/users` is now working and supported. We'll skip `v2` in the future.
