### ISSUE TITLE
Consider adding "satoshi" in the `namespace_reveal` command for UX clarity

### ISSUE THREAD

**Issue by bhessert** [blockstack/blockstack-core#646]
When running `blockstack namespace_reveal', it's unclear as to whether the units of measurement when setting base prices are in satoshis. The units are clear in the source code, but not printed in the CLI.  

Happy for one of our team to submit a PR with clearer CLI descriptions here.  

By way of example, here's some of the output from running the command:

```
Namespace ID:            helloworld2
Name lifetimes (blocks): infinite
Price coefficient:       4
Price base:              4
Price bucket exponents:  [15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
Non-alpha discount:      2
No-vowel discount:       5
Burn or receive fees?    Receive to 1Pzcb4wGHmtxFh44SCFFaEgVjL3tqf9SUC

Name price formula:
(UNIT_COST = 10.0):
                                     buckets[min(len(name)-1, 15)]
             UNIT_COST * coeff * base
cost(name) = -----------------------------------------------------
                   max(nonalpha_discount, no_vowel_discount)
```

**Comment by larrysalibra** [comment]
@bhessert awesome feed back!

> Happy for one of our team to submit a PR with clearer CLI descriptions here.

This would be amazing! Thanks!

**Comment by kantai** [comment]
This definitely adds some clarity -- thanks for the PR, it's been merged.
