### ISSUE TITLE
Failed to run `pip freeze` on Homebrew installed on macOS

### ISSUE THREAD

**Issue by cryptoquick** [blockstack/blockstack-core#650]
macOS: Sierra 10.12.6
python 2.7.14
blockstack-core version: 0.16.0.1 (trying out the multi-reader-storage branch, but the issue is still on master, as linked below)

Error:
Exception: Failed to run `pip freeze`

https://github.com/blockstack/blockstack-core/blob/a9de5d0d2e5f343738133930f374695240dadf9f/blockstack_client/rpc.py#L5293

Changing the line to `pip2` fixes the issue on my machine.

**Comment by kantai** [comment]
Hi @cryptoquick, good find -- if you submit a PR to change that to `pip2`, we'll happily merge it in!

**Comment by cryptoquick** [comment]
The problem is, I'm not sure `pip2` would work on all systems, and I think there's also a `pip3`, and my Python is a little rusty.

**Comment by jackzampolin** [comment]
This is more of an issue of having the proper python version installed (`2.7x`) rather than an issue with our software. We have that version documented in a couple of places. I'm going to go ahead and close this issue. Please re-open if applicable.
