### ISSUE TITLE
Improvements to docker install instructions

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#656]
I want to run a full node on a ubuntu virtual machine. It's 16.0.4.3 LTS.

I'm trying to follow the docker instructions on https://github.com/blockstack/blockstack-core#install-with-docker

My background is: I know what docker is. I recall installing it before as part of the discourse forum software install instructions. I've heard it makes setting up server side apps easier because you don't have to manage a bunch of dependencies. I don't use it regularly though.

I'm intentionally following instructions as they are written even when I know they won't work.

---

I downloaded the `launcher` script by clicking on "download" but it didn't download, it opened in my browser.

I realized I probably need to copy and past the script text into a file on the server.

I try to run `./launcher pull`. I get an error. Ahh I need to make the script executable. Instructions didn't tell me that.

Another error. Hmm I don't have docker installed. The instructions didn't tell me to install docker or how I can do that.

<img width="521" alt="screen shot 2017-10-21 at 2 54 38 am" src="https://user-images.githubusercontent.com/597182/31837517-ae31449a-b60b-11e7-8963-db989f5548fd.png">

I try `apt-get install docker`. It installs something. yay! I have docker!

Try to run `./launcher pull`. Hmm..the same error `docker` not found.

<img width="601" alt="screen shot 2017-10-21 at 3 01 51 am" src="https://user-images.githubusercontent.com/597182/31838005-82096e18-b60d-11e7-938c-b150d13b8a24.png">

I guess that wasn't docker?

By now I'm lost. The next step is i have to go down a rabbit hole of figuring out what docker is (because apparently `apt-get install docker` wasn't it and how to install it.

If i'm really motivated and have a lot of time, I'll go figure out how to install docker by googling around. But I came here trying to learn about blockstack, not docker. Our docker install instructions were supposed to make it faster and easier than the `pip install` instructions, but it didn't succeed in doing that.

---

I think docker install for running full code nodes on servers has the potential to make this a lot easier for everyone. It would be great if we can review the instructions and make them super easy to follow for someone with basic linux command line ability.

Discourse does this very well with their instructions for installing discourse in the cloud via docker. All you have to do is exactly follow the steps they give you and you get a discourse.

My suggestion would be to approach our instructions in the same way. Some one should be able to follow them step by step without having to assume anything more than a general ability to use the unix command line.

I really like how the discourse instructions tell you exactly what version of what operating system you should install. I don't think we need to go so far as push people to a particular cloud vendor, but telling them to start with a Ubuntu 16.04 LTS install might be a good idea so that everyone is on the same page.

**Comment by jackzampolin** [comment]
I'll go ahead and fix this.

**Comment by larrysalibra** [comment]
I figured out how to install docker on my own.

Now, I'm not sure how to start up my full node core instance. The instructions for fast sync don't work. I guess that's because i need to be in the docker container to use them?

I tried `./launcher enter` to enter into the container, but it didn't work.

<img width="635" alt="screen shot 2017-10-21 at 3 32 09 am" src="https://user-images.githubusercontent.com/597182/31838675-7eae04ec-b610-11e7-9570-4533b3402442.png">

**Comment by larrysalibra** [comment]
I gave up on docker and tried to use pip install instructions instead: https://github.com/blockstack/blockstack-core/issues/657

**Comment by jackzampolin** [comment]
https://github.com/blockstack/blockstack-core/issues/65

**Comment by jackzampolin** [comment]
https://github.com/blockstack/packaging/pull/14

**Comment by jackzampolin** [comment]
Need this issue fixed too: https://github.com/blockstack/blockstack-core/issues/658
