### ISSUE TITLE
Explain how to set up API as part of full node instructions

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#661]
I tried to set up a full node over the past couple days. 

The docker instructions didn't work for me at all (#656). The pip install instructions got the indexer running for me once I re-imaged my virtual machine with a clean install of Ubuntu 16.04. (instructions didn't tell me to do this)  However, they didn't explain to me how get the Core API running in a way that points to my node.

After installing core and letting it index, I ended up with an API endpoint pointing to node.blockstack.org. I tried changing the node.blockstack.org entry in `client.ini` to localhost, but that didn't work. Not sure if it's because another setting (https?) needs to be changed.

Instructions for setting up a full core node that don't tell you how to enable the REST api so you can actually use the full core node you've just set up aren't very useful.

As we've previously discussed, the main installation path for developers and users is downloading and installing Blockstack for their respective platform from our website. Having said that, as a decentralized platform, it's important that people can run their own nodes.  

The current documentation doesn't provide step by step instructions that work without additional guessing or troubleshooting on the part of someone following the instructions.

**Comment by jcnelson** [comment]
Hey! Does the new README.md help?  Also, have you seen this issue? https://github.com/blockstack/blockstack-core/issues/736

**Comment by jcnelson** [comment]
Closing as stale.  Also, the upcoming `develop` branch does not need any extra documentation, since the API server is built-in.
