### ISSUE TITLE
How to use Cloud storage with blockstack?

### ISSUE THREAD

**Issue by inzig** [blockstack/blockstack-core#664]
Hello guys @larrysalibra @kantai 

We have been working on real time app and we wish to store data on cloud (due to limitations of local storage). We know 0.17 release has issues with cloud storage so cloud storage is not supported in release 18. What is progress on that part because we are lagging in our app due to cloud storage part.
Or if there is workaround to use Cloud kindly share that as well.

**Comment by jackzampolin** [comment]
@inzig The browser currently uses cloud storage. I'm closing this issue as not applicable.
