### ISSUE TITLE
received unexpected HTTP status: 500 Internal Server Error

### ISSUE THREAD

**Issue by edent** [blockstack/blockstack-core#668]
Running the latest version on Linux (Blockstack-for-Linux-v0.9.1.sh).  Issue seems to be with `6a8bd10c9278` - just keeps retrying the download.

```
v0.19.1-browser: Pulling from blockstack/blockstack-core
f6fa9a861b90: Pull complete 
da7318603015: Pull complete 
6a8bd10c9278: Downloading 
d5a40291440f: Download complete 
bbdd8a83c0f1: Download complete 
a3ed95caeb02: Download complete 
e4d18368874a: Download complete 
82cea0faf768: Download complete 
83c6a3e22873: Download complete 
615090ae68c9: Download complete 
received unexpected HTTP status: 500 Internal Server Error
```

**Comment by GitMeABurrito** [comment]
Are you still experiencing this issue? I had no problem downloading the docker containers using the [launcher script](https://raw.githubusercontent.com/blockstack/packaging/master/browser-core-docker/launcher) mentioned in the readme.

**Comment by kantai** [comment]
I think this was due to a temporary outage from the quay docker repository. Closing this issue for now, you can reopen if this issue is persistent.
