### ISSUE TITLE
Password Validation Silently Fails

### ISSUE THREAD

**Issue by edent** [blockstack/blockstack-core#669]
On my first set up on Linux, I didn't notice that the password requirements were
```
Legal characters:
               letters (upper and lowercase), numbers, '_', and '-'
```

I inputted a password like `P@ssw!rd?` which it seemed to accept.  Next message was

```
Password: 
Repeat: 
Wallet does not exist yet. Setting up wallet
Unable to find image 'quay.io/blockstack/blockstack-core:v0.19.1-browser' locally
v0.19.1-browser: Pulling from blockstack/blockstack-core
```

Which gave no indication that anything was wrong.  When I later did the set-up again (and read the password restrictions) I got:

```
Password: 
Repeat: 
Wallet does not exist yet. Setting up wallet
Wallet is encrypted using your password and stored  at "/root/.blockstack/wallet.json", please make sure you create a backup.
{
    "status": true
}
```

1. Relax your password requirements.  Let me choose a strong password.
2. If you can't do that - abort the process when a non-compliant password is entered.

**Comment by jcnelson** [comment]
Closing as stale.  The Linux installer no longer does this.
