### ISSUE TITLE
Why email is required? If you talk about freedom and security

### ISSUE THREAD

**Issue by michaelScoff** [blockstack/blockstack-core#677]
You options given! 

<img width="543" alt="screen shot 2017-11-06 at 12 39 52 pm" src="https://user-images.githubusercontent.com/32179653/32462858-bf87f6ee-c2ef-11e7-85c9-13084e60fa18.png">

**Comment by john-light** [comment]
Housekeeping note: this issue is probably more appropriate for the [blockstack-browser](https://github.com/blockstack/blockstack-browser/issues) repo.

**Comment by jackzampolin** [comment]
I'm going to agree with @john-light on this one. This email is currently not used for anything. It will be used to send notifications for name transfers and other operations performed by the browser. We _*do not*_ collect those emails in any way. It just gets stored in your browser.

I've got an open issue https://github.com/blockstack/blockstack-browser/issues/1048 to allow for editing of the email you input, and opened this issue https://github.com/blockstack/blockstack-browser/issues/1168 to more proactively address concerns like yours. 

You can also always input an email matching the email regex. I use `foo@bar.com` personally.
