### ISSUE TITLE
CLI command `blockstack renew` does not work with multisig private key

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-core#679]
When using `blockstack renew` via CLI it is not possible to enter e.g. owner key as multisig key.

The schema validation expects type object for multisig but the json request just returns a string.

**Comment by kantai** [comment]
Thanks for raising this issue @friedger -- I'm looking into this now.

**Comment by jcnelson** [comment]
This is deprecated with the new CLI.

**Comment by jcnelson** [comment]
This should be fixed in the new CLI: https://github.com/jcnelson/cli-blockstack.  Once I have written a migration tool, I'll close this issue out.

**Comment by jcnelson** [comment]
Closing this out, since it's now implemented in the cli-blockstack repo
