### ISSUE TITLE
Namespace_creation.md doc is missing time restriction info

### ISSUE THREAD

**Issue by bhessert** [blockstack/blockstack-core#681]
This document does not clearly define the time restriction (or block count restriction) between preorder and reveal.  

https://github.com/blockstack/blockstack-core/blob/master/docs/namespace_creation.md

**Comment by jcnelson** [comment]
Thanks for letting me know!  I added a "Warnings" subsection to the `NAMESPACE_REVEAL`, `NAME_IMPORT`, and `NAMESPACE_READY` sections to clarify this.

**Comment by jackzampolin** [comment]
Looks like this issue has been resolved!
