### ISSUE TITLE
/v1/users 502 error on re-registered name w/ no new profile file

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#683]
I re-registered the expired name `james.id` and never created a profile file.

It's causing an error when trying to resolve using the `/v1/users` endpoint:

```
Vanquish:larrysalibra larry$ curl -I https://core.blockstack.org/v1/users/james.id
HTTP/2 502 
date: Wed, 15 Nov 2017 13:31:41 GMT
content-type: text/html; charset=UTF-8
set-cookie: __cfduid=de0821aabf499458fe754e51b5e5d55101510752700; expires=Thu, 15-Nov-18 13:31:40 GMT; path=/; domain=.blockstack.org; HttpOnly
expires: Thu, 01 Jan 1970 00:00:01 GMT
cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
pragma: no-cache
x-frame-options: SAMEORIGIN
server: cloudflare-nginx
cf-ray: 3be2927c2d63123d-HKG
```

**Comment by kantai** [comment]
This is a known error behavior:

This is what a profile resolver endpoint returns (directly)
```
< HTTP/1.1 502 BAD GATEWAY
< Server: nginx/1.10.3 (Ubuntu)
< Date: Wed, 15 Nov 2017 13:40:38 GMT
< Content-Type: application/json
< Content-Length: 91
< Connection: keep-alive
< Cache-Control: public, max-age=600
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: OPTIONS, HEAD, POST, GET
< Access-Control-Max-Age: 21600
< 
{
  "james.id": {
    "error": "Failed in parsing and fetching profile for james.id"
  }
}
```

The error 502 BAD GATEWAY is set because the resolver (in this case, acting like a gateway), fails to contact he requested resource. Unfortunately for core.blockstack.org, Cloudflare really aggressively hates 5xx errors.

So I guess a 404 is more appropriate (or at least will behave better)? When setting this error code, I went with 502 because it seemed that the blame for the error lay with the server and backend configuration (so a 5xx error), rather than a 4xx error which is usually a user error.

**Comment by larrysalibra** [comment]
@kantai 

Yeah that's a dilemma. Another option would be to return a `200` response with an empty profile since there's no valid profile, the user request was valid (the name exists) and the server is working fine.

As to how to fix the related explorer problem, it looks like we should use the `https://core.blockstack.org/v1/names/larry.id` look up to see if a name exists and for the zonefile result and this `https://core.blockstack.org/v1/users/larry.id` user lookup only for profile resolving. 

Tagging @yknl on this.

**Comment by kantai** [comment]
> Yeah that's a dilemma. Another option would be to return a 200 response with an empty profile since there's no valid profile, the user request was valid (the name exists) and the server is working fine.

That should work-- do we want to include the error message, or just return a blank profile?

**Comment by kantai** [comment]
Updated on core.blockstack.org and merged into master.

Example:
https://core.blockstack.org/v1/users/blanks.id

Returns 200 Response + the error message

Closing for now, can reopen if we want other behavior.
