### ISSUE TITLE
After migrating from legacy with setup_wallet, the new wallet can't see my names

### ISSUE THREAD

**Issue by hudon** [blockstack/blockstack-core#684]
Hello!

**Setup:**
I had a "legacy" wallet and I wanted to see which names I own. I ran `blockstack wallet` and it complained about it being a legacy wallet so I ran `blockstack setup_wallet`.

This created a new `wallet.json` and backed up my legacy one in `wallet.json.legacy.<some number>`

**Problem:**

I expect to now see my names when I do `blockstack wallet`, but I do not.

I also noticed that the wallet that was created has a different owner address than the legacy wallet.

I have confirmed that the owner address in my legacy wallet matches the owner of my name by running `blockstack whois <name>`. But the owner address of my new wallet does not match.

Please let me know if I missed a step to complete the migration! Maybe I need to explicitly create a new wallet and send over the name from my old owner address? Or does the different owner address have the same underlying private key so it's just a UI issue?

**Comment by jcnelson** [comment]
Hey @hudon, sorry to hear you're having trouble!

What probably happened is your owner private keys were converted from a compressed public key address to an uncompressed public key address, or vice versa (a bitcoin private key has two addresses).  We can confirm as follows:

* Run `blockstack api start`
* Run `blockstack wallet`
* Using your owner private key, run: 
```python
python -c 'import keylib; import sys; print keylib.public_key_to_address(keylib.key_formatting.decompress(keylib.ECPrivateKey(sys.argv[1]).public_key().to_hex())); print keylib.public_key_to_address(keylib.key_formatting.compress(keylib.ECPrivateKey(sys.argv[1]).public_key().to_hex()))' YOUR_PRIVATE_KEY
```

Example:
```bash
$ python -c 'import keylib; import sys; print keylib.public_key_to_address(keylib.key_formatting.decompress(keylib.ECPrivateKey(sys.argv[1]).public_key().to_hex())); print keylib.public_key_to_address(keylib.key_formatting.compress(keylib.ECPrivateKey(sys.argv[1]).public_key().to_hex()))' c10cc5a6ee903a47d0f0fa05c784f3f42d5609ff4d3fd11fa67a70a5e948e61d01
1NLsvhVSqqKkHE9Q389RWo3X16EYXMFmbn
14ip5mEpwzjZqWagbPCxdkYuyqKJpfFNm3
```

If one of the addresses matches your name in `blockstack whois`, then this was the problem.

**Comment by hudon** [comment]
right on that's it. The new wallet deals only with the compressed pubkey I guess. Hmm. I'd still expect `blockstack names` to show me any name owned by the owner prvkey

**Comment by jackzampolin** [comment]
This is likely because you also updated the browser and switched to using the browser wallet. You need to track this issue on the name migration tool: https://github.com/blockstack/blockstack-browser/issues/619

I'm closing this in favor of that issue. If this was closed in error, please reopen.
