### ISSUE TITLE
Importing "master_private_key": “df484533kf5mzv83892a234a44ae9z83m832987a82mqwmdkks018121204v95las9"

### ISSUE THREAD

**Issue by Omar-Itani** [blockstack/blockstack-core#688]
The wallet format was updated so I am unable to import the private key. Here is an example of the older backup format:
   "master_private_key": “df484533kf5mzv83892a234a44ae9z83m832987a82mqwmdkks018121204v95las9"

In order to import this key into CLI, I need to download an older version? If so, which version? Or is there an easier way to get access to my BTC/BCH?

**Comment by kantai** [comment]
You can use the command:

```bash
$ blockstack import_wallet
```

To set the current wallet to use that private key -- the current set up uses three different keys, and you can set your key for all of them.

Alternatively, if you just want to get the BTC out of the private key -- most BTC wallet software will allow you to import a private key directly -- this hexstring should be importable in most software wallets.

**Comment by jackzampolin** [comment]
Closing this as resolved. If this is still an issue please reopen.

**Comment by Omar-Itani** [comment]
Hello, I downloaded the CLI but there is no "import_wallet" command. I believe for the "send_btc" command you need a payment key but with the "get_payment_key" command you must have a 12 word passphrase....however all I have is a 66 character "master_private_key"
It would be much easier if I could find a wallet that would allow me to just import my 66 character "master_private_key" but I have not found any....does anyone know of any?
