### ISSUE TITLE
"API Endpoint fails to start, and API setup fails"

### ISSUE THREAD

**Issue by 20jsg17** [blockstack/blockstack-core#691]
Here it is AaronB - and thanks again.

> /tmp/blockstack-venv/bin/python

 /tmp/blockstack-venv/bin/blockstack setup -y --password password
Saving configuration to /Users/GLF/.blockstack/client.ini
{
   "error": "Unexpected error:
Traceback (most recent call last):
 File \"/tmp/blockstack-venv/bin/blockstack\", line 55, in <module>
   result = run_cli()
 File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/cli.py\", line 557, in run_cli
   result = method(args, config_path=config_path)
 File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py\", line 370, in cli_setup
   res = cli_setup_wallet(wallet_args, interactive=interactive, config_path=config_path, password=password)
 File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py\", line 2264, in cli_setup_wallet
   res = wallet_setup(config_path=config_path, interactive=interactive, password=password)
 File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/wallet.py\", line 1225, in wallet_setup
   res = initialize_wallet(wallet_path=wallet_path, password=password, interactive=interactive)
 File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/wallet.py\", line 758, in initialize_wallet
   wallet = make_wallet(password)
 File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/wallet.py\", line 220, in make_wallet
   payment_privkey_info = virtualchain.make_multisig_segwit_wallet(2,3) if payment_privkey_info is None and not test_legacy else payment_privkey_info
 File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/virtualchain/lib/blockchain/bitcoin_blockchain/multisig.py\", line 199, in make_multisig_segwit_wallet
   return make_multisig_segwit_info(m, [pks])
 File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/virtualchain/lib/blockchain/bitcoin_blockchain/multisig.py\", line 117, in make_multisig_segwit_info
   priv = BitcoinPrivateKey(pk, compressed=True)
 File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/keylib/private_key.py\", line 37, in __init__
   secret_exponent = encode_privkey(private_key, 'decimal')
 File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/keylib/key_formatting.py\", line 379, in encode_privkey
   return encode_privkey(decode_privkey(priv), formt, vbyte)
 File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/keylib/key_formatting.py\", line 358, in decode_privkey
   formt = get_privkey_format(priv)
 File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/keylib/key_formatting.py\", line 281, in get_privkey_format
   bin_p = b58check_to_bin(priv)
 File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/keylib/key_formatting.py\", line 235, in b58check_to_bin
   leadingzbytes = len(re.match('^1*', inp).group(0))
 File \"/tmp/blockstack-venv/lib/python2.7/re.py\", line 141, in match
   return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
",
   "help": "Try getting latest version of CLI with \"sudo pip install blockstack --upgrade\""

> 

> }

**Comment by kantai** [comment]
Thanks for bearing with me to find this!

It turns out that this is a pretty significant bug.

**Comment by 20jsg17** [comment]
I am glad I persisted in trying finding the right person to communicate with as I knew there was something going on...

**Comment by jackzampolin** [comment]
Looks like this is resolved! Closing.
