### ISSUE TITLE
Serverless functions

### ISSUE THREAD

**Issue by Sach97** [blockstack/blockstack-core#693]
Hi everyone, just heard about blockstack. Is it possible to make serverless functions the AWS way inside a blockstack core container? Running micro services with Blockstack would be a killer feature.

**Comment by jackzampolin** [comment]
@Sach97 The question you are asking is a bit confused. `serverless functions the AWS way` are a central platform executing code for you for a fee. If you are running a `blockstack-core` container yourself, you necessarily have some compute that you could run arbitrary code on.

This sounds more like a topic for forum discussion than an issue. If you are interested in discussing further please start a post on our forum: [forum.blockstack.org](https://forum.blockstack.org)
