### ISSUE TITLE
Allow export of browser identity to CLI

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-core#698]
Give users the ability to load the 12 word keychain phrase generated in the browser into their cli so that they can programmatically utilize their ids.

**Comment by ericgay** [comment]
👍 This would be great. Also open to any temporary hacks to pull out the data, no matter how dirty.

**Comment by cryptocracy** [comment]
Ya this would be a great utility to have for Souq !

**Comment by vsund** [comment]
Definitely would be a really handy feature to have an easy way to generate the keychain from it. Also enables things like hardware tokens for identity (see https://github.com/blockstack/blockstack-apps/issues/19) 🎉

**Comment by jcnelson** [comment]
This is implemented in the new CLI (https://github.com/jcnelson/cli-blockstack)
