### ISSUE TITLE
Threading blockstackd

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#699]
As of now, `blockstackd` handles requests single-threaded -- It may be possible to significantly improve the responsiveness of `blockstackd` through adding threading into the SimpleXMLRPCServer. However, responsiveness during the handling of database _updates_ will still be low -- as read operations in sqlite are serialized when a write lock is held -- we could enable WAL mode, which would allow reads to happen concurrently with writes, however, that may not be necessary.

**Comment by jcnelson** [comment]
In `feature/token-v1` and `develop`, I have modified the code to make the *network* requests multi-threaded (up to a maximum number of RPC threads), but the individual RPC invocations remain serialized for the time being.

**Comment by jcnelson** [comment]
I think we've done all we can here for the foreseeable future.  Going to go ahead and close this.
