### ISSUE TITLE
Atlas: NAT traversal

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#704]
Add support to the Atlas network for serving zone files from behind NATs, and connecting to peers from behind NATs.

**Comment by jcnelson** [comment]
Just a few notes to myself on this.

* We currently use [pystun](https://github.com/jtriley/pystun) in Atlas in order for a node to automatically detect its public IP address.  If we implement NAT traversal, we'll also need to make sure that nodes periodically re-query their IP address (or detect that they need to re-query it).

* Atlas nodes should be careful about adding short-lived nodes to their peer set.  One way to achieve this could be to have a node propagate a peer proportional to `1.0 - peer_health * 1.0 / peer_uptime`.  This would make it unlikely that a recently-joined peer would be propagated, and it would make it unlikely that a long-lived but unhealthy peer would be propagated.  However, it would make it much more likely that all peers learn about all the long-lived healthy peers.  Need to investigate the trade-offs of this, though---we don't want it to be the case that the network gets held together by a handful of superpeers that, if taken offline, would lead to a network partition.

**Comment by larrysalibra** [comment]
I'd be hesitant about adding NAT traversal to Atlas. It has the potential to add a lot of unnecessary  complexity.  Was there a discussion about doing this somewhere already?

**Comment by jcnelson** [comment]
I don't recall having a discussion about *never* doing it...just about not doing it at first.

I agree that NAT traversal is a low-priority concern, because as long as there is at least one publicly-routable Atlas node that a zonefile-sender can reach, then all Atlas nodes behind all NATs will eventually be able to fetch the zone file (since they'll each pull it from the publicly-routable node).

The problem I'm trying to solve is make it so the network can continue to operate even if all publicly-routable Atlas nodes get shut down (i.e. through DDoS, through misconfiguration, etc.).  I don't expect NAT traversal to be 100% reliable for 100% of peers, but all we need to have work for this is make it so some peers can at least be contacted if there are no publicly-routable peers.

In terms of prioritization, making the network more reliable by pushing zone files to one another and adding code to ban misbehaving and short-lived peers should come first.  Once these are in place, then we can think about adding support for NAT-traversing nodes that e.g. run on your laptop and frequently switch IP addresses and go offline.

**Comment by jcnelson** [comment]
Closing as stale.  We'll worry about this once we have a push-based peer network.
