### ISSUE TITLE
Nameops: include new zone file hash in `transfer`

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#709]
It would be nice if, when transferring a name, a new zone file hash could be set.  This would make it easier to migrate a name's zone file's Gaia URLs all in one go.

**Comment by kantai** [comment]
Completely agree -- because I couldn't do this, I've been sending renews instead of transfers.

**Comment by jcnelson** [comment]
We probably won't get to this until after the Stacks chain is live, and at that point, we'll be overhauling the entire state engine anyway.  Closing as stale.
