### ISSUE TITLE
Subdomain Registrar: Names aren't batched efficiently

### ISSUE THREAD

**Issue by freethejazz** [blockstack/blockstack-core#712]
After initial startup and queueing up a large list of names, zonefiles will start with only 1 subdomain TXT record. Each time a zonefile gets created, the number of subdomain TXT records is incremented by 1 (perhaps until the 4kb limit, but I haven’t pushed it that far yet). However, I expect each zonefile to be as close to the 4kb limit as possible, right off the bat.

Steps to reproduce:
```# Kick off the registrar scenario
docker run -dt -v /tmp/bs:/tmp quay.io/blockstack/integrationtests:develop blockstack-test-scenario --interactive 2 blockstack_integration_tests.scenarios.subdomain_registrar

# Wait for the test to complete
docker logs -f <container id> | grep inished

# Hop in
docker exec -it <container id> bash

# All the following are executed w/in the docker container
# Set env vars properly
export BLOCKSTACK_TEST=1
export BLOCKSTACK_TESTNET=1
export BLOCKSTACK_DEBUG=1
export BLOCKSTACK_CLIENT_CONFIG=/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.subdomain_registrar/client/client.ini

# Create a bunch of subdomain registration requests
for i in {1..100}; do
  curl -X POST --data '{"zonefile": "$ORIGIN foo'"$i"'\n$TTL 3600\n_file URI 10 1 \"file:///tmp/foo'"$i"'.profile.json\"\n", "name": "foo'"$i"'", "owner_address": "14x2EMRz1gf16UzGbxZh2c6sJg4A8wcHLD"}' http://localhost:7103/register/
done

# Observe the zonefiles as they start getting registered
blockstack list_zonefile_history foo.id
```

This has to do with a few things. First, the `entries_per_tx_hint` variable, which controls how many queued registrations are queried from the database, is being set after ever batch of registrations, regardless of why the batch was a certain size. It makes sense to save the hint if a batch was scaled down due to size constrictions. However, when the size was low due to a low queue volume, the hint shouldn't be saved. The other is that the logic to increase the number of entries in each batch is spread out over multiple batches (one more each batch), instead of packing in the most zonefiles it can in a single run.

Here's a pseudo-code sketch of how I imagine this logic should work:
```
global zonefile_limit = 4096
global entries_per_tx_hint = 24
global domain = foo.id

function maximizeSubdomains() {
  rows = getQueuedRegistrations(entries_per_tx_hint);
  local zf_init = createZonefile(domain);
  local txtRecords = rows.map { row =>
  }
}
```

When batching queued subdomain requests, I'd expect it to work something like:
1. Query for `entries_per_tx_hint` number of rows (initial value is 24)
1. Try to create a zonefile with all results.
1. If zonefile is too big:
   1. Remove zonefiles and check size until we're under the limit. This could be simple (`-1` each time) or smart (determine size of each TXT entry and calculate how many you need to remove in one shot)
   1. update the `entries_per_tx_hint` with resulting number of rows
1. If zonefile is significantly less than our limit
   1. Query more rows
   2. Go through the above process
   3. Update `entries_per_tx_hint` with the number of rows we settle on

If step 1 returns less than `entries_per_tx_hint` and they can all fit in the zonefile, don't update `entries_per_tx_hint`

**Comment by kantai** [comment]
Yep, now the subdomain registrar figures out how many operations it can
pack in a zonefile directly from the zonefile size configuration variable.

**Comment by jcnelson** [comment]
Cool!  Will go ahead and close this then.
