### ISSUE TITLE
Core Node Runs Slowly

### ISSUE THREAD

**Issue by freethejazz** [blockstack/blockstack-core#713]
I've got several core nodes running and I get very slow performance from RPC requests. When calling the `getinfo` request, I'm getting response times between 30s and 60s. Very occasionally, I get an immediate response, but I haven't been able to replicate it enough to determine circumstances to reliably produce it. I've tried everything below multiple times on fresh infrastructure and have gotten the same results each time, with one exception (see **Curiosities** below).

**The "Metal"**
One core node process running in a docker image that's running on a m4.large EC2 instance. The base operating system on the EC2 instance is the standard Amazon Linux AMI.

**The Setup**
On the base AMI:
- Install docker and start the service:
```
yum -y install docker
service docker start
```
- create directory structure for data:
```
mkdir -p /data/{server,api}
```
- Write basic configuration for the blockstack server:
```
printf "[bitcoind]\np2p_port = 8333\nregtest = False\nspv_path = /root/.virtualchain-spv-headers.dat\nserver = bitcoin.blockstack.com\npasswd = blockstacksystem\nuser = blockstack\ntimeout = 300\nport = 8332\nuse_https = False\n[blockstack]\nemail = foo@bar.com\nserver_version = 0.17.07\n" > /data/server/blockstack-server.ini
```
- Bootstrap the core node with `fast_sync`
```
docker run -a stdout \
    -v /data/server/:/root/.blockstack-server/ \
    --name blockstack-core-init \
    quay.io/blockstack/blockstack-core:v0.17.0.14 \
    blockstack-core --debug fast_sync http://fast-sync.blockstack.org/snapshot.bsk > /dev/null
```
- When the fast_sync has completed, start the blockstack server, exposing the port out to the instance:
```
docker run -d \
    -v /data/server/:/root/.blockstack-server/ \
    -v /data/api/:/root/.blockstack/ \
    -p 0.0.0.0:6264:6264 \
    quay.io/blockstack/blockstack-core:v0.17.0.14 \
    blockstack-core start --debug --foreground
```
- Then, wait for the core node to catch up the rest of the way

**One slow call**
```
curl -X POST \
  http://my.ec2.hostname.or.ip:6264/RPC2 \
  -H 'content-length: 95' \
  -H 'content-type: application/xml' \
  -d '<?xml version="1.0"?><methodCall><methodName>getinfo</methodName><params></params></methodCall>'
```
**Resource consumption during the above call**
`top` reports half of the available memory free
`top` reports very little CPU usage. I saw it "spike" to 1.38% for one refresh a three times.
`iotop` reports disk activity to be basically nothing

The layered filesystem of docker shouldn't play into this, because I'm mounting all the data in as a volume.

**Curiosities**
Using identical steps (via a user-data script attached to a launch configuration) on a t2.small, I was able to get great response times for hundreds of costlier requests (crawling through zonefile history of the `.id` namespace) for a short amount of time.

**Some possibilities**
I dug around to try to find external causes for sluggishness, since it doesn't appear the core process is doing any work during the 30-60 seconds it takes to get a response.

- Slow Performance by `bitcoin.blockstack.org`. The core node is configured to use this as a bitcoind node and bitcoind is used in the `getinfo` call: https://github.com/blockstack/blockstack-core/blob/master/blockstack/blockstackd.py#L827
- Contention on the local file that contains info about the last block? https://github.com/blockstack/blockstack-core/blob/master/blockstack/lib/nameset/virtualchain_hooks.py#L181

What do you all think?

**Comment by jcnelson** [comment]
Hey @freethejazz, thank you for your detailed report!

We've been feeling this pain-point recently as well.  I think your intuition is correct--the slow part of `rpc_getinfo()` is the call to the bitcoin node.  Have you tried spinning up a colocated bitcoin node and pointing your Core node at that one instead?

Specific to `rpc_getinfo()`, the response from `bitcoin.blockstack.org` can be cached by the Core node, since it doesn't change all that often (i.e. once per 10 minutes on average).  It does not do this right now. 
 This is on my engineering plate this week, among some other benchmarking and optimization tasks.

**Comment by jcnelson** [comment]
I'm just going to list some notes on some known slow paths here that I'm going to focus in improving...

  - `rpc_get_all_names()`
    - change pagination from 100 names to 50, or 25, or 10 (needs evaluation; see #701)
    - 100-name page size takes ~500 milliseconds to process
  - `rpc_getinfo()`, `rpc_ping()`, `success_response()`
    - Cache bitcoind block height and consensus hash to avoid DB read (#702)
    - can keep coherent via `index_blockchain()` thread
  - `rpc_get_name_blockchain_record()`
    - Returns name history as well, so O(n) in number of name transactions
    - Add complementary RPC method that does NOT return history (#716)
      - affects `GET /v1/users`
      - affects `POST /v1/names`
      - affects `GET /v1/names/{:name}/zonefile`
      - probably more
  - `rpc_get_name_at()`, `rpc_get_nameops_affected_at()`
    - Very slow in `master`, since it replays history (O(n))
    - Much faster in `feature/clean-chainstate`, since it leverages new chainstate DB in virtualchain’s `develop` branch (O(1))

**Comment by jackzampolin** [comment]
Some thoughts on the above:

* I would caution moving the max number of names returned by `rpc_get_all_name()` down without some benchmarking. This could potentially be slower for iterating through all the names. 
* Cached block height 🙌 
* Complementary RPC method that doesn't return history 💯 🙌 🎉 💥 
* O(n) -> O(1) Awesome!

**Comment by jcnelson** [comment]
Regarding `rpc_get_all_names()`, one option might be to calculate a name's "id" as `int(sha256(name,register_block_height)[0:16])` (i.e. the upper 64 bits of the SHA256 of the name and the block at which it was registered).  This would get us a deterministic and roughly even distribution of name IDs over the range `[0, 2**63)`.  Then, to select page `p`, you would:

* find the number of unexpired names (`SELECT COUNT(name) FROM ... WHERE (unexpired)`).  If zero, then return.
* calculate id range `R` as `2**63 / num_unexpired_names`
* make sure the signed values `p * R` and `(p + 1) * R` fit into 63 bits
* run `SELECT name FROM ... WHERE id >= p * R AND id < (p + 1) * R`

**Comment by jcnelson** [comment]
All but the `rpc_get_all_names()` calls have been sped up in 0.18.  I'm going to move the `rpc_get_all_names()` performance bug to #701.

If there are no other problems, can we close this issue?

**Comment by jackzampolin** [comment]
We can go ahead and close this. I need to get you a benchmark from these new `v0.18` servers too.
