### ISSUE TITLE
Monitoring: add test for bitcoind block height and consensus hash

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#719]
Add a monitoring service we can ping with Runscope that will monitor core.blockstack.org and/or node.blockstack.org to make sure that they don't "fall behind" the main chain.  This service should return an error if the target service (core.blockstack.org, node.blockstack.org) gets too far behind its colocated bitcoind node.  We can have Runscope monitor it so we get notified.

**Comment by jcnelson** [comment]
To the best of my ability to determine, this is what happened to `5cb1f7541764474e07cc01c9c28fdc780c43c650d099ce131a6ced9a86009ab6`.  The `node.blockstack.org` public nodes got stuck at block 504275 for ~12 hours because they were unable to receive new blocks from `bitcoin.blockstack.org` (likely due to network issues in Azure).  As such, they kept serving a stale consensus hash, which this transaction incorporated.  The monitoring service should let us know when the Core node's consensus hash and the Bitcoin chain tip get too far out of sync (e.g. by more than 12 blocks, say).

**Comment by jackzampolin** [comment]
I can add this to my to-dos if you would like.

**Comment by jcnelson** [comment]
Fixed in clients.
