### ISSUE TITLE
Subdomains: allow any name to send subdomain updates for any existing subdomain

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#726]
Right now, updates to a subdomain can only be done through the owner of the stem name.  That is, the only way to send an update to `jude.blockstack.id` is to send a `NAME_UPDATE` for `blockstack.id`.

This does not have to be the case.  Instead, *any* name ought to be able to send a `NAME_UPDATE` that incorporates an update for a subdomain.  This lets subdomain owners recover from lost or unresponsive name owners.

However, there are two constraints that have to be enforced:
* A subdomain must *originate* on its stem name.  That is, `jude.blockstack.id` has to be created by `blockstack.id`.  It cannot be created by `jude.blockstack2.id`.
* A subdoman will only be created if *all prior zone files* for the stem name are known in advance.  This is to prove the *absence* of any prior subdomain creation operation on this subdomain.  It cannot be the case that `jude.blockstack.id` gets registered twice; enforcing the above two constraints lets us do this.

**Comment by jcnelson** [comment]
So there's actually one more subtle problem to solve here:  a subdomain's history in the set of zone files can get reorganized with the arrival of *any* previous zone file.  This has a profound consequence for the security of subdomains: **a subdomain can be stolen or invalidated through a reorg.**

Here's how.  Suppose I successfully create `jude.blockstack.id`, and I transfer it from address `1AA` to `1BB`.  My subdomain history might look like this:

```
jude.blockstack.id seq=0 address=1AA zonefile=XXX accepted=1 parent_index=5
jude.blockstack.id seq=1 address=1BB zonefile=XXX accepted=1 parent_index=12
jude.blockstack.id seq=2 address=1BB zonefile=YYY accepted=1 parent_index=19
```

Here, the `parent_index` is the index into the blockchain-ordered list of zone files that identifies the zone file that included the subdomain operation.  For the sake of this example, the zone file at `parent_index=5` was from a `NAME_UPDATE` on `blockstack.id`, so this history is valid.  The zone files at `parent_index=12` and `parent_index=19` do not have to be from `blockstack.id`, per this issue.

Now, here's the problem.  Suppose the subdomain transfer at `seq=1` is the result of me selling the subdomain to a different person.  Suppose now that I want to *defraud* this person.  I can easily do so by sending a `NAME_UPDATE` at any `parent_index=6` through `parent_index=11` whose zone file includes a *different* `seq=1` subdomain record for `jude.blockstack.id`.  I do not announce this zone file at first, so the transfer to address `1BB` is accepted for some time.

When I want to defraud the recipient, I send my alternative subdomain record and reorganize this subdomain's history.  Here's what it might look like if the missing zone file was added at `parent_index=7`:

```
jude.blockstack.id seq=0 address=1AA zonefile=XXX accepted=1 parent_index=5
jude.blockstack.id seq=0 address=1CC zonefile=ZZZ accepted=1 parent_index=7
jude.blockstack.id seq=1 address=1BB zonefile=XXX accepted=0 parent_index=12
jude.blockstack.id seq=2 address=1BB zonefile=YYY accepted=0 parent_index=19
```

Since the subdomain record at `parent_index=7` transfers the subdomain to `1CC`, it *invalidates* the history at `parent_index=12` and `parent_index=19`.  A query to `jude.blockstack.id` would now return `address=1CC` and `zonefile=ZZZ`, whereas before it would have returned `address=1BB` and `zonefile=YYY`.  This is obviously a problem.

**Solution**:  My proposed solution to this problem is to allow a subdomain record to set a list of domain names that can issue transfers.  They would be set when the subdomain is created, and when the subdomain address is changed.  Then, an address change would only be accepted into the subdomain's history if *each* domain name's full zone file history was already present (i.e. to prove the absence of any missing address changes).  This could be used to prevent me from defrauding the user simply by omitting `blockstack.id` as an allowed domain name.

Here's how the history might look before my attempted reorg attack, but with this solution applied:

```
jude.blockstack.id seq=0 address=1AA zonefile=XXX accepted=1 parent_index=5 care_of="foo.id,bar.id"
jude.blockstack.id seq=1 address=1BB zonefile=XXX accepted=1 parent_index=12
jude.blockstack.id seq=2 address=1BB zonefile=YYY accepted=1 parent_index=19
```

The record at `seq=0` states that only the names `foo.id` and `bar.id` are allowed to change the address of the subdomain `jude.blockstack.id`.  That way, when I send my subdomain update at `parent_index=7`, the history would look like this:

```
jude.blockstack.id seq=0 address=1AA zonefile=XXX accepted=1 parent_index=5 care_of="foo.id,bar.id"
jude.blockstack.id seq=0 address=1CC zonefile=ZZZ accepted=0 parent_index=7 care_of="blockstack.id"
jude.blockstack.id seq=1 address=1BB zonefile=XXX accepted=1 parent_index=12
jude.blockstack.id seq=2 address=1BB zonefile=YYY accepted=1 parent_index=19
```

My history entry would be rejected because it did not come from either `foo.id` or `bar.id`.

Note that this still requires that the system know about *all* of `foo.id` and `bar.id`'s zone files.  Otherwise, they could reorganize the subdomain history and defraud the user.

I'm thinking that a subdomain user can set the `care_of` list to at most five different names.  This gives the user some choice in who they can contact (only one of them has to succeed in sending a `NAME_UPDATE` to include their address change), and it keeps the number of database queries we'd need to do server-side to a manageable amount.

What do you think? @kantai

**Comment by kantai** [comment]
I agree that we should require users to delegate authority to different names to be able to issue updates there as well. _However_ I think we should hold off on spec'ing and building out that feature until another sprint. For now, I think user's subdomains should only be able to be updated by the originating domain name.

Also, about the above:

> A subdoman will only be created if all prior zone files for the stem name are known in advance. This is to prove the absence of any prior subdomain creation operation on this subdomain. It cannot be the case that jude.blockstack.id gets registered twice; enforcing the above two constraints lets us do this.

I believe that this behavior should be enforced by clients, not by `blockstackd` -- like, ultimately,the client should display a warning to users that the domain still has outstanding zonefiles -- and if a conflict occurs at a later time, the user would at least have proof of the domain operator's misbehavior (the domain operator would have knowingly issued two different, conflicting, registrations for the same subdomain.

The case I'm trying to avoid is basically 'missing zonefiles due to errors cause a domain to become useless'.

**Comment by jcnelson** [comment]
> I believe that this behavior should be enforced by clients, not by blockstackd -- like, ultimately,the client should display a warning to users that the domain still has outstanding zonefiles -- and if a conflict occurs at a later time, the user would at least have proof of the domain operator's misbehavior (the domain operator would have knowingly issued two different, conflicting, registrations for the same subdomain.

Doesn't this make subdomain lookups just as expensive as they were when done client-side?  i.e. each lookup still has to process a subdomain's history?

**Comment by jcnelson** [comment]
How about this for this sprint?
* Subdomains can only be created by their domain names.
* Any domain name can broadcast a subdomain zone file update, but not an address change.
* Only the original domain name can send an address change, and it will only be considered valid if the domain has all of the previous zone files up to that point.

We can worry about `care_of` and on-chain recovery in the next sprint.

**Comment by kantai** [comment]
> How about this for this sprint?
>
>  *  Subdomains can only be created by their domain names.
>  *  Any domain name can broadcast a subdomain zone file update, but not an address change.

That sounds good to me.

Regarding your earlier comments:

> Doesn't this make subdomain lookups just as expensive as they were when done client-side? i.e. each lookup still has to process a subdomain's history?

Why? We could support a query that allows the client to find out whether or not a given domain has any missing zonefiles earlier than some transaction. This query is cheap for the indexer, and cheap for the client.

>Also, if any zone file is missing, then wouldn't this make warnings into false positives in many cases?

Not sure I understand this -- in this case, wouldn't it be _worse_ if blockstackd just didn't process any subdomain registrations?

In general, I think it's possible that `blockstackd` refusing to process subdomain updates if a zonefile is missing can work, but it's really important that if that's the case, we have a plan for dealing with missing zonefiles due to errors or bugs (after all, there are many missing zonefiles currently) before shipping that behavior.

**Comment by jcnelson** [comment]
> Why? We could support a query that allows the client to find out whether or not a given domain has any missing zonefiles earlier than some transaction. This query is cheap for the indexer, and cheap for the client.

Gotcha.  I misunderstood what you were asking--I thought you were suggesting that the client fetch all zone files and replay the subdomain history locally.  This makes sense though---it would let a client detect dishonesty on the domain operator's part.

> In general, I think it's possible that blockstackd refusing to process subdomain updates if a zonefile is missing can work, but it's really important that if that's the case, we have a plan for dealing with missing zonefiles due to errors or bugs (after all, there are many missing zonefiles currently) before shipping that behavior.

I think the design decision we're trying to make is whether or not we want the zonefile arrival schedule to influence the subdomain index's view of a subdomain's address.

I think @kantai is saying that the view does not need to be stable---a subdomain's address can retroactively change with the arrival of a missing zonefile.  The arguments for this are that (1) it allows subdomain processing to continue in the face of missing zone files, and (2) if we require the domain to process all address transfers, then the client can efficiently detect whether or not the subdomain view is stable based on whether or not the domain is missing any zone files after the subdomain was created.

My argument was that the view does need to be stable---a subdomain's address cannot retroactively change due to a zone file arrival.  My argument was that doing otherwise allows an attacker to trick other users into trusting the wrong key for a subdomain by controlling the arrival schedule.  The downside of this approach is that any missing zone files from the domain(s) that process address changes for a subdomain cannot get lost; otherwise subdomains from that domain would not be able to be processed.

Having talked this through more, I'm more inclined to agree with @kantai for the following reasons:
* Only the subdomain owner can create address-change TXT records in the first place, so a user signing up for a subdomain is unlikely to reorg her own subdomain history (doing so would break her applications).
* A user would not create a subdomain on a domain name that is missing zone files in the first place (otherwise their subdomain would not resolve).
* A user should not be blocked from updating their zone files based on the creator domain's bad behavior.

Nevertheless, it should still be the case that only the domain name can process address changes.  The reason is that clients still need an efficient way to detect subdomain view instability.  Constraining the set of domains that can process address changes to just the domain that created it would mean that a client only needs to check the domain name's zone file history to verify that all zone files are present.  If we did not do this, then *any* missing zone file could be a source of view instability.

**Comment by jcnelson** [comment]
Update: sounds like we have a plan:  When creating or transferring a subdomain record, the creator also provides a list of the registrar's domain's known-missing zone files.  The registrar only incorporates the subdomain record if the list of known-missing zone files is consistent with its view of the Atlas network.  Then, the domain can tolerate the loss of prior zone files, and should they be discovered later (and invalidate any subdomains), clients can efficiently detect them and in doing so catch the registrar in a lie.

Subdomains can be updated on any zone file, but can only be created or transferred on the domain that created them.  The only reason for this constraint is to make catching the registrar in a lie efficient, since it limits the number of zone files the client needs to query.

**Comment by kantai** [comment]
One note -- the client, on registering (or transferring) -- needs to perform the following check when the registrar's zonefile for that operation propagates:

1. That the entry's public-key matches the one they submitted
2. That their missing-zone-file-view matches the one broadcasted by the domain operator

The user should have an indication that their subdomain is _pending_ until this check is performed and validated.

**Comment by jcnelson** [comment]
Merged to `develop`

**Comment by jcnelson** [comment]
Merged to `master`
