### ISSUE TITLE
Implement subdomain registrar independent of blockstack-client.

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#730]

**Comment by jcnelson** [comment]
This looks like a dup of #725.  Shall I close #725 in favor of this one?

**Comment by kantai** [comment]
This is implemented and working in this repo: https://github.com/kantai/subdomain-registrar

In addition to its unit test suite, I tested in regtest and mainnet with a couple of subdomain registrations -- the only issue is core.blockstack.org's subdomain indexer is broken right now -- a fix is pushed, but the service will need to be rolled over to incorporate that fix.

**Comment by kantai** [comment]
This is completed -- the independent subdomain registrar code lives at https://github.com/blockstack/subdomain-registrar
