### ISSUE TITLE
Make snapshot pubKey configurable

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-core#732]
If this is done then users can host and rely on their own snapshot server.

**Comment by jcnelson** [comment]
I don't know what you mean by this?  You can set your own snapshot server private key; you'll just need to have your users pass in the right public key when they run `fast_sync`.

**Comment by jackzampolin** [comment]
Ok, maybe this is a misunderstanding of how this works, and if so forgive me. Is there a flag you can pass in for `pubKey` when running `fast_sync`? Also is there any documentation on how to generate the `pubKey` and `privKey` for this service?

**Comment by jcnelson** [comment]
It's a secp256k1 keypair.  Any Bitcoin library can generate one.  I use `virtualchain`:

```
$ cat ~/bin/ecdsa_privkey
#!/usr/bin/python
import virtualchain
print virtualchain.lib.ecdsalib.ecdsa_private_key(compressed=True).to_hex()
```

A public key is an optional argument to `blockstack-core fast_sync`.  Full command is `blockstack-core fast_sync <url> <CSV of public keys> [--num_required <number of required signatures>]`

**Comment by jackzampolin** [comment]
Going to go ahead and close this issue. Thank you for clarifying @jcnelson
