### ISSUE TITLE
pip install on HPUX system

### ISSUE THREAD

**Issue by fabe33** [blockstack/blockstack-core#733]
HI everybody,

I'm trying to use pip on an HPUX system (PA-RISC HPUX 11iV3), I installed with succes pip but when i want to use it to install a new module, i obtain this issue.

>pip install sysv_ipc
Collecting sysv_ipc
  Downloading sysv_ipc-0.7.0.tar.gz (93kB)
    100% |################################| 102kB 398kB/s
Installing collected packages: sysv-ipc
  Running setup.py install for sysv-ipc ... error
    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-DCA74B/sysv-ipc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mN1VJF-record/install-record.txt --single-version-externally-managed --compile:
    ******************************************************************************
    * Setup can't determine the value of PAGE_SIZE on your system, so it will
    * default to 4096 which may not be correct.
    *
    * Please report this message and your operating system info to the package
    * maintainer listed in the README file.
    ******************************************************************************
    running install
    running build
    running build_ext
    building 'sysv_ipc' extension
    creating build
    creating build/temp.hp-ux-B.11.31-9000-800-2.7
    gcc -DNDEBUG -O -fpic +z -I/usr/local/include/python2.7 -c sysv_ipc_module.c -o build/temp.hp-ux-B.11.31-9000-800-2.7/sysv_ipc_module.o
    gcc: +z: No such file or directory
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-DCA74B/sysv-ipc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mN1VJF-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-DCA74B/sysv-ipc/

Option "+z "need to be replace by -fpic on this system but impossible to find where i can do that.

Thanks for your help.

Fabien.

**Comment by larrysalibra** [comment]
Hi @fabe33! is this a problem with installing blockstack-core?

**Comment by fabe33** [comment]
Ho sorry, wrong topic ... but I think it's a common issue if you have an idea :)

**Comment by tamil07** [comment]
@fabe33 , I am looking for a best way to install pip on hp ux. I noticed that this thread  is about it so asking for help here.

**Comment by moxiegirl** [comment]
@tamil07 this issue was closed because it is not a Blockstack issue. Please seek help on Stackoverflow or similar where they answer questions specific to `pip` and your OS.
