### ISSUE TITLE
Setup a remote regtest core node with a faucet endpoint

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-core#735]
Run a regtest core node on a Blockstack subdomain that the browser can be configured to connect to. Removes the need to perform the current docker setup and makes it very easy for developers to start testing with Blockstack IDs.

I can work with @jackzampolin to set this up. cc: @kantai @jcnelson 

Reference user story: 
https://github.com/blockstack/blockstack-browser/issues/1190

**Comment by jcnelson** [comment]
We should enhance testnet.blockstack.org to do this.

**Comment by jcnelson** [comment]
testnet.blockstack.org already does all of this, including running a subdomain registrar.  Closing this issue; please re-open if there are any specific problems.
