### ISSUE TITLE
Docs: Add overview of the Blockstack Naming Service (BNS)

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#740]
Describe from a developer's perspective how the Blockstack Naming Service works and what it does for them.  Include diagrams and pointers to core.blockstack.org API endpoints and blockstack.js APIs.

**Comment by jcnelson** [comment]
Initial draft at https://github.com/blockstack/blockstack-core/blob/feature/docs-bns/docs/blockstack_naming_service.md

**Comment by jcnelson** [comment]
Merged

**Comment by larrysalibra** [comment]
@jcnelson i'm trying to figure out if all the docs are complete - it looks like these changes were made outside of the normal create feature branch, pull request to develop, merge, pull request to master process, so I can't figure out where the reviewer, @kantai, signed off on these docs.

It looks like there's a pull request here where the reviewer asked for changes: https://github.com/blockstack/blockstack-core/pull/763

Where are we in the review process on this?

**Comment by kantai** [comment]
@jcnelson pushed changes to address my comments, I just went back through those changes and approved the changes.

**Comment by jcnelson** [comment]
@larrysalibra sorry about that!  I didn't realize I was supposed to merge to `develop` first.  Will do that from now on.

**Comment by larrysalibra** [comment]
Thanks @kantai @jcnelson for clarifying

**Comment by larrysalibra** [comment]
Moving this to accepted
