### ISSUE TITLE
Docs: Add overview of the Atlas Peer Network

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#741]
Create a document that describes Atlas from a developer's perspective.  Describe what it can be used for and how to go about doing so.

**Comment by jcnelson** [comment]
Merged!

**Comment by larrysalibra** [comment]
Same comment as this: https://github.com/blockstack/blockstack-core/issues/740#issuecomment-371127806 - Can't see where the review process and sign off from @kantai happened for the atlas docs. Apologies if i missed it somewhere!

**Comment by kantai** [comment]
I reviewed it on slack @larrysalibra --- which means that it is lost to time.

**Comment by jcnelson** [comment]
@larrysalibra same as #740.  Will merge to `develop` first from now on.
