### ISSUE TITLE
API: Deprecate all REST routes that we're not using

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#744]
Go through `blockstack_client/rpc.py` and deprecate any methods that we don't use.  Make sure we have documentation for the methods that we do use, however.

Endpoints that we use today (update as we discover more):
* GET /v1/node/ping
* GET /v1/names?page={page}
* GET /v1/names/{name}
* GET /v1/names/{name}/history
* GET /v1/names/{name}/zonefile
* GET /v1/names/{name}/zonefile/{zoneFileHash}
* GET /v1/addresses/{blockchain}/{address}
* GET /v1/prices/namespaces/{tld}
* GET /v1/prices/names/{name}
* GET /v1/blockchains/{blockchainName}/consensus
* GET /v1/blockchains/{blockchainName}/name_count
* GET /v1/blockchains/{blockchainName}/pending
* GET /v1/blockchains/bitcoin/operations/{blockheight}
* GET /v1/namespaces
* GET /v1/namespaces/{tld}/names?page={page}
* GET /v1/users/{username}
* GET /v1/auth?authRequest={authRequestToken}

cc @larrysalibra @kantai @jackzampolin if you know of any more that will need to be preserved.

**Comment by jackzampolin** [comment]
I'm not seeing any that I use that aren't on there. I think we need to make sure to ping @yknl on this issue too.

**Comment by yknl** [comment]
Good catch @jackzampolin 

@jcnelson The Blockstack Explorer is still using the endpoints below which I don't see in the list:
GET /v1/names/{name}/zonefile
GET /v1/blockchains/bitcoin/operations/{blockheight}

**Comment by jcnelson** [comment]
Thanks!  Updated

**Comment by jcnelson** [comment]
Actually, are we using these endpoints at all?

* GET /v1/blockchains/{blockchainName}/pending
* GET /v1/node/*
* POST /v1/node/*
* PUT /v1/node/*
* DELETE /v1/node/*
* GET /insight-api/*
* POST /insight-api/*

**Comment by jackzampolin** [comment]
I've seen the `GET & POST /insight-api/*` routes (`/tx/send` and `/addr/{{ address }}/utxo`). I have not seen any of the `/v1/node/*` routes or the `/v1/blockchain/` routes either.

**Comment by kantai** [comment]
> GET /v1/blockchains/{blockchainName}/pending
Not used -- I don't think the browser ever used this for checking tx status, though that would be a nice feature for users -- now that the browser generates the transactions itself, it should just monitor them using their txids.

> GET /v1/node/*

The "ping" endpoint is still being used by a couple different clients -- a lot of those monitoring jobs. The browser also uses it to test if the local node is alive for debugging reasons. That last use case can go away when we remove the api endpoint from the browser build.

> POST /v1/node/*

These were only ever used for setting the core storage configuration options. The code still exists in the browser, but again, these will not get called in the future.

> PUT /v1/node/*
> DELETE /v1/node/*

Weren't ever used to my knowledge.

> GET /insight-api/*
> POST /insight-api/*

I believe these are _only_ used in the regtest environment. However, the transaction generation and broadcasting code in `blockstack.js` does _not_ use them in regtest mode, instead speaking to the bitcoind instance directly. Those `insight-api` endpoints are still used to fetch wallet balance though.

**Comment by jcnelson** [comment]
Thanks @jackzampolin @kantai!  I'll preserve the `/insight-api/` endpoints for testing, and the `ping` endpoint.  I think @kantai is right about `POST /v1/node/*`---we used to use this to configure the Dropbox driver.

We're not relying on Core to track pending name registrations anymore though, right?  More generally, when I call `GET /v1/names/{:name}`, we don't do anything with the built-in registrar's information anymore, right?  Trying to figure out if we can deprecate the built-in registrar.

**Comment by kantai** [comment]
> We're not relying on Core to track pending name registrations anymore though, right? More generally, when I call GET /v1/names/{:name}, we don't do anything with the built-in registrar's information anymore, right? Trying to figure out if we can deprecate the built-in registrar.

That's right -- the only thing depending on the `blockstack_client` registrar is some legacy infrastructure, which shouldn't need to be patched going forward.

**Comment by jcnelson** [comment]
This is implemented upstream in `feature/token-v1` and `feature/blockstack_client_refactor`
