### ISSUE TITLE
Docs:  Add documentation for starting `blockstack-core` in a Docker container

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#747]
The instructions for Docker currently show how to get `blockstack api` and the browser running, but not the `blockstack-core` node.  We'll need documentation on starting `blockstack-core` and `blockstack api` processes in Docker.

cc @jackzampolin

**Comment by jackzampolin** [comment]
I've got a number of scripts to get this going. I'll get one in the repo.

**Comment by jcnelson** [comment]
Merged!
