### ISSUE TITLE
"error": "Authentication to API service failed. Are you using the correct API password or do you need to pass the correct one with --api_password ?"

### ISSUE THREAD

**Issue by nsipplswezey** [blockstack/blockstack-core#751]
Issue in setting up node. I'm following instructions as written in readme: https://github.com/blockstack/blockstack-core#setting-up-blockstack-api

```
pip2 install blockstack --upgrade
blockstack setup
blockstack api start
blockstack info
```

I get the following authentication error on `blockstack info`
Inputting my password created in `blockstack setup` step to `blockstack info --api_password <password from blockstack setup>` gives the same error.

```
Wallet is encrypted using your password and stored  at "/Users/nsipplswezey/.blockstack/wallet.json", please make sure you create a backup.
{
    "status": true
}
Macintosh-7:~ nsipplswezey$ blockstack api start
Enter wallet password: 
{
    "status": true
}
Macintosh-7:~ nsipplswezey$ blockstack info
{
    "error": "Authentication to API service failed. Are you using the correct API password or do you need to pass the correct one with --api_password ?"
}
Macintosh-7:~ nsipplswezey$ 
```

I imagine this is a common first-pass set-up oversight/confusion about passwords on my part, so might be an easily closed issue. Thanks!

**Comment by nsipplswezey** [comment]
Found https://github.com/blockstack/blockstack-core/issues/416 for reference.

**Comment by jcnelson** [comment]
Hey @nsipplswezey, sorry to hear you're having trouble!

The API password is stored as a config option `~/.blockstack/client.ini` (it's analogous to the `rpc_password` field in `bitcoind`, if you are familiar with that).  It is different from your wallet password, which is not stored anywhere.

Can you confirm that the `api_password` is being sent via the HTTP headers?  You can do so by passing `--debug` to `blockstack api start` and inspecting the log file in `~/.blockstack/api_endpoint.log`.

Hope this helps!

**Comment by nsipplswezey** [comment]
Thanks @jcnelson for the note clarifying the distinction between wallet and API passwords. That was ambiguous in my first read, and a clear point of confusion on my part, and I get the distinction now.  Also wow thanks for https://github.com/blockstack/blockstack-core/commit/e54d08fcc8340e04403bbaedfe6680b64bb744e7 It seems like I'm on to another error which requires some debugging on my side. Will come back with future issues. Thanks!
