### ISSUE TITLE
no se instala

### ISSUE THREAD

**Issue by oleometal** [blockstack/blockstack-core#764]
ninguno de los metodos que tienen ahi sirve para instalarlo

**Comment by oleometal** [comment]
desde la fuente me sale esto
python2 ./setup.py build

Traceback (most recent call last):
  File "./setup.py", line 24, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

**Comment by jcnelson** [comment]
Hola @oleometal,

(Perdoname, el espanol no es mi lingua primera).

Necessita usted instalar el paquete de Python `setuptools`.  Puede utilizar el commando de bash aqui:

```bash
$ pip install setuputils
```

Espero que esta informacion es util para usted!

**Comment by oleometal** [comment]
gracias ya lo hice y pude correr el dapp hello-blockstack pero cuando quiero registrarme, cuando le doy al boton me lleva a localhost:8888/.... pero ahi no hay nada. puedes mostrarme como correr el blocstack api porfavor. :-)

**Comment by jcnelson** [comment]
Use usted el Linux?  Ya ha instalado y ha corrido el Blockstack Browser? (https://github.com/blockstack/blockstack-browser)  Si es asi, y si usted no use el Docker para correrlo, es possible que necessite cambiar el numero de puerto a 3000 en lago de 8888, y recargar la pagina.  Por favor me cuenta si lo functiona?

**Comment by jcnelson** [comment]
Yo vi su nota en el foro aqui: https://forum.blockstack.org/t/chrome-does-not-launch-to-localhost-8888/4064/10

Los nota usted los tres '/' en el argumento `auth=`?  Lo funciona cuando los elimina?

**Comment by oleometal** [comment]
https://forum.blockstack.org/t/chrome-does-not-launch-to-localhost-8888/4064/11?u=oleometal

2018-03-06 14:23 GMT-06:00 Jude Nelson <notifications@github.com>:

**Comment by oleometal** [comment]
Gracias


2018-03-06 15:14 GMT-06:00 Oleo nuñez <oleometal@gmail.com>:

**Comment by jcnelson** [comment]
Me alegro que funciono para usted!  Yo los arreglare estes problemas y el README.

**Comment by oleometal** [comment]
muchas gracias estoy aprendiendo mucho sobre las aplicaciones web y me
gusta este proyecto, lo sigo muy de cerca.

2018-03-06 15:28 GMT-06:00 Jude Nelson <notifications@github.com>:
