### ISSUE TITLE
Testing: use local transaction broadcaster and gaia hub in test framework

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#770]
The integration test suite does not have any systemic tests that cover the transaction broadcaster service (https://github.com/blockstack/transaction-broadcaster) or Gaia hubs (https://github.com/blockstack/gaia).  These instead have their own tests.  However, Core's integration test suite should make them available and include tests to ensure that `blockstack.js` can communicate with them.

This is blocked on #717.  Once #717 closes, we can use `blockstack.js` to communicate (and test) these components.

**Comment by kantai** [comment]
There's a test environment which spins these up for testing with a local browser:

https://github.com/blockstack/blockstack-core/blob/master/integration_tests/blockstack_integration_tests/scenarios/browser_env.py#L56

This makes assumptions about where to find those node modules, though, which is pretty specific to the docker image. i guess an alternative is to assume they are in the `PATH`, and then make sure that the docker image adds them as such.

**Comment by jcnelson** [comment]
The gaia hub is now started by default in the test framework, and we have helpers in `testlib.py` that can load and store profiles using it.

**Comment by jcnelson** [comment]
This is now working in `feature/token-v1`

**Comment by kantai** [comment]
Is this going to break that test scenario? If so, we'd have to update the various docs for setting up the browser testing environment.

**Comment by jcnelson** [comment]
No; I patched that test scenario in `feature/token-v1`.

**Comment by jcnelson** [comment]
This is also patched into `feature/blockstack_client_refactor`
