### ISSUE TITLE
Core: Deprecate the use of blockstack_client

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#772]
We need to stop using `blockstack_client` in `core.blockstack.org` wherever possible, since the behavior of the token system is going to conflict with a lot of assumptions blockstack_client makes (in particular, getting costs of names and namespaces).  Generally speaking, this functionality has migrated to blockstack.js anyway.

**Comment by jcnelson** [comment]
This includes:

* `blockstack_client.get_profile()` for loading user profiles
* `blockstack_client.subdomains` for getting the set of subdomains in the system
* `blockstack_client.get_all_names()` when refreshing the resolver

**Comment by kantai** [comment]
The functionality hasn't fully migrated to `blockstack.js` yet -- the price lookup in `blockstack.js` uses the `/v1/prices/` endpoint -- if we want to deprecate _that_ endpoint, I think that's a separate discussion from deprecating `blockstack_client`, which I agree we should do, though again, we still need some kind of API shim between clients and the json+XML RPC interface.

**Comment by jcnelson** [comment]
Ah.  To clarify, I wasn't suggesting depreciating the RESTful endpoints.  `/v1/prices/` should stay, for example.  I was just going to make the `/v1/prices/` endpoint implementation stop using `blockstack_client`.  I've already done it in my local branch, for example (it just uses the equivalent method in `blockstack.lib.client`).

**Comment by jcnelson** [comment]
This is working in `feature/token-v1` and `feature/blockstack_client_refactor`
