### ISSUE TITLE
API: Rename "subdomain" to "sponsored name"

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#775]
We've been floating the term "subdomain" to refer to an off-chain name, whose name transactions are broadcast via the Atlas network.  However, this has been shown to be a confusing term, because while a "subdomain" Blockstack ID *looks like* a DNS subdomain, it has fundamentally different semantics.  Specifically, it has the same safety properties of an on-chain Blockstack ID, but slightly different liveness properties (i.e. the on-chain name owner needs to propagate off-chain transactions on their behalf).

@yknl came up with the term "sponsored name" to describe off-chain names, which I like a lot better.  It does not confuse users who are familiar with DNS, and it captures the semantic differences between an on-chain Blockstack ID and an off-chain Blockstack ID.  It also captures the notion that off-chain names are cheaper to create and do not need to cost the user any BTC.

I'm proposing that we rename all instances of "subdomain" in the documentation and codebase to "sponsored name."  If we do this, it would be better to do this sooner rather than later, since we haven't yet shipped the ability for users to acquire off-chain names (and we want to get that messaging right the first time).

Thoughts? @shea256 @muneeb-ali @jeffdomke @larrysalibra @yknl

**Comment by larrysalibra** [comment]
I like this too.

**Comment by kantai** [comment]
I like "sponsored name" a lot, but I'd like to vote against sweeping changes of variable names in the source code (we should update docs, repo names though). We've ended up with lots of errors in the past from refactors that have missed renamed variables.

**Comment by jcnelson** [comment]
Looks like we're sticking with subdomains for the time being.
