### ISSUE TITLE
STACKs: implement pay-with-STACKs rules for names

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#776]
Introduce a new namespace type (version 3) where names are purchased with STACKs tokens, instead of BTC.  The following new rules apply for names created in version-3 namespaces:

Registration:
* The `NAME_PREORDER` transaction sends a dust amount to the default burn address, instead of the name's cost on the namespace price curve.  It is otherwise unchanged from before.
* The `NAME_REGISTRATION` transaction is only accepted if the address that sent the `NAME_PREORDER` has enough STACKs to pay for it.  Otherwise, it is rejected.
* ~~When a `NAME_REGISTRATION` transaction is committed, the `NAME_PREORDER`'s address is debited the amount of STACKs the name cost.~~
* The `NAME_PREORDER` wire format will be changed to include the number of STACKs to burn in the `OP_RETURN`.
* When a `NAME_PREORDER` transaction is committed, the `NAME_PREORDER`'s address is debited the amount of STACKs it indicated to burn.

Renewals:
* A `NAME_RENEWAL` transaction sends a dust amount to the default burn address, instead of the name's cost on the namespace price curve.  It is otherwise unchanged from before.
* A `NAME_RENEWAL` transaction is only accepted if the *owner* address has enough STACKs in its account to pay for the name's price.
* When a `NAME_RENEWAL` transaction is committed, the *current owner*'s address is debited the amount of STACKs the name cost.

**Comment by kantai** [comment]
> When a NAME_REGISTRATION transaction is committed, the NAME_PREORDER's address is debited the amount of STACKs the name cost.

Should the debit occur when the preorder is committed? Otherwise, an adversary could preorder a bunch of names, and only issue a register when they see another user's register hit the mempool without penalty (in STACKs). Granted, the limited validity window for preorders limits the scope of this, but I wonder if this is something we want to deal with.

**Comment by jcnelson** [comment]
> Should the debit occur when the preorder is committed? Otherwise, an adversary could preorder a bunch of names, and only issue a register when they see another user's register hit the mempool without penalty (in STACKs). Granted, the limited validity window for preorders limits the scope of this, but I wonder if this is something we want to deal with.

Trouble is, it's impossible to know anything about the name while it is preordered (including determining which namespace it was in), except perhaps the price.  I agree that ideally, a preorder would burn all the STACKs up front.  This could be done if we change the wire format of the preorder to include the number of STACKs to burn, for example.  However, I'm also trying to avoid that so we don't end up having to patch blockstack.js significantly (i.e. the wire formats of all these transactions are still the same in this description).  What do you think?

**Comment by kantai** [comment]
>  This could be done if we change the wire format of the preorder to include the number of STACKs to burn, for example. However, I'm also trying to avoid that so we don't end up having to patch blockstack.js significantly (i.e. the wire formats of all these transactions are still the same in this description). What do you think?

Ahhh, I see. Having an identical wire format is really nice, though I'm not too worried about including changes in the transaction generation library -- changes already are going to need to happen for the safety checks on ability to fund a in-STACKs purchase. 

I think there's two positives to including the burn amount in the preorder:
1. ability to debit on preorder
2. transaction "inspectability" -- the transactions _themselves_ contain all the information I need to know how much an account will be debited

I think the positive of (2) is actually stronger than (1).

**Comment by jcnelson** [comment]
True enough.  I'll go ahead and make the wire format include the number of STACKs to burn, if you're fine with patching the wire format.  Can you open an issue in `blockstack.js` for this too?

**Comment by jcnelson** [comment]
Also keep in mind we'll need to change the wire format for `NAME_RENEWAL` as well, since it will have to indicate how many STACKs to burn.

**Comment by jcnelson** [comment]
Implemented in `feature/token-v1`
