### ISSUE TITLE
How exactly Virtualchain and consensus hash  works?

### ISSUE THREAD

**Issue by haiki** [blockstack/blockstack-core#781]
After days learning, I am totally confused by the mechnism of  virtualchain and  consensus rules . 
so I want to know how virtualchain store blocks which parses transactions from blockchain, What kind of database is used? how to anthenticate transactions which are valid or not by consensus hash  ?  as some transactions have consensus hash but others not . 
and how virtual chain block's format looks like ? Are the blocks of virtualchain and blockchain corresponding to one by one? if so,once  blcokchain's block wihtout operation ,here will be many stale virtualchain block?
May be here are enough doc for my questions but I am not understand them . so I'm looking forward to yours reply ! thanks~

**Comment by kantai** [comment]
The best resource for learning about that is the paper "Blockstack: A New Decentralized Internet"

https://blockstack.org/papers

**Comment by haiki** [comment]
well，I had read all the papers it mentions in addtion to  the token whitepaper, May I trouble you to answer my question above? I‘d like to know whether my understanding is right or not and some points I mentioned above were not explained in papers. thank you! @kantai

**Comment by jackzampolin** [comment]
@haiki This is not the right place for this type of question. Our forum might be a better spot for it: forum.blockstack.org

**Comment by arni077** [comment]
From my understanding,Virtualchain has it's own nodes. the blocks of the virtualchain and the underlying blockchain NOT corresponding to one by one,because the virtualchain does changes to it's blocks corresponding to user changes(when he updates things for example)..then the virtualchain sends those changes as. transactions to underlying blockchain.
