### ISSUE TITLE
Difficulty installing with pip on macOS

### ISSUE THREAD

**Issue by chat491231702** [blockstack/blockstack-core#783]
Installed /Library/Python/2.7/site-packages/blockstack-0.18.0.4-py2.7.egg
Processing dependencies for blockstack==0.18.0.4
Searching for cryptography>=1.9
Reading https://pypi.python.org/simple/cryptography/
Best match: cryptography 2.2
Downloading https://pypi.python.org/packages/b1/b8/f42fd854ed5b6f29a1b9c3778993753ff6ef138e4d892fdd61355d40508d/cryptography-2.2.tar.gz#md5=c49c1ee145a900313a216fa2c788208c
Processing cryptography-2.2.tar.gz
Writing /tmp/easy_install-gJoDXX/cryptography-2.2/setup.cfg
Running cryptography-2.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gJoDXX/cryptography-2.2/egg-dist-tmp-ihJSNo
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*' found under directory 'vectors'
build/temp.macosx-10.13-intel-2.7/_openssl.c:493:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
error: Setup script exited with error: command 'cc' failed with exit status 1

**Comment by chat491231702** [comment]
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CFLAGS="-I/usr/local/opt/openssl/include/openssl"
export CPPFLAGS="-I/usr/local/opt/openssl/include/openssl"
export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"

after env set, still not work!

**Comment by kantai** [comment]
Hi @chat491231702 -- it's kind of tricky to install using `pip` on macOS -- because of dependencies on `cryptography` and `pyscrypt` -- if you look at the circle.yml file we use, you can see some of the tricks that we play to get compilation working on macOS:

https://github.com/blockstack/blockstack-core/blob/master/circle.yml

**Comment by jcnelson** [comment]
The `pyscript` dependency is going away soon, hopefully!

**Comment by frank0718** [comment]
1) find openssl header file dir  , /usr/local/Cellar/openssl/1.0.2l/include 
2) cp /usr/local/Cellar/openssl/1.0.2l/include  /Library/Developer/CommandLineTools/usr/include/ 

worked at mac 10.13.2 Sierra
