### ISSUE TITLE
API: add endpoint for querying sponsored names

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#789]
Add `/v1/names/sponsored` to return the list of sponsored names.

Add `/v1/blockchain/{:blockchainName}/sponsored_name_count` to return the number of sponsored names.

**Comment by kantai** [comment]
Can we continue to call them subdomains for a little bit? I'm not saying that we should plan on calling them that forever (I'm fairly certain that we will abandon that name, in fact), but we do already have a bunch of code, repos, etc. that use the word subdomains, so it'd be better to have 1 deprecated name, then a mix of 1 deprecated name and 1 name that (I think) we still haven't decided is the one we'll use forever.

**Comment by jackzampolin** [comment]
Any reason why we don't just include subdomains in the returns for the following routes:

```
/v1/names
/v1/namespaces/{tld}/names?page={page}
```

This way developers wouldn't need to query 2 different endpoints to fetch all the names in the system.

**Comment by jcnelson** [comment]
A few reasons:

* Backwards compatibility.  The `/v1/names` endpoint is meant for on-chain names.
* Semantic incompatibility.  We will want to support queries on subdomains that do not make sense for on-chain names (such as "get all subdomains registered by this on-chain name").  Shoehorning this into the `/v1/names` endpoint will lead to awkward usage rules and semantics..
* Implementation complexity.  It is much simpler to have two endpoints than to try to interleave names from two separate subsystems together.

**Comment by jcnelson** [comment]
Shipped in 0.18.5
