### ISSUE TITLE
500 Errors from Blockstack Core

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#792]
Blockstack core currently responds with `5xx` errors in many cases.

This leads to problems like this report for explorer:
https://forum.blockstack.org/t/explorer-addusername-does-not-work-for-expired-usernames/4851

This also leads to bad behavior from caching services -- which render "Server Down" messages for 5xx errors. You can see this by loading and refreshing, e.g., the following page:

https://core.blockstack.org/v1/names/blankstein

**Comment by jcnelson** [comment]
Are these errors forwarded from the RESTful API, or are they from the Core API service?  I can remove all 5xx errors from the RESTful API in the 0.19 build.

**Comment by kantai** [comment]
They're returned from the 6270 endpoint.

**Comment by jcnelson** [comment]
What would you like the preferred behavior to be in that case with the Core API?

**Comment by kantai** [comment]
Maybe a blanket 400? Then we should track what requests are giving us frequent 400s, and try to figure out if we can provide better error responses and codes in those case.

**Comment by jcnelson** [comment]
Yeah, better use of 400's would be good.  Will try to be more specific than 400, though.

I've done some work on this in `feature/refactor_blockstack_client` and am mirroring it to `blockstack/token-v1`

**Comment by jcnelson** [comment]
This should be fixed upstream, in both `feature/token-v1` and `feature/blockstack_client_refactor`.
