### ISSUE TITLE
blockstack-core search endpoint does not return .personal.id IDs

### ISSUE THREAD

**Issue by prabhaav** [blockstack/blockstack-core#794]
Search needs to index .personal.id and other id's registered by subdomains. Example: `https://core.blockstack.org/v1/search?query=braphaav.personal.id`

**Comment by jcnelson** [comment]
Agreed.  Will see if either I or @kantai can do something about this before the 0.19 release.

**Comment by prabhaav** [comment]
FYI, since we are registering users on .stealthy.id, if search could index those too that'd be awesome!

**Comment by jcnelson** [comment]
Definitely.  All Blockstack IDs need to be indexed.

**Comment by kantai** [comment]
Yep -- I'll look into it while you're working on 0.19 -- ideally this is something more like a 'true client' of blockstack-core, rather than the current search endpoint which is more of a hybrid.

**Comment by kantai** [comment]
This should now work @prabhaav :
https://core.blockstack.org/v1/search?query=braphaav.personal

**Comment by prabhaav** [comment]
Indeed it does! Thanks @kantai

**Comment by jcnelson** [comment]
Cool!  Can we close this now?

**Comment by prabhaav** [comment]
Closing issue.
