### ISSUE TITLE
Support for Ethereum?

### ISSUE THREAD

**Issue by bmiller59** [blockstack/blockstack-core#795]
I was reading this https://github.com/blockstack/virtualchain/issues/7 and followed up by reviewing issues for blockstack and blockstack-core, as well as by checking the forum but could not find a current status update on Ethereum support. The Slack channel is locked and I could not join there.

Can you clarify intentions for Ethereum support and anticipated timeline? I am also considering participating in the necessary development if I could find a roadmap and how to plug in. Thanks.

**Comment by jcnelson** [comment]
Our design philosophy is to build on top of the most secure blockchain, but remain portable so the system can migrate to a more secure blockchain later on.  Currently, this is Bitcoin.  There is no roadmap or timeline for an Ethereum port on our end.  However, feel free to send a PR to virtualchain if you would like to port Blockstack to Ethereum :)
