### ISSUE TITLE
Review the API specification (replies and JSON schema)

### ISSUE THREAD

**Issue by vsund** [blockstack/blockstack-core#798]
I'm currently working on a small TypeScript client which represents the Core endpoints in a TypeScript environment. While doing this I noticed that
1. some JSON schema specifications don't match the provided examples (e.g. missing attributes)
2. some attributes are explicitly nullable (`anyOf: [ { "type": "string" }, { "type": "null" } ]`) while others are allowed to be absent (which would be the way to go I think)
3. some endpoints have no associated schema
4. most schemas have a weird format (are using single quotes and trailing commas), which isn't valid per JSON specification
5. some endpoints reply with error objects and some don't have errors, I'd like to propose to use HTTP errors there instead of error objects

in the [API specification](https://github.com/blockstack/blockstack-core/blob/develop/docs/api-specs.md).

For creating the mentioned Core client I had to create own (spec-conform) JSON schema specifications, happy to contribute them and and adding additional ones.

I first tried to generate a client from the API spec, but in the current form it's unfortunately impossible. I'd like to suggest (and help ;)) to review them until the next breaking release when the deprecated ones get dropped.

---
(I enumerated these for separate discussion, if I should open multiple issues please leave me a message.)

**Comment by vsund** [comment]
Also noticed that some endpoints (e.g. `/v1/namespaces/{tld}/names?page={page}`, probably more) respond with not expected replies (and also a bit strangely):

```bash
$ curl https://core.blockstack.org/v1/namespaces/not-existing/names?page=0
[]
$ curl https://core.blockstack.org/v1/namespaces/.not-existing/names?page=0
{
  "error": "Not found"
}
```

The API specification says nothing about errors on this endpoint :/

**Comment by vsund** [comment]
Just for reference, my written JSON schemas are now online [here](https://github.com/ntzwrk/blockstack-core-client.ts/tree/develop/src/responses).

**Comment by jcnelson** [comment]
Hey @vsund, thanks for pointing these out!  I'll take a look at cleaning some of these up later today.

**Comment by moxiegirl** [comment]
Per @kantai  very call _not_ marked deprecated in the `api-specs.md` should be in the core listing
Missing from core listing:

- `GET /v1/names/{name}/zonefile` missing from core listing
- GET /v1/blockchains/{blockchainName}/operations/{blockHeight}`

DEPRECATED in spec, but appears in core listing, so revove
`GET /v1/blockchains/{blockchainName}/pending`

**Comment by jcnelson** [comment]
I've updated the Core documentation for the `develop` branch.  I'm satisfied with its current state.  Closing this issue here; please reopen if there's anything missing.
