### ISSUE TITLE
STACKS: What happens if we're missing an address in the genesis block?

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#812]
@kantai, @jeffdomke, and @jessesoslow raised a critical concern for deploying the Stacks token:  what happens if, somehow, we don't get somebody's account address by the time the genesis block goes live?  This could happen if the token buyer loses their email address, or the token buyer dies before the genesis block launches and their estate executor doesn't know to send us an address.

The solution we arrived at was to create an `ACCOUNT_TRANSFER` opcode.  The `ACCOUNT_TRANSFER` opcode would do the following:
* Transfer all tokens from the sender address to the receiver address
* Transfer all token vesting schedules from the sender address to the receiver address (so the recipient would vest the tokens instead)
* Transfer the transfer lock-up period from the sender address to the receiver address (so the recipient cannot spend tokens until the lock-up period passes).
* Remove the sender address from the accounts table.

The `ACCOUNT_TRANSFER` operation could only be used **once** over the lifetime of an account.  Once an account is transferred, it cannot be transferred again.

When the genesis block launches, all accounts that have addresses would be non-transferrable by default.  Only accounts for which we **do not yet have an address for** would be transferrable.  We would hold onto a private key for each such account, and issue a `ACCOUNT_TRANSFER` transaction to send the account to the rightful owner once they reach out to us and give us an address.

@shea256 @muneeb-ali Thoughts or concerns?

**Comment by kantai** [comment]
Just giving this a "bump" in visibility as I think this is the only remaining "feature" to be implemented in `token-v1`

**Comment by jcnelson** [comment]
Based on conversations had online, I think this is no longer the approach we're going to take.  Closing this issue.
