### ISSUE TITLE
Create Stacks test net testing guide

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#821]
Create a brief guide to help team members know what they should try out.

**Comment by jcnelson** [comment]
1. Follow the instructions on https://testnet.blockstack.org to install the `feature/stacks-transactions` branch of `blockstack.js` and the Blockstack CLI.
2. Generate some owner and payment private keys using the `make_keychain` command.
3. Fund your payment address with some Stacks via the faucet
4. Verify that `blockstack-cli -t balance YOUR_ADDRESS` returns your Stacks balance after it confirms.  You can also verify that the TXID printed on the faucet has sufficient confirmations via `blockstack-cli -t get_confirmations TXID`
5. Verify the price of a name with `blockstack-cli -t price NAME.id2` is priced in Stacks
6. Verify that you can register a name in the `.id2` namespace, which is paid for in Stacks
7. Verify your Stacks balance decreases by the name amount
8. Verify that you can preorder, reveal, and ready a namespace paid for with Stacks.
9. Verify that you can send Stacks to a new address, and then spend from it.

Instructions are now up on the testnet site.

**Comment by jcnelson** [comment]
Tokens will be live later today.
