### ISSUE TITLE
Installation instructions reference the wrong branch of blockstack.js

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#828]
The testnet instructions on https://testnet.blockstack.org tell me to use the `feature/stacks-token`branch of blockstack.js but it should be `feature/stacks-transactions`

<img width="770" alt="screen shot 2018-05-22 at 3 35 51 pm" src="https://user-images.githubusercontent.com/597182/40393802-d47ddc04-5dd5-11e8-8b23-58ea3f5171b7.png">

**Comment by jcnelson** [comment]
Thanks @larrysalibra !  Should be fixed now.
