### ISSUE TITLE
Names with long histories break XMLRPC

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#834]
Names with too many operations won't fit in an XMLRPC payload when the blockstack `client.py` queries for historical name operations. This leads to 500s because there's a client error.

**Comment by jcnelson** [comment]
I can take a crack at this.  Do you know how many operations it takes before it breaks?

**Comment by kantai** [comment]
Nope -- though `id.blockstack` already has enough. I think we'll probably  just need to add pagination to the `get_name_blockchain_record` RPC.

**Comment by kantai** [comment]
This is now resolved in `master` and updated on core.blockstack.org -- this also added the `page=` query string parameter to the history API.
