### ISSUE TITLE
Remove and replace references to the OLD CLI in the documentation

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack-core#856]
* Create and Launch a namespace documentation
See @jcnelson comment that this process is going to be changing soon.  This is due to the upcoming CLI changes.

* TBD

**Comment by moxiegirl** [comment]
@markmhx the CLI documentation includes things like this.

**Comment by markmhx** [comment]
@moxiegirl fantastic, thanks! Mind adding this to this project as well? https://github.com/orgs/blockstack/projects/30

**Comment by jcnelson** [comment]
I think this has been merged now?

**Comment by moxiegirl** [comment]
@jcnelson I did recheck. Found a couple of mentions I missed. Also, saw an issue with duplicate `subdomain.md` and `subdomains.md` file
