### ISSUE TITLE
Tutorial for "Discourse style" of adding Blockstack authentication to an existing applicatiom

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack-core#857]
Tasks to complete:

- A sample code with an outline of the process @hstove 
- A detailed tutorial that walks users through the example @moxiegirl

@larrysalibra Here is the issue.  Hank volunteered to do a sample. @hstove let us know if you think you won't be able to do this.

Assigning to Hank for now.  Hank assign it back to me when you have the sample code ready.

**Comment by hstove** [comment]
Hey @moxiegirl , can you give me some timeline about when I should try and deliver this?

I feel that it should roughly take me half a day, but my week is pretty busy with other priorities right now. I think Friday would be a good day for me to work on it. Is that too slow?

**Comment by moxiegirl** [comment]
@hstove Not at all.  This is as soon as you have time kind of thing.  So, the idea is maybe when you have time in a regular day as opposed to the weekend.   I think the only key is to make sure the app end is something similar to Discourse --- because it has a free version available to every one.

**Comment by moxiegirl** [comment]
This was completed. Output here: https://docs.blockstack.org/develop/auth_provider.html

Thanks @hstove
