### ISSUE TITLE
U2F integration

### ISSUE THREAD

**Issue by hoidsflute** [blockstack/blockstack-core#860]
More a request than an issue, feel free to close if this is in the wrong place or inappropriate.

In the future, I'd love to have the ability to only allow access to my Blockstack ID with U2F/yubikey device.  I don't know if this is possible or what the limitations of this integration would be. 

[https://www.yubico.com/why-yubico/for-developers/](https://www.yubico.com/why-yubico/for-developers/)

Some things that make me slightly uncomfortable about Blockstack that I think could be mitigated with U2F device:
-If someone hijacks my private keys, they have stolen my identity.
-If someone steals my device, they can steal my identity.
-If someone's phone/computer was confiscated by the government, well you know

**Comment by jcnelson** [comment]
This sounds like an awesome app idea!  Want to open this on the [Blockstack Browser](https://github.com/blockstack/blockstack-browser)?  This is the program that stores your private key; ideally, it could be encrypted with your Yubikey or something like that.
