### ISSUE TITLE
blockstore-cli commands in Docker

### ISSUE THREAD

**Issue by ig-grant** [blockstack/blockstack-core#88]
Not sure if I've missed something obvious here. I have blockstored running in a Docker container - it is processing blocks with no issues. In order to run blockstore-cli commands, I attach to the running container via a new terminal window as follows:

```
sudo docker exec -it <container_id> bash
```

I then try to run blockstore-cli commands, eg:

```
root@abf7de6241d9:~/blockstore# blockstore-cli getinfo
```

But I'm getting the following error:

```
None
{
    "error": "Failed to connect to Blockstored"
}
```

Any suggestions?

**Comment by ig-grant** [comment]
I can also confirm the same issue when installing and running on a local Ubuntu server (no Docker):

Open terminal 'A'
Run ```blockstored start```
Enter config options
Blocks being processed...

Open terminal 'B'
Run ```blockstore-cli getinfo```
Returns ``` "error": "Failed to connect to Blockstored"```
Attempts to connect to port 6264 via ```cat < /dev/tcp/127.0.0.1/6264``` return ```connection refused```

**Comment by muneeb-ali** [comment]
Can you share your system details? Is this on OS X?

**Comment by ig-grant** [comment]
Both installation types are on Ubuntu:

Docker installation: base image is Ubuntu 14.04. Host is Ubuntu 14.04 on AWS. 
Non-Docker physical installation: Ubuntu 14.04.

**Comment by muneeb-ali** [comment]
Is the docker image you're using public? Otherwise I can just make a new one using the Dockerfile you shared earlier and reproduce the issue on Ubuntu AWS

**Comment by ig-grant** [comment]
I'm using the following Dockerfile:

```
FROM ubuntu:14.04

RUN apt-get -y update && apt-get -y install python-setuptools python-dev git-core build-essential
RUN easy_install -U pip

RUN mkdir -p /root/blockstore
RUN git clone https://github.com/namesystem/blockstore.git /root/blockstore

WORKDIR /root/blockstore
RUN pip install --upgrade -r requirements.txt
RUN pip install blockstore

EXPOSE 6264

CMD blockstored start
```

Build image:
```
sudo docker build -t openname/blockstore:v1 .
```

Run container:
```
sudo docker run -it openname/blockstore:v1
```

**Comment by ig-grant** [comment]
I've just realised that I'm attempting to ping blockstore-cli before block processing has caught up. Having skimmed over blockstored.py I see I need to wait for this to complete. Can you confirm this?

**Comment by jcnelson** [comment]
Hi @ig-grant,

I know it's been a few months, but Blockstore has been pretty heavily overhauled since you opened this issue, and the command-line client (and client library) have since been factored out as a [separate package](https://github.com/blockstack/blockstore-cli).  Would love to know if you've tried out the latest and greatest version in Docker!

Thanks,
Jude

**Comment by muneeb-ali** [comment]
Update: the docker version is out of data and we've updated our installation docs to reflect that. I'm adding this to the v0.1.0 milestone as it'd make sense to release the new docker image with the new release.
