### ISSUE TITLE
.virtualchain-spv-headers.dat

### ISSUE THREAD

**Issue by doodlemania2** [blockstack/blockstack-core#881]
File is not storing in .blockstack-server directory and I think it should to keep all related data together.

**Comment by jcnelson** [comment]
`.virtualchain-spv-headers.dat` is not created or maintained by Blockstack Core, but by [virtualchain](https://github.com/blockstack/virtualchain).  This is intentionally kept outside of `~/.blockstack-server` because other virtualchain state engine implementations use it.

**Comment by doodlemania2** [comment]
Oh, well alrighty then - thanks sir!
