### ISSUE TITLE
Search Endpoint (v1/search) Takes a Long Time to Load

### ISSUE THREAD

**Issue by jehunter5811** [blockstack/blockstack-core#884]
When querying on anything other than a full ID, the search endpoint takes up to 10 seconds to load for each query. Example: 

https://core.blockstack.org/v1/search?query=bran

**Comment by kantai** [comment]
This was resolved in PR #885, and deployed in production -- the search endpoint should be running much faster now.

**Comment by jehunter5811** [comment]
SOOOOOO much faster. Thanks, Aaron!
