### ISSUE TITLE
Trouble with Dockerfile

### ISSUE THREAD

**Issue by doodlemania2** [blockstack/blockstack-core#893]
I'm unable to get the docker container to run. It gives me a really strange error: standard_init_linux.go:190 exec user process caused “exec format error”.

This indicates initially that the base image is not the right arch. So I fixed that (running from a Raspberry Pi, so grabbed armhf base). Next, the error continues to surface and other searches indicate to watch for #! on line one of the start script - which is present.

So, I tried something random - I executed the image in interactive mode and started /src/api/deployment/boot-docker.sh expecting it to fail but give me a bit more - odd thing happened - it works and I'm running the node in interactive mode.

So, good news, I'm up and running. Bad news - I can't get the CMD to execute non-interactively. Anyone have any ideas?

**Comment by doodlemania2** [comment]
Hi Jude, this was a self built container. The only change I made was line 1 of Dockerfile to read:
FROM multiarch/ubuntu-core:armhf-bionic
(So I could run it on my RaspPi)

Running great in interactive mode, just can't seem to figure out why it won't start regularly.

**Comment by jcnelson** [comment]
Hmm...I have an idea, but not a way to test it.

The Blockstack Core docker image uses [tini](https://github.com/krallin/tini) as the entry point.  The docker file will fetch and verify the `tini` binary when it builds, but it looks like this binary is an `amd64` binary.  That might explain why the image gives you an `exec format error` while running the `boot_docker.sh` script works.

**Comment by doodlemania2** [comment]
Ooooo! I bet that is it - hadn't thought to look at the script for what it's pulling - will try ASAP to see if that's the culprit.

**Comment by doodlemania2** [comment]
That did it @jcnelson ! Changed these lines:
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-armhf /tini
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-armhf.asc /tini.asc
