### ISSUE TITLE
Protocol: Expose VRF Primitive in Smart Contracting Language

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#895]
@hstove suggested this:

Smart contracts often want randomness and often do some kind of hash-then-sort using the latest chain head hash to do it deterministically and non-predictably. It would be nice to have some VRF primitives in our smart contract language. Rather than add this into the SIP-002 (which won't have an exhaustive list of primitives), we should be sure to include this once we have a 1.0 language spec.

**Comment by jcnelson** [comment]
This is implemented.
