### ISSUE TITLE
As a Blockstack team member, I should be able to read detailed document on the blockchain plan.

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack-core#906]
@larrysalibra commented on [Mon Feb 19 2018](https://github.com/blockstack/blockstack/issues/425)

**Comment by kantai** [comment]
Between the whitepaper (https://blockstack.org/whitepaper.pdf) and the SIPs (https://github.com/blockstack/blockstack-core/tree/develop/sip), this issue has been addressed.
