### ISSUE TITLE
Rigorously bound the Clarity Value sizes in VM

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#911]
We should enforce a maximum byte limit for types.

**Comment by jcnelson** [comment]
Does this refer to the size of atoms, or lists, or both?

**Comment by kantai** [comment]
Both -- so we'd have a maximum size for a value in the system -- neither lists nor atoms (e.g., very large tuples) could exceed the size.

**Comment by kantai** [comment]
One important thing to note is that this has to be a maximum size enforced at the language level -- we don't want it to be the case that changes in the interpreter's representation of values could change this.
