### ISSUE TITLE
Hex literals in the smart contracting language

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#916]
We're going to be adding some support for hex literals in the language, but there's still some details to decide.

We can support hex literals as _buffers_, such that something like:

```
0x0000
```

Would represent a 2-byte zero buffer.

But, it may also be useful for hex literals to represent _integer_ types in our language. So we could support both via syntax that looks like this:

```
0x0000i
0x0000b
```

Where the `i` indicates to lex it as an integer, and the `b` indicates to lex it as a buffer.

**Comment by jcnelson** [comment]
I'm a little unclear about this -- what's a buffer, and how is it different from a list of integers that are each between 0 and 255?

**Comment by kantai** [comment]
It's pretty much exactly a list of integers that are between 0 and 255 (it's a Vec<u8> at the interpreter level) -- but it would be less cumbersome than either (1) using a list of 128-bit width integers, each representing 16 bytes, or (2) using a list of 128-bit width integers, where each is constrained to be between 0 and 255.

**Comment by kantai** [comment]
Closing this for now -- we currently are lexing as buffers -- if we want to add support for integer lexing of hex literals, we can revisit.
