### ISSUE TITLE
Issues running on Windows

### ISSUE THREAD

**Issue by csuwildcat** [blockstack/blockstack-core#93]
Steps to reproduce:
- Installed Python
- Installed blockstored with pip
- Attempt to exec `blockstored start`

Error output:

```
[DEBUG] [blockstored:76] Connect to bitcoind at https://openname@btcd.onename.co
m:8332
Traceback (most recent call last):
  File "blockstore/blockstored.py", line 701, in <module>
    run_blockstored()
  File "blockstore/blockstored.py", line 688, in run_blockstored
    stop_server()
  File "blockstore/blockstored.py", line 552, in stop_server
    from .lib.config import BLOCKSTORED_PID_FILE
ValueError: Attempted relative import in non-package
```

**Comment by muneeb-ali** [comment]
Thanks for reporting. We've been testing blockstore on OS X and Linux only. We'll look into setting up Windows testing as well.

**Comment by muneeb-ali** [comment]
One quick work-around can be to use the blockstore docker on Windows.

**Comment by jcnelson** [comment]
We have a docker image here:  https://registry.hub.docker.com/u/blockstack/blockstored/  Would you like to give that a try?

**Comment by csuwildcat** [comment]
Yep, I'll give it a swing on Sunday.

**Comment by csuwildcat** [comment]
@jcnelson @muneeb-ali tried installing via docker, when I run `docker pull blockstack/blockstore` I get the following error:

```
Pulling repository blockstack/blockstored
Tag latest not found in repository blockstack/blockstored
```

**Comment by csuwildcat** [comment]
@jcnelson @muneeb-ali used the `-a` flag, and I got the 0.1 release. I think some default or setting directs it to look for a "latest" version, maybe this should be disabled or added to 0.1?

**Comment by jcnelson** [comment]
Whoops, sorry about that (I had pushed blockstack/blockstored:v0.1).  I just pushed blockstack/blockstored:latest.

**Comment by csuwildcat** [comment]
I am running the Docker image in Windows, but the program freezes operation on `Processing block 361091` when I run `blockstored start` - any ideas?

**Comment by csuwildcat** [comment]
On exit, it raises this error `File "/usr/lib/python2.7/httplib.py", line 871, in putrequest - raise CannotSendRequest()`

**Comment by muneeb-ali** [comment]
@csuwildcat I'm working on the latest docker image and will update you shortly.

**Comment by muneeb-ali** [comment]
Can't seem to reproduce your bug:

```Initializing blockstored server in foreground ...
Creating initial index ...
Processing block 361091
block_nameops []
Processing block 361092```

This is docker on windows?

**Comment by csuwildcat** [comment]
@muneeb-ali yes, I am running it in Docker on Windows. It never prints anything to the console beyond `Processing block 361091`. (Unless it takes more than 10 minutes - I closed it after about that long).

**Comment by muneeb-ali** [comment]
No it shouldn't take that long at all. Can you share more info i.e., version of windows etc? The thing with block 361091 is that it's the last saved block in the docker image, so it's unclear if your docker can even reach outside Internet. I just tested on both OS X and Debian and the current docker version is working perfectly fine.

**Comment by csuwildcat** [comment]
@muneeb-ali still unable to start the docker image on Windows 10 RTM build. This is my exact problem: https://forums.docker.com/t/boot2docker-hangs-then-crashes/401

Seems Docker simply will not run on Windows 10 at the moment, and we have a hackathon next week during which we were looking to start development. I just need a way to get this going inside Windows, it would be amazing if that could happen in time for the hackathon on Monday July 27th.

**Comment by muneeb-ali** [comment]
@csuwildcat Already on it! We also confirmed that it's a Docker problem and not a blockstore problem. Docker is having issues on Windows. We're going to test things out on windows without a docker and ship this. Will keep you posted!

**Comment by csuwildcat** [comment]
Thank you Muneeb!
