### ISSUE TITLE
Improved error messages for the type checker

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#944]
There's a number of ways that the type checker errors can be improved (so this may be more appropriately an epic).

1. Line numbers, rather than subexpressions.
2. More descriptive error messages, especially when it comes to arg-counts. Things like `(define ...)` `(let ...)` and `(tuple ...)` expressions are a little more complex to reason about the argument number.

**Comment by kantai** [comment]
@lgalabru is investigating implementing by transporting a "diagnostic" object:

e.g., 

https://github.com/rust-lang/rust/blob/d3e2cec29225a46298ec4ebf082f34ebd7cfeecf/src/librustc_errors/diagnostic.rs#L13

This is starting to roughly standardize across IDEs, and can lead to useful error checks.

For an exciting preview:

![Screen Shot 2019-06-27 at 9.58.46 AM.png](https://images.zenhubusercontent.com/5bd1c90476942148495f0f12/e0ccfd91-a7dd-43b6-a161-ce3077f39fb8)

**Comment by lgalabru** [comment]
Handled with #1041
