### ISSUE TITLE
Decide on data serialization formats for smart contract data

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#946]
Currently, we serialize data for smart contracts using serde and JSON -- I think we can probably:

1. have a much more efficient serialization scheme
2. eliminate usage of serde in the smart contract VM entirely

Those seem like high enough benefit that we should probably come up with a better serialization format.

**Comment by kantai** [comment]
A key requirement for the serialization format is that it be a bijective mapping (i.e. 1-to-1) from Clarity values to serializations.

**Comment by kantai** [comment]
The first draft of serialization for Clarity values will be the netstring format presented in SIP-005:

...

Each type is encoded by a 1-byte alphabetical ASCII character as a prefix to the
netstring length.  The following characters are used for Clarity types:

* `i` for integer, which will be encoded as an ASCII string of numbers, prefaced with `-` for negative values.
* `s` for buffer, which will be encoded as a lower-case hexadecimal string
* `b` for boolean, which encodes to `1` for "true" or `0` for "false" 
* `p` for standard principal, which will be encoded as an upper-case c32check string
* `c` for contract principal, which will be encoded as an upper-case c32check string
* `n` for a Clarity item name.  All Clarity items are encoded in ASCII already,
  so converting them to a hex string is unnecessary.  In particular, this encoding is used for
tuple names and asset names.
* `t` for tuple.  Each item name is encoded as `n${len(name)}:${name},` followed
  by its encoded value.  The name and value are in turn encoded as `t${total-len}:n${len(name)}:${name},${value_type}${len(value)}:${value},,`
* `o` for option.
   * `some x` is encoded as `o${len(x) + 4}:${x_type}${encode(x)},`.
   * `none` is encoded as `o0:`
* `r` for result.
   * `ok x` is encoded as `r${len(x) + 3}:o${x_type}${encode(x)},`
   * `err x` is encoded as `r${len(x) + 3}:e${x_type}${encode(x)},`
* `l` for list, which acts as a container for the above items.  Note that all
  items in a list must have the same type.  The length of a list is the total
length of its encoded items.
```

**Comment by kantai** [comment]
The `ClarityValue` JSON schema is a recursive schema, where a value is one of:

* `bool` -> JSON boolean value (e.g., `true` | `false`)
* `int` -> `{ type: "i128", value: String }`, where `value` is a b64 encoding of the big-endian representation of the signed integer value.
* `buff` -> `{ type: "buff", value: String }` where `value` is a b64 encoding of the buffer value.
* standard `principal` -> `{ type: "principal", value: String }` where `value` is the c32check encoding of the standard principal
* contract `principal` -> `{ type: "contract_principal", namespace: String, name: String }` where `namespace` is the c32check encoding of the publishing principal, and `name` is the ASCII name for the contract.
* `some` -> `{ type: "some", value: ClarityValue }`
* `none` -> `{ type: "none" }`
* `ok` -> `{ type: "ok", value: ClarityValue }`
* `err` -> `{ type: "err", value: ClarityValue }`
* `list` -> `{ type: "list", entries: [ ClarityValue, ... ] }`

**Comment by kantai** [comment]
Closed by #1099

**Comment by kantai** [comment]
Reopening!

JSON isn't great for the serialization format here, since we want the value to actually be a bit more compact when it comes to things like transaction generation.

**Comment by njordhov** [comment]
> A key requirement for the serialization format is that it be a bijective mapping (i.e. 1-to-1) from Clarity values to serializations.

A subset of [EDN](https://github.com/edn-format/edn) could be a candidate, with a related syntax for the data as in the Clarity language.

**Comment by jcnelson** [comment]
Thanks for the suggestion, but edn looks to be incompatible with the first requirement:

> have a much more efficient serialization scheme

We need something that uses as few bytes as possible, since there is no such thing as deleting blockchain data.

**Comment by njordhov** [comment]
Is there a draft specification for the binary serialization format available yet?

**Comment by kantai** [comment]
A spec and implementation can be found in this PR:

https://github.com/blockstack/blockstack-core/pull/1199

**Comment by kantai** [comment]
This was implemented in #1199
