### ISSUE TITLE
Fill in block-time stub in block-info

### ISSUE THREAD

**Issue by zone117x** [blockstack/blockstack-core#949]
### Motivation

Make absolute time easier to work with in smart contracts. 

The current method for estimating the absolute time requires hardcoding in a timestamp during contract deployment. For example:

```scm
(define height-at-launch block-height)
(define time-at-launch 1557237920)
(define block-time (* 60 10))

(define (estimate-current-time)
  (+ time-at-launch 
    (* (- block-height height-at-launch) block-time)))
```

### Implementation

Expose the bitcoin median timestamp as a built in variable, similar to `block-height`. Should be explicitly named so that it is immediately clear that the timestamp is not realtime, for example `median-time`. 

### Usage reliability

Bitcoin defines median time as:
> The median time of the 11 blocks before the most recent block on the blockchain. Used for validating transaction locktime under [BIP113](https://github.com/bitcoin/bips/blob/master/bip-0113.mediawiki).

BIP113 states that it ensures this median time "increases monotonically with each block". 

> The block time is a Unix epoch time when the miner started hashing the header (according to the miner). Must be strictly greater than the median time of the previous 11 blocks. Full nodes will not accept blocks with headers more than two hours in the future according to their clock.

See here for block timestamp validation src: https://github.com/bitcoin/bitcoin/blob/0.18/src/validation.cpp#L3258

The `mediantime` is included in several bitcoin RPC methods ([`getblock`](https://bitcoincore.org/en/doc/0.18.0/rpc/blockchain/getblock/), [`getblockchaininfo`](https://bitcoincore.org/en/doc/0.18.0/rpc/blockchain/getblockchaininfo/), [`getblockstats`](https://bitcoincore.org/en/doc/0.18.0/rpc/blockchain/getblockstats), etc).

Additionally, lightning network depends on this variable for CTLV timelocks https://github.com/lightningnetwork/lnd/search?p=2&q=CLTV&unscoped_q=CLTV

**Comment by jcnelson** [comment]
The absolute time would be exposed from the underlying burn chain, since our blockchain derives its notion of time from the burn chain already.  The absolute time also would have a pretty high margin of error, since most burn chains have to allow for significant clock skew already.  As such, while I'm not opposed to exposing this information, I'd want to make sure we call it something indicative of this behavior, like `block_timestamp` or something.

**Comment by kantai** [comment]
This is going to be subsumed by #950 and #951

**Comment by zone117x** [comment]
Some historical data on the median timestamps:

The soft fork activating BIP113 was occurred on May 1st, 2017 -- around 110,000 blocks ago. 
 
Here's an attempt at graphing the median-time delta distribution curve for all the blocks in the past ~2 years https://docs.google.com/spreadsheets/d/1k5kVtA-m8v3yJ3V9iRMhOHkambn_aCanIQv0YR_aSwM/edit?usp=sharing

Attaching the block header dataset used. Flat csv file containing `height,time,median_time,hash,version_hex` of last ~175k blocks [block_time_data.zip](https://github.com/blockstack/blockstack-core/files/3167487/block_time_data.zip)

**Comment by kantai** [comment]
#1233 added a panicking stub for getting this information out of the block header db -- @jcnelson, do you want to take over this issue for filling in that stub?
