### ISSUE TITLE
Implement naming scheme for contracts

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#952]
Contract names are going to be defined as:

PRINCIPAL.CHOSEN-NAME

Where Principal is the publishing principal, and chosen name is composed of lowercase letters, underscores, and periods, with some maximum length.

`(contract-call!` and `(contract-call` will be default _namespaced_ such that if a principal is _not_ supplied, the referenced contract is of the same principal as the current contract.

**Comment by lgalabru** [comment]
In this context, is principal a C32 encoded string or a Blockstack-id?

**Comment by kantai** [comment]
It would be a C32 encoded string.

**Comment by jcnelson** [comment]
To be clear, `(contract-call!` _must_ take something that evaluates at deploy-time to a literal `PRINCIPAL.CHOSEN-NAME`, right?  We don't want to support dynamic dispatch.  So, we'd support something like this, right?

```
(define my-contract-func 'SP28V3NX23SEFVDQA19A8YEJY90Z82NXN89X4Z97B.hello_world)
;; ...
(contract-call! my-contract-func ;; ...
```

**Comment by kantai** [comment]
Closing in favor of #1078
