### ISSUE TITLE
Specify runtime error behavior of smart contracts

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#956]
There's a couple possible "runtime errors" in the execution of a transaction:

1. Arithmetic errors (underflows, overflows, division by zero)
2. Attempts to use Void/Null types

Currently, these errors cause the current function to abort. Such aborts will stop _all_ processing of a transaction (i.e., if an outer function called an error-inducing public function, that function is aborted as well).

This need not necessarily be the case: we could alternatively have the function which caused such an error return false to the caller.

What are people's thoughts on this?

**Comment by jcnelson** [comment]
+1 for having the functions abort.  Developers who do not want aborts should be (1) checking the operands and (2) checking the return type.  Regarding (1), we can make a "safe-math" library that does the checks for users.

**Comment by lgalabru** [comment]
Is a library a contract, deployed on chain, that I can invoke from my contract?

**Comment by kantai** [comment]
Closing for now -- we've decided to keep runtime errors as uncatchable aborts. If we want to revisit this spec, we can open an issue later on.
