### ISSUE TITLE
Cute sample application to demo

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack-core#960]
## It should demonstrate this functionality

- Interaction with balances; call the token contract so you see a shift with the token balances
- notion of time should be demonstrated --- interact with the get block info time
- include non-fungible asset illustration --- so a rocketship or building  a house
- some gamified element to it that riffs on the language name perhaps (crypto kitties)
- runs entirely local in docker container
- interacts or inter dependency on other contracts

## Bonus points

Add in some "social" outcome like completion of the contract can be posted on Twitter or Instagram.

## Example

For example build rocketship call that lets you call the contract. You can then specify some parameters that affect the cost and the time to build.  Like you build the rocketship and you can't use it to some point in time.

Not a requirement:
- wallets 
- teach a build from scratch
- rely on the SDK in any way

**Comment by kantai** [comment]
This was implemented over in https://github.com/blockstack/clarity-js-sdk/pull/4 -- thanks @lgalabru !
