### ISSUE TITLE
Allowing return types in public functions

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#969]
@lgalabru brought up the possibility of returning more data when a public function returns `false`.

We could change the boolean result requirement on public functions to a typed-tuple requirement, where the typed tuple must _at least_ have a "success" field. That way, public functions could chose to return data alongside the status.

The question is whether or not we think this would improve the usability of the language, or add to much complication.

**Comment by jcnelson** [comment]
Relevant: #975

**Comment by kantai** [comment]
So what we'll do instead of using the typed tuples is we'll introduce a _result_ type, similar to what we're going to add for the datamap return type (which would be an _option_ type).
