### ISSUE TITLE
Inter-contract calling convention

### ISSUE THREAD

**Issue by zone117x** [blockstack/blockstack-core#980]
_Branching off of https://github.com/blockstack/blockstack-core/issues/969_

We have inter-contract callable read-only functions, but still use the mutability-implying `contract-call!` function for invoking. 

Should we implement a `contract-call` (no mutability indicating `!`) for invoking read-only functions?

**Comment by jcnelson** [comment]
I anticipate that a one-character difference is going to be a source of typo-induced bugs.  Maybe call it something like `call!` or `call-ro`?

**Comment by zone117x** [comment]
I agree it will be typo inducing, but I think they would be caught and enforced during type-checking (rather than runtime bugs)

**Comment by kantai** [comment]
I don't have a strong opinion on whether we should add a new kind of contract-call that only allows read-only calls, but if we do, I think it should differ by more than one character -- so something like `call!` versus `call-ro` would be okay with me.
