### ISSUE TITLE
Deny contract-call! on certain methods

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#981]
As @lgalabru helped me understand, there exists a social engineering attack vector whereby someone can trick you into calling a smart contract method that, in turn, calls a security-sensitive method within another smart contract you own.  For example, if you're the owner of a fungible token smart contract, you can be tricked into minting tokens this way because the malicious contract (which may impersonate something plausibly innocent like a DEX contract) can indirectly call your contract's `mint` method.

One remediation would be to add a way to define a public function that _must not_ be called via `contract-call!` -- that is, it must be called only through a direct transaction.  You might call this `define-public-txonly` or something.

**Comment by jcnelson** [comment]
I'm also open to the inverse of this -- we make all functions callable only by a transaction by default, and require the developer to additionally mark a function as callable by a contract.  This could be `define-public-contract` or `define-contract` or the like.

**Comment by kantai** [comment]
This is what I'd propose:

We have 4 types of functions:

```
(define-public ...) ;; callable by other contracts and by other functions in the contract, must return Response<A,B> type. Database modifications are rolled back on `err`, materialized on `ok`.
(define-private ...) ;; callable only by other functions in the contract
(define-read-only ...) ;; callable by other contract and by other functions in the contract. cannot make any database changes.
(define-transaction ...) ;; only callable by issuing a transaction.
```

Best practice will be to _minimize_ the usage of `define-public`, only exposing as public functions intended to be called by other contracts -- this means that authorization checks must be performed, and _should not_ typically use `tx-sender` as an owner (per #982).

**Comment by kantai** [comment]
The alternative is:

```
(define-public ...) ;; callable by other contracts, by other functions in the contract, and by issuing a transaction on the blockchain. Must return Response<A,B> type. Database modifications are rolled back on `err`, materialized on `ok`.
(define-private ...) ;; callable only by other functions in the contract
(define-read-only ...) ;; callable by other contract and by other functions in the contract. cannot make any database changes.
```

And `tx-sender` _always_ changes on executing `contract-call!`

**Comment by kantai** [comment]
From out-of-band discussion, we reached consensus around the idea of:

1. Modifying our current `tx-sender` behavior.
2. Adding `tx-origin`.

**Comment by moxiegirl** [comment]
Make sure you describe the current behavior some place so I can pick it up in the documentation.

**Comment by kantai** [comment]
Closing this in favor of #1051 -- if we want to go a different route than the one described there, we can revisit.
