### ISSUE TITLE
Do not require strict function ordering

### ISSUE THREAD

**Issue by zone117x** [blockstack/blockstack-core#985]
Top level function definition ordering is unnecessarily strict. The type checker will report a function as undefined if it is invoked before its declaration.

**Comment by jcnelson** [comment]
What's wrong with that?

**Comment by lgalabru** [comment]
I was also surprised by this. 
I personally don't have a strong opinion about it, however if we're not considering working on this constraint (cc @kantai), we should definitely document it (cc @moxiegirl).

**Comment by kantai** [comment]
I think we should fix this --- almost no modern compilers will complain about this kind of ordering.

**Comment by lgalabru** [comment]
Handled with #1079
