### ISSUE TITLE
Expand areas where tuple-shorthand syntax is allowed

### ISSUE THREAD

**Issue by zone117x** [blockstack/blockstack-core#986]
Currently terse/implicit tuples are allowed in `define-map`. The  other commonly used map functions require verbose `tuple(...)` expressions.

**Comment by kantai** [comment]
Yep -- I like this idea.

So, for the data-map functions you'd be able to write something like:

```
(set-entry map0 ((id 102)) ((name "goo") (owner tx-sender)))
```

Though I think this would have to be special-cased, since we'd also want to be able to accept a variable value as an argument, e.g.:

```
(let ((a (tuple ...)))
   (fetch-entry map0 a))
```
