### ISSUE TITLE
Export name of arguments in the contract interface

### ISSUE THREAD

**Issue by lgalabru** [blockstack/blockstack-core#990]
Running

```bash
$ clarity check path/contract.cla

```

Returns a `json` describing the contract (private funcs, public funcs, etc).
We would like to leverage this payload for generating typings / autocompletions (js side), and make the life of our developers easier.

At this point, a method's description looks like:

```json
"transfer!": {
    "Fixed": [
        [
            {
                "atomic_type": "PrincipalType",
                "list_dimensions": null
            },
            {
                "atomic_type": "PrincipalType",
                "list_dimensions": null
            },
            {
                "atomic_type": "IntType",
                "list_dimensions": null
            }
        ],
        {
            "atomic_type": "BoolType",
            "list_dimensions": null
        }
    ]
}

``` 

We can't complete our goal, without having the name of the arguments in the description.

**Comment by zone117x** [comment]
I overloaded the `ContractAnalysis` struct originally as a quick way to get something like a contract interface JSON from the CLI. 
I think we'll need a new struct that is better suited to represent the contract interface.

**Comment by kantai** [comment]
> I think we'll need a new struct that is better suited to represent the contract interface.

Yep -- I agree. We can also use the `developer-mode` compile flag (currently defaults to "on"), to control whether or not the checker passes construct that new ABI struct.
