### ISSUE TITLE
Add support for "contract global variables"

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#999]
Currently, the only storage method we support is data maps. However, it will likely be very common for contracts to need to manage global variable-like storage. This is, of course, possible using data maps by creating a data map with something like single entry, however, that's a onerous pattern and one likely to cause errors. We could instead support a notion of global variables, which can be manipulated via something like a `(set ...)` function (but would behave otherwise exactly like data in data maps -- automatic rollbacks on errors, etc.)

**Comment by jcnelson** [comment]
Would this be a library function or a native function?

**Comment by kantai** [comment]
Native -- if it were a library function, it'd be a pretty awkward interface.

**Comment by lgalabru** [comment]
@kantai should we also introduce a new native function for defining a new variable - `define-var`?

**Comment by kantai** [comment]
Yep

**Comment by lgalabru** [comment]
Do we want to define a var with a type or a value and infer the type from there?
`(define-var cursor int)` vs `(define-var cursor 0)`

**Comment by kantai** [comment]
Define with the type, since list types wouldn't necessarily be inferable.

 `(define-var` is probably not quite the right name, though more obtuse, maybe something like:

`(define-data-var cursor int)`

**Comment by jcnelson** [comment]
Would there be public/private globals?  Or would they all be public like data maps?

**Comment by kantai** [comment]
> Would there be public/private globals? Or would they all be public like data maps?

All public, like data maps.

**Comment by lgalabru** [comment]
As a smart contract developer, can I invoke `set`:
- for mutating a "variable" declared with `(define totalSupply 100)`?
- for mutating a "variable" declared with `(let totalSupply 100)`?

**Comment by kantai** [comment]
> As a smart contract developer, can I invoke set:
> for mutating a "variable" declared with (define totalSupply 100)?
> for mutating a "variable" declared with (let totalSupply 100)?

No -- you cannot

**Comment by kantai** [comment]
This was addressed in #1022, closing.
